parla.cython.device.DeviceConfiguration Class Reference
Public Member Functions
def __repr__ (self)
Static Public Attributes
int
long
Static Private Attributes
dictionary __annotations__
Detailed Description
A dataclass to represent a device configuration.
Definition at line 80 of file device.pyx.
Member Function Documentation
__repr__()
def parla.cython.device.DeviceConfiguration.__repr__ (self)
Definition at line 96 of file device.pyx.
    def __repr__(self):
        return f"DeviceConfiguration(device_type={self.device_type}, device_id={self.device_id}, memory={self.memory_size}, vcus={self.num_vcus})"
@dataclass
Referenced by parla.common.globals.Storage.__str__(), parla.common.globals.LocalStack.__str__(), parla.cython.device.Stream.__str__(), parla.cython.device.CupyStream.__str__(), and parla.cython.tasks.TaskState.__str__().
Member Data Documentation
__annotations__
dictionary parla.cython.device.DeviceConfiguration.__annotations__ [static], [private]
Initial value:
= {
        "type": PyDeviceType,
        "id": int,
        "memory": long,
        "vcus": int
    }
Definition at line 89 of file device.pyx.
int
parla.cython.device.DeviceConfiguration.int [static]
Definition at line 85 of file device.pyx.
long
parla.cython.device.DeviceConfiguration.long [static]
Definition at line 86 of file device.pyx.
The documentation for this class was generated from the following file:
src/python/parla/cython/device.pyx