MemoryReserver Class Reference
MemoryReserver phase of the scheduler.
#include <phases.hpp>
Public Member Functions
MemoryReserver (InnerScheduler *scheduler, DeviceManager *devices)
void enqueue (InnerTask *task)
Enqueue a task to the phase.
void enqueue (std::vector< InnerTask * > &tasks)
Enqueue a vector of tasks to the phase.
void run (SchedulerPhase *next_phase)
Run the phase. Check tasks in the enqueued buffer, check phase condition, and move tasks to the next phase.
size_t get_count ()
Get the number of tasks enqueued (and waiting) in the phase.
Protected Member Functions
bool check_resources (InnerTask *task)
Check if the PersistentResources are available for a task.
void reserve_resources (InnerTask *task)
Reserve (decrease) the PersistentResources for a task.
void create_datamove_tasks (InnerTask *task)
Create, assign dependencies, and enqueue data movement tasks for the task.
Protected Attributes
std::shared_ptr< PhaseManager< ResourceCategory::Persistent > > reservable_tasks
MemoryReserverStatus status {name}
std::vector< InnerTask * > reserved_tasks_buffer
Static Protected Attributes
static const std::string name {`Memory Reserver`}
Detailed Description
MemoryReserver phase of the scheduler.
Reserves all 'persistent resources.
This phase plans task execution on the device set. Here all 'persistent resources that have a lifetime greater than the task body are reserved and shared between tasks. Typically this means the memory that the task uses for both its input, output, and intermediate workspace. Memory usage is planned and reserved ahead of task execution to allow input data to be prefetched onto the devices through data movement tasks.
Note
Assumption: This is the only part of the runtime that decreases the PersistentResources. Otherwise there will be race conditions without a lock on the ResourcePool.
Definition at line 244 of file phases.hpp.
Constructor & Destructor Documentation
MemoryReserver()
MemoryReserver::MemoryReserver (InnerScheduler * scheduler, DeviceManager * devices) [inline]
Definition at line 246 of file phases.hpp.
      : SchedulerPhase(scheduler, devices) {
    this->reservable_tasks =
        std::make_shared<PhaseManager<ResourceCategory::Persistent>>(devices);
  }
References SchedulerPhase::SchedulerPhase().
Referenced by InnerScheduler::InnerScheduler().
Member Function Documentation
check_resources()
bool MemoryReserver::check_resources (InnerTask * task) [protected]
Check if the PersistentResources are available for a task.
Parameters
task The task to check the PersistentResources for.
Definition at line 151 of file phases.cpp.
                                                    {
  bool status = true;
  for (Device *device : task->assigned_devices) {
    ResourcePool_t &task_pool =
        task->device_constraints[device->get_global_id()];
    ResourcePool_t &device_pool = device->get_reserved_pool();
    status = device_pool.check_greater<ResourceCategory::Persistent>(task_pool);
    if (!status) {
      break;
    }
  }
  return status;
}
create_datamove_tasks()
void MemoryReserver::create_datamove_tasks (InnerTask * task) [protected]
Create, assign dependencies, and enqueue data movement tasks for the task.
Parameters
task The task to create data movement tasks for.
Definition at line 178 of file phases.cpp.
                                                          {
  // Get a list of the parrays the current task holds.
  const std::vector<std::vector<std::pair<parray::InnerPArray *, AccessMode>>>
      &parray_list = task->parray_list;
  std::string task_base_name = task->get_name();
  std::vector<InnerTask *> data_tasks;
  data_tasks.reserve(parray_list.size());
  for (size_t i = 0; i < parray_list.size(); ++i) {
    for (size_t j = 0; j < parray_list[i].size(); ++j) {
      // Create a data movement task for each PArray.
      parray::InnerPArray *parray = parray_list[i][j].first;
      AccessMode access_mode = parray_list[i][j].second;
      InnerDataTask *datamove_task = new InnerDataTask(
          // TODO(hc): id should be updated!
          task_base_name + ".dm." + std::to_string(i), 0, parray, access_mode,
          i);
      auto &parray_task_list = parray->get_parent_parray()->get_task_list_ref();
      // Find dependency intersection between compute and data movement tasks.
      // TODO(hc): This is not the complete implementation.
      // We will use a concurrent map for parray's
      // task list as an optimization.
      std::vector<void *> compute_task_dependencies = task->get_dependencies();
      std::vector<InnerTask *> data_task_dependencies;
      for (size_t k = 0; k < compute_task_dependencies.size(); ++k) {
        InnerTask *parray_dependency =
            static_cast<InnerTask *>(compute_task_dependencies[k]);
        // The task list in PArray is currently thread safe since
        // we do not remove tasks from the list but just keep even completed
        // task as its implementation is easier.
        for (size_t t = 0; t < parray_task_list.size(); ++t) {
          if (parray_task_list.at(t)->id == parray_dependency->id) {
            data_task_dependencies.push_back(parray_dependency);
          }
        }
      }
      // TODO(hc): pass false to add_dependencies() as optimization.
      datamove_task->add_dependencies(data_task_dependencies, true);
      // Copy assigned devices to a compute task to a data movement task.
      // TODO(hc): When we support xpy, it should be devices corresponding
      // to placements of the local partition.
      auto device = task->get_assigned_devices()[i];
      datamove_task->add_assigned_device(device);
      datamove_task->device_constraints.emplace(
          std::piecewise_construct,
          std::forward_as_tuple(device->get_global_id()),
          std::forward_as_tuple(0, 0, 1));
      data_tasks.push_back(datamove_task);
      // Add the created data movement task to a reserved task queue.
      this->scheduler->increase_num_active_tasks();
      this->reserved_tasks_buffer.push_back(datamove_task);
    }
  }
  // Create dependencies between data move task and compute tasks.
  task->add_dependencies(data_tasks, true);
}
enqueue() [1/2]
void MemoryReserver::enqueue (InnerTask * task) [virtual]
Enqueue a task to the phase.
Implements SchedulerPhase.
Definition at line 136 of file phases.cpp.
                                            {
  this->reservable_tasks->enqueue(task);
}
Referenced by InnerScheduler::enqueue_task().
enqueue() [2/2]
void MemoryReserver::enqueue (std::vector< InnerTask * > & tasks) [virtual]
Enqueue a vector of tasks to the phase.
Implements SchedulerPhase.
Definition at line 140 of file phases.cpp.
                                                          {
  for (InnerTask *task : tasks) {
    this->enqueue(task);
  }
}
get_count()
size_t MemoryReserver::get_count () [virtual]
Get the number of tasks enqueued (and waiting) in the phase.
Implements SchedulerPhase.
Definition at line 146 of file phases.cpp.
                                 {
  size_t count = this->reservable_tasks->size();
  return count;
}
reserve_resources()
void MemoryReserver::reserve_resources (InnerTask * task) [protected]
Reserve (decrease) the PersistentResources for a task.
Parameters
task The task to reserve the PersistentResources for.
Definition at line 167 of file phases.cpp.
                                                      {
  // TODO(wlr): Add runtime error check if resource failure
  for (Device *device : task->assigned_devices) {
    ResourcePool_t &task_pool =
        task->device_constraints[device->get_global_id()];
    ResourcePool_t &device_pool = device->get_reserved_pool();
    device_pool.decrease<ResourceCategory::Persistent>(task_pool);
  }
}
run()
void MemoryReserver::run (SchedulerPhase * next_phase) [virtual]
Run the phase. Check tasks in the enqueued buffer, check phase condition, and move tasks to the next phase.
Parameters
next_phase The next phase to move tasks to.
Implements SchedulerPhase.
Definition at line 241 of file phases.cpp.
                                                   {
  NVTX_RANGE("MemoryReserver::run", NVTX_COLOR_LIGHT_GREEN)
  // std::cout << "MemoryReserver::run" << std::endl;
  RuntimeReserver *runtime_reserver =
      dynamic_cast<RuntimeReserver *>(next_phase);
  // Only one thread can reserve memory at a time.
  // Useful for a multi-threaded scheduler. Not needed for a single-threaded.
  // std::unique_lock<std::mutex> lock(this->mtx);
  // TODO:: Dummy implementation that just passes tasks through
  bool has_task = this->get_count() > 0;
  while (has_task) {
    InnerTask *task = this->reservable_tasks->front();
    if (task == nullptr) {
      throw std::runtime_error("MemoryReserver::run: task is nullptr");
    }
    // Is there enough memory on the devices to schedule this task?
    bool can_reserve = this->check_resources(task);
    if (can_reserve) {
      this->reserve_resources(task);
      this->reservable_tasks->pop();
      this->create_datamove_tasks(task);
      this->reserved_tasks_buffer.push_back(task);
    } else {
      // TODO:(wlr) we need some break condition to allow the scheduler to
      // continue if not enough resources are available Hochan, do you
      // have any ideas? One failure per scheduler loop (written here) is
      // bad. Is one failure per device per scheduler loop better?
      break;
    }
    has_task = this->get_count() > 0;
  }
  for (InnerTask *reserved_task : this->reserved_tasks_buffer) {
    reserved_task->notify_dependents(this->enqueue_buffer, TaskState::RESERVED);
    this->scheduler->enqueue_tasks(this->enqueue_buffer);
    this->enqueue_buffer.clear();
    // TODO:(wlr) Create and possibly enqueue data movement tasks
    // Possibly enqueue this task
    bool enqueue_flag =
        (reserved_task->num_blocking_dependencies.fetch_sub(1) == 1);
    if (enqueue_flag) {
      reserved_task->set_status(TaskStatus::RUNNABLE);
      runtime_reserver->enqueue(reserved_task);
    }
  }
  this->reserved_tasks_buffer.clear();
}
Referenced by InnerScheduler::activate().
Member Data Documentation
name
const std::string MemoryReserver::name {`Memory Reserver`} [inline], [static], [protected]
Definition at line 259 of file phases.hpp.
Referenced by parla.cython.tasks.Task::__hash__(), parla.cython.tasks.Task::get_name(), parla.cython.tasks.Task::unpack_name(), and parla.cython.tasks.Task::update_name().
reservable_tasks
std::shared_ptr<PhaseManager<ResourceCategory::Persistent> > MemoryReserver::reservable_tasks [protected]
Definition at line 258 of file phases.hpp.
reserved_tasks_buffer
std::vector<InnerTask *> MemoryReserver::reserved_tasks_buffer [protected]
Definition at line 261 of file phases.hpp.
status
MemoryReserverStatus MemoryReserver::status {name} [protected]
Definition at line 260 of file phases.hpp.
Referenced by parla.cython.scheduler.WorkerThread::run().
The documentation for this class was generated from the following files:
src/c/backend/include/phases.hpp
src/c/backend/phases.cpp