parla.cython.tasks.TaskSpawned Class Reference
This state specifies that a task is ready to be mapped to a specific device set.
Public Member Functions
def value (self)
def is_terminal (self)
Detailed Description
This state specifies that a task is ready to be mapped to a specific device set.
Definition at line 82 of file tasks.pyx.
Member Function Documentation
is_terminal()
def parla.cython.tasks.TaskSpawned.is_terminal (self)
Reimplemented from parla.cython.tasks.TaskState.
Definition at line 91 of file tasks.pyx.
    def is_terminal(self):
        return False
Referenced by parla.cython.tasks.TaskEnvironment.streams(), and parla.cython.tasks.TaskEnvironment.synchronize().
value()
def parla.cython.tasks.TaskSpawned.value (self)
Reimplemented from parla.cython.tasks.TaskState.
Definition at line 87 of file tasks.pyx.
    def value(self):
        return 1
Referenced by parla.utility.threads.Propagate.run().
The documentation for this class was generated from the following file:
src/python/parla/cython/tasks.pyx