parla.cython.tasks.CPUEnvironment Class Reference
Public Member Functions
def __init__ (self, device, blocking=False)
def __repr__ (self)
def __enter__ (self)
def __exit__ (self, exc_type, exc_val, exc_tb)
def __len__ (self)
def __getitem__ (self, index)
def finalize (self)
def return_streams (self)
Additional Inherited Members
Detailed Description
Definition at line 1254 of file tasks.pyx.
Constructor & Destructor Documentation
__init__()
def parla.cython.tasks.CPUEnvironment.__init__ (self, device, blocking = False)
Reimplemented from parla.cython.tasks.TerminalEnvironment.
Definition at line 1256 of file tasks.pyx.
    def __init__(self, device, blocking=False):
        super(CPUEnvironment, self).__init__(device, blocking=blocking)
Member Function Documentation
__enter__()
def parla.cython.tasks.CPUEnvironment.__enter__ (self)
Reimplemented from parla.cython.tasks.TaskEnvironment.
Definition at line 1262 of file tasks.pyx.
    def __enter__(self):
        #print("Entering CPU Environment: ", self, flush=True)
        Locals.push_context(self)
        return self
__exit__()
def parla.cython.tasks.CPUEnvironment.__exit__ (self, exc_type, exc_val, exc_tb)
Reimplemented from parla.cython.tasks.TaskEnvironment.
Definition at line 1267 of file tasks.pyx.
    def __exit__(self, exc_type, exc_val, exc_tb):
        #print("Exiting CPU Environment: ", self, flush=True)
        Locals.pop_context()
        return False
__getitem__()
def parla.cython.tasks.CPUEnvironment.__getitem__ (self, index)
Reimplemented from parla.cython.tasks.TerminalEnvironment.
Definition at line 1275 of file tasks.pyx.
    def __getitem__(self, index):
        if index == 0:
            return self
__len__()
def parla.cython.tasks.CPUEnvironment.__len__ (self)
Reimplemented from parla.cython.tasks.TerminalEnvironment.
Definition at line 1272 of file tasks.pyx.
    def __len__(self):
            return 1
__repr__()
def parla.cython.tasks.CPUEnvironment.__repr__ (self)
Reimplemented from parla.cython.tasks.TerminalEnvironment.
Definition at line 1259 of file tasks.pyx.
    def __repr__(self):
        return f"CPUEnvironment({self._device})"
Referenced by parla.common.globals.Storage.__str__(), parla.common.globals.LocalStack.__str__(), parla.cython.device.Stream.__str__(), and parla.cython.device.CupyStream.__str__().
finalize()
def parla.cython.tasks.CPUEnvironment.finalize (self)
Reimplemented from parla.cython.tasks.TaskEnvironment.
Definition at line 1279 of file tasks.pyx.
    def finalize(self):
        pass
return_streams()
def parla.cython.tasks.CPUEnvironment.return_streams (self)
Reimplemented from parla.cython.tasks.TaskEnvironment.
Definition at line 1282 of file tasks.pyx.
    def return_streams(self):
        pass
The documentation for this class was generated from the following file:
src/python/parla/cython/tasks.pyx