DeviceManager Class Reference
DeviceManager registers/provides devices and their information on the current system to the Parla runtime.
#include <device_manager.hpp>
Public Member Functions
DeviceManager ()
DeviceManager (const DeviceManager &)=delete
void register_device (Device *new_dev)
void print_registered_devices ()
template<DeviceType T>
int get_num_devices ()
int get_num_devices (DeviceType dev_type)
template<DeviceType T>
std::vector< Device * > & get_devices ()
Device * get_device_by_parray_id (DevID_t parray_dev_id) const
Device * get_device_by_global_id (DevID_t global_dev_id) const
std::vector< Device * > & get_devices (DeviceType dev_type)
size_t get_num_devices ()
const DevID_t globalid_to_parrayid (DevID_t global_dev_id) const
const int parrayid_to_globalid (DevID_t parray_dev_id) const
Protected Attributes
DevID_t last_dev_id_ = 0
std::array< std::vector< Device * >, NUM_DEVICE_TYPES > arch_devices_
std::vector< Device * > all_devices_
Detailed Description
DeviceManager registers/provides devices and their information on the current system to the Parla runtime.
Definition at line 18 of file device_manager.hpp.
Constructor & Destructor Documentation
DeviceManager() [1/2]
DeviceManager::DeviceManager () [inline]
Definition at line 20 of file device_manager.hpp.
{}
DeviceManager() [2/2]
DeviceManager::DeviceManager (const DeviceManager &) [delete]
Member Function Documentation
get_device_by_global_id()
Device* DeviceManager::get_device_by_global_id (DevID_t global_dev_id) const [inline]
Definition at line 82 of file device_manager.hpp.
                                                               {
    return all_devices_[global_dev_id];
  }
get_device_by_parray_id()
Device* DeviceManager::get_device_by_parray_id (DevID_t parray_dev_id) const [inline]
Definition at line 77 of file device_manager.hpp.
                                                               {
    DevID_t global_dev_id = this->parrayid_to_globalid(parray_dev_id);
    return all_devices_[global_dev_id];
  }
get_devices() [1/2]
template<DeviceType T>
std::vector<Device *>& DeviceManager::get_devices () [inline]
Definition at line 67 of file device_manager.hpp.
                                                             {
    if constexpr (T == DeviceType::CPU) {
      return arch_devices_[static_cast<int>(DeviceType::CPU)];
    } else if constexpr (T == DeviceType::CUDA) {
      return arch_devices_[static_cast<int>(DeviceType::CUDA)];
    } else if constexpr (T == DeviceType::All) {
      return all_devices_;
    }
  }
References All, CPU, and CUDA.
Referenced by parla.cython.tasks.TaskEnvironment::get_cupy_devices().
get_devices() [2/2]
std::vector<Device *>& DeviceManager::get_devices (DeviceType dev_type) [inline]
Definition at line 86 of file device_manager.hpp.
                                                        {
    switch (dev_type) {
    case DeviceType::CPU:
      return get_devices<DeviceType::CPU>();
    case DeviceType::CUDA:
      return get_devices<DeviceType::CUDA>();
    default:
      return get_devices<DeviceType::All>();
    }
  }
References All, CPU, and CUDA.
Referenced by parla.cython.tasks.TaskEnvironment::get_cupy_devices().
get_num_devices() [1/3]
template<DeviceType T>
int DeviceManager::get_num_devices () [inline]
Definition at line 46 of file device_manager.hpp.
                                                {
    if constexpr (T == DeviceType::All) {
      return all_devices_.size();
    } else if constexpr (T == DeviceType::CPU) {
      return arch_devices_[static_cast<int>(DeviceType::CPU)].size();
    } else if constexpr (T == DeviceType::CUDA) {
      return arch_devices_[static_cast<int>(DeviceType::CUDA)].size();
    }
  }
References All, CPU, and CUDA.
get_num_devices() [2/3]
size_t DeviceManager::get_num_devices () [inline]
Definition at line 97 of file device_manager.hpp.
{ return all_devices_.size(); }
get_num_devices() [3/3]
int DeviceManager::get_num_devices (DeviceType dev_type) [inline]
Definition at line 56 of file device_manager.hpp.
                                           {
    switch (dev_type) {
    case DeviceType::CPU:
      return get_num_devices<DeviceType::CPU>();
    case DeviceType::CUDA:
      return get_num_devices<DeviceType::CUDA>();
    default:
      return get_num_devices<DeviceType::All>();
    }
  }
References All, CPU, and CUDA.
globalid_to_parrayid()
const DevID_t DeviceManager::globalid_to_parrayid (DevID_t global_dev_id) const [inline]
Definition at line 101 of file device_manager.hpp.
                                                                  {
    Device *dev = all_devices_[global_dev_id];
    if (dev->get_type() == DeviceType::CPU) {
      return -1;
    } else {
      return dev->get_id();
    }
  }
References CPU, and Device::get_type().
parrayid_to_globalid()
const int DeviceManager::parrayid_to_globalid (DevID_t parray_dev_id) const [inline]
Definition at line 110 of file device_manager.hpp.
                                                              {
    if (parray_dev_id == -1) {
      // XXX: This assumes that a CPU device is always single and
      // is added at first.
      // Otherwise, we need a loop iterating all devices and
      // comparing device ids.
      return 0;
    } else {
      return parray_dev_id + 1;
    }
  }
print_registered_devices()
void DeviceManager::print_registered_devices () [inline]
Definition at line 30 of file device_manager.hpp.
                                  {
    std::cout << "C++ device list:\n";
    for (DeviceType dev_type : architecture_types) {
      int i = static_cast<int>(dev_type);
      std::cout << "Device type: " << i << "\n";
      auto device_list = arch_devices_[i];
      for (auto j = 0; j < device_list.size(); ++j) {
        auto device = device_list[j];
        std::cout << "Device " << j << ": " << device->get_name()
                  << "\n\t mem. sz:" << device->get_memory_size()
                  << ", num. vcus:" << device->get_num_vcus() << "\n";
      }
    }
  }
register_device()
void DeviceManager::register_device (Device * new_dev) [inline]
Definition at line 23 of file device_manager.hpp.
                                        {
    new_dev->set_global_id(this->last_dev_id_++);
    const int idx = static_cast<int>(new_dev->get_type());
    arch_devices_[idx].emplace_back(new_dev);
    all_devices_.emplace_back(new_dev);
  }
References Device::get_type().
Member Data Documentation
all_devices_
std::vector<Device *> DeviceManager::all_devices_ [protected]
Definition at line 131 of file device_manager.hpp.
arch_devices_
std::array<std::vector<Device *>, NUM_DEVICE_TYPES> DeviceManager::arch_devices_ [protected]
Definition at line 129 of file device_manager.hpp.
last_dev_id_
DevID_t DeviceManager::last_dev_id_ = 0 [protected]
Definition at line 126 of file device_manager.hpp.
The documentation for this class was generated from the following file:
src/c/backend/include/device_manager.hpp