parla.cython.device_manager.PyDeviceManager Class Reference
Public Member Functions
def __init__ (self, dev_config=None)
def __dealloc__ (self)
def register_cupy_gpu_devices (self)
def register_cpu_devices (self, bool register_to_cuda=False)
def register_devices_to_cpp (self)
def print_registered_devices (self)
def get_cy_device_manager (self)
int get_num_gpus (self)
def get_devices (self, architecture_type)
int get_num_cpus (self)
PyArchitecture get_architecture (self, arch_type)
def parse_config_and_register_devices (self, yaml_config)
def get_all_devices (self)
def get_all_architectures (self)
def is_multidevice_placement (self, placement_tuple)
def construct_single_device_requirements (self, dev, res_req)
def construct_single_architecture_requirements (self, arch, res_req)
def construct_resource_requirements (self, placement_component, vcus, memory)
def unpack_placements (self, placement_components, vcus, memory)
def get_device_reqs_from_placement (self, placement, vcus, memory)
def globalid_to_parrayid (self, global_dev_id)
def parrayid_to_globalid (self, parray_dev_id)
Public Attributes
cy_device_manager
py_registered_archs
registered_devices
num_real_gpus
stream_pool
Detailed Description
A device manager manages device objects and provides their information.
The Parla runtime should access device information through a device manager.
A single device manager for each Python and C++ is created and held
by each schedulers.
Definition at line 125 of file device_manager.pyx.
Constructor & Destructor Documentation
__init__()
def parla.cython.device_manager.PyDeviceManager.__init__ (self, dev_config = None)
Definition at line 133 of file device_manager.pyx.
    def __init__(self, dev_config = None):
        self.cy_device_manager = CyDeviceManager()
        self.py_registered_archs = {}
        self.registered_devices = []
        if CUPY_ENABLED:
            try:
                self.num_real_gpus = cupy.cuda.runtime.getDeviceCount()
            except cupy.cuda.runtime.CUDARuntimeError:
                self.num_real_gpus = 0
        else:
            self.num_real_gpus = 0
        # Initialize Devices
        if dev_config == None or dev_config == "":
            self.register_cpu_devices()
            self.register_cupy_gpu_devices()
        else:
            self.parse_config_and_register_devices(dev_config)
        #self.register_devices_to_cpp()
        # Initialize Device Hardware Queues
        self.stream_pool = StreamPool(self.get_devices(DeviceType.CUDA))
Member Function Documentation
__dealloc__()
def parla.cython.device_manager.PyDeviceManager.__dealloc__ (self)
Definition at line 158 of file device_manager.pyx.
    def __dealloc__(self):
        for arch in self.py_registered_archs:
            for dev in arch.devices:
                del dev
References parla.cython.device_manager.PyDeviceManager.py_registered_archs.
construct_resource_requirements()
def parla.cython.device_manager.PyDeviceManager.construct_resource_requirements (self, placement_component, vcus, memory)
Definition at line 328 of file device_manager.pyx.
    def construct_resource_requirements(self, placement_component, vcus, memory):
        if isinstance(placement_component, Tuple) and \
              not self.is_multidevice_placement(placement_component):
                # In this case, the placement component consists of
                # Device or Architecture, with its resource requirement.
                placement, req = placement_component
                req.memory = req.memory if req.memory is not None else \
                    (0 if memory is None else memory)
                req.vcus = req.vcus if req.vcus is not None else \
                    (0 if vcus is not None else vcus)
                # If a device specified by users does not exit
                # and was not registered to the Parla runtime,
                # use CPU instead.
                if isinstance(placement, PyArchitecture):
                    # Architecture placement means that the task mapper
                    # could choose one of the devices in the specified
                    # architecture.
                    # For example, if `gpu` is specified, all gpu devices
                    # become target candidate devices and one of them
                    # might be chosen as the final placement for a task.
                    # To distinguish architecture placement from others,
                    # it is converted to a frozen set of the entire devices.
                    return self.construct_single_architecture_requirements(
                        placement, req)
                elif isinstance(placement, PyDevice):
                    return self.construct_single_device_requirements(
                        placement, req)
        elif isinstance(placement_component, PyArchitecture):
            vcus = vcus if vcus is not None else 0
            memory = memory if memory is not None else 0
            res_req = DeviceResource(memory, vcus)
            return self.construct_single_architecture_requirements(
                placement_component, res_req)
        elif isinstance(placement_component, PyDevice):
            vcus = vcus if vcus is not None else 0
            memory = memory if memory is not None else 0
            res_req = DeviceResource(memory, vcus)
            return self.construct_single_device_requirements(
                placement_component, res_req)
        else:
            raise TypeError("Incorrect placement")
References parla.cython.device_manager.PyDeviceManager.construct_single_architecture_requirements(), parla.cython.device_manager.PyDeviceManager.construct_single_device_requirements(), parla.cython.device_manager.DeviceResource, and parla.cython.device_manager.PyDeviceManager.is_multidevice_placement().
Referenced by parla.cython.device_manager.PyDeviceManager.unpack_placements().
construct_single_architecture_requirements()
def parla.cython.device_manager.PyDeviceManager.construct_single_architecture_requirements (self, arch, res_req)
Definition at line 321 of file device_manager.pyx.
    def construct_single_architecture_requirements(self, arch, res_req):
        arch_reqs = []
        for d in arch.devices:
            arch_reqs.append(self.construct_single_device_requirements(
                  d, res_req))
        return PrintableFrozenSet(arch_reqs)
References parla.cython.device_manager.PyDeviceManager.construct_single_device_requirements().
Referenced by parla.cython.device_manager.PyDeviceManager.construct_resource_requirements().
construct_single_device_requirements()
def parla.cython.device_manager.PyDeviceManager.construct_single_device_requirements (self, dev, res_req)
Definition at line 318 of file device_manager.pyx.
    def construct_single_device_requirements(self, dev, res_req):
        return DeviceResourceRequirement(dev, res_req)
References parla.cython.device_manager.DeviceResourceRequirement.
Referenced by parla.cython.device_manager.PyDeviceManager.construct_resource_requirements(), and parla.cython.device_manager.PyDeviceManager.construct_single_architecture_requirements().
get_all_architectures()
def parla.cython.device_manager.PyDeviceManager.get_all_architectures (self)
Definition at line 309 of file device_manager.pyx.
    def get_all_architectures(self):
        return self.py_registered_archs.values()
References parla.cython.device_manager.PyDeviceManager.py_registered_archs.
get_all_devices()
def parla.cython.device_manager.PyDeviceManager.get_all_devices (self)
Definition at line 306 of file device_manager.pyx.
    def get_all_devices(self):
        return self.registered_devices
References parla.cython.device_manager.PyDeviceManager.registered_devices.
Referenced by parla.cython.tasks.TaskEnvironment.devices().
get_architecture()
PyArchitecture parla.cython.device_manager.PyDeviceManager.get_architecture (self, arch_type)
Definition at line 266 of file device_manager.pyx.
    def get_architecture(self, arch_type) -> PyArchitecture:
        return self.py_registered_archs[arch_type]
References parla.cython.device_manager.PyDeviceManager.py_registered_archs.
get_cy_device_manager()
def parla.cython.device_manager.PyDeviceManager.get_cy_device_manager (self)
Definition at line 252 of file device_manager.pyx.
    def get_cy_device_manager(self):
        return self.cy_device_manager
References parla.cython.device_manager.PyDeviceManager.cy_device_manager.
get_device_reqs_from_placement()
def parla.cython.device_manager.PyDeviceManager.get_device_reqs_from_placement (self, placement, vcus, memory)
 Unpack placement and return device objects that are specified
    (or implied) through the placement argument of @spawn.
    If None is passed to the placement, all devices exiting
    in the current system become candidates of the placement. 
Definition at line 403 of file device_manager.pyx.
    def get_device_reqs_from_placement(self, placement, vcus, memory):
        """ Unpack placement and return device objects that are specified
            (or implied) through the placement argument of @spawn.
            If None is passed to the placement, all devices exiting
            in the current system become candidates of the placement. """
        # Placement cannot be None since it is set to a list of the whole
        # devices.
        assert placement is not None
        ps = placement if isinstance(placement, Iterable) else [placement]
        return self.unpack_placements(ps, vcus, memory)
References parla.cython.device_manager.PyDeviceManager.unpack_placements().
get_devices()
def parla.cython.device_manager.PyDeviceManager.get_devices (self, architecture_type)
Definition at line 258 of file device_manager.pyx.
    def get_devices(self, architecture_type):
        if architecture_type not in self.py_registered_archs:
            return []
        return self.py_registered_archs[architecture_type].devices
References parla.cython.device_manager.PyDeviceManager.py_registered_archs.
Referenced by parla.cython.tasks.TaskEnvironment.get_cupy_devices().
get_num_cpus()
int parla.cython.device_manager.PyDeviceManager.get_num_cpus (self)
Definition at line 263 of file device_manager.pyx.
    def get_num_cpus(self) -> int:
        return len(self.py_registered_archs[cpu].devices)
References parla.cython.device_manager.PyDeviceManager.py_registered_archs.
get_num_gpus()
int parla.cython.device_manager.PyDeviceManager.get_num_gpus (self)
Definition at line 255 of file device_manager.pyx.
    def get_num_gpus(self) -> int:
        return len(self.py_registered_archs[gpu].devices)
References parla.cython.device_manager.PyDeviceManager.py_registered_archs.
globalid_to_parrayid()
def parla.cython.device_manager.PyDeviceManager.globalid_to_parrayid (self, global_dev_id)
Definition at line 414 of file device_manager.pyx.
    def globalid_to_parrayid(self, global_dev_id):
        return self.cy_device_manager.globalid_to_parrayid(global_dev_id)
References parla.cython.device_manager.PyDeviceManager.cy_device_manager.
is_multidevice_placement()
def parla.cython.device_manager.PyDeviceManager.is_multidevice_placement (self, placement_tuple)
Definition at line 312 of file device_manager.pyx.
    def is_multidevice_placement(self, placement_tuple):
        if len(placement_tuple) == 2 and \
                isinstance(placement_tuple[1], DeviceResource):
            return False
        return True
Referenced by parla.cython.device_manager.PyDeviceManager.construct_resource_requirements(), and parla.cython.device_manager.PyDeviceManager.unpack_placements().
parrayid_to_globalid()
def parla.cython.device_manager.PyDeviceManager.parrayid_to_globalid (self, parray_dev_id)
Definition at line 417 of file device_manager.pyx.
    def parrayid_to_globalid(self, parray_dev_id):
        return self.cy_device_manager.parrayid_to_globalid(parray_dev_id)
References parla.cython.device_manager.PyDeviceManager.cy_device_manager.
parse_config_and_register_devices()
def parla.cython.device_manager.PyDeviceManager.parse_config_and_register_devices (self, yaml_config)
Definition at line 269 of file device_manager.pyx.
    def parse_config_and_register_devices(self, yaml_config):
        with open(yaml_config, "r") as f:
            parsed_configs = yaml.safe_load(f)
            # Parse CPU device information.
            cpu_num_cores = parsed_configs["CPU"]["num_cores"]
            if cpu_num_cores > 0:
                cpu_arch = PyCPUArchitecture()
                self.py_registered_archs[cpu] = cpu_arch
                cpu_mem_sz = parsed_configs["CPU"]["mem_sz"]
                py_cpu_device = PyCPUDevice(0, cpu_mem_sz, VCU_BASELINE)
                cpu_arch.add_device(py_cpu_device)
                self.registered_devices.append(py_cpu_device)
                cy_device = py_cpu_device.get_cy_device()
                self.cy_device_manager.register_device(cy_device)
            num_of_gpus = parsed_configs["GPU"]["num_devices"]
            if num_of_gpus > 0:
                gpu_arch = PyCUDAArchitecture()
                self.py_registered_archs[gpu] = gpu_arch
                gpu_mem_sizes = parsed_configs["GPU"]["mem_sz"]
                assert(num_of_gpus == len(gpu_mem_sizes))
                
                for dev_id in range(num_of_gpus):
                    if self.num_real_gpus > 0:
                        py_cuda_device = PyCUDADevice(dev_id % self.num_real_gpus, \
                                                    gpu_mem_sizes[dev_id], \
                                                    VCU_BASELINE)
                    
                    else:
                        py_cuda_device = PyCPUDevice(dev_id, gpu_mem_sizes[dev_id], VCU_BASELINE)
                    gpu_arch.add_device(py_cuda_device)
                    self.registered_devices.append(py_cuda_device)
                    cy_device = py_cuda_device.get_cy_device()
                    self.cy_device_manager.register_device(cy_device)
References parla.cython.device_manager.PyDeviceManager.cy_device_manager, parla.cython.device_manager.PyDeviceManager.num_real_gpus, parla.cython.device_manager.PyDeviceManager.py_registered_archs, parla.cython.device_manager.PyCPUArchitecture, parla.cython.device_manager.PyCPUDevice, parla.cython.device_manager.PyCUDAArchitecture, parla.cython.device_manager.PyCUDADevice, and parla.cython.device_manager.PyDeviceManager.registered_devices.
print_registered_devices()
def parla.cython.device_manager.PyDeviceManager.print_registered_devices (self)
Definition at line 246 of file device_manager.pyx.
    def print_registered_devices(self):
        print("Python devices:", flush=True)
        for dev in self.py_registered_archs:
            print(f"\t Registered device: {dev}", flush=True)
        self.cy_device_manager.print_registered_devices()
References parla.cython.device_manager.PyDeviceManager.cy_device_manager, and parla.cython.device_manager.PyDeviceManager.py_registered_archs.
register_cpu_devices()
def parla.cython.device_manager.PyDeviceManager.register_cpu_devices (self, bool register_to_cuda = False)
Definition at line 198 of file device_manager.pyx.
    def register_cpu_devices(self, register_to_cuda: bool = False):
        #if register_to_cuda:
        # gpu.add_device(cpu(0))
        # self.registered_devices.append(cpu(0))
        # cy_device = cpu(0).get_cy_device()
        # self.cy_device_manager.register_device(cy_device)
        #else:
        # Get the number of usable CPUs from this process.
        # This might not be equal to the number of CPUs in the system.
        num_cores = os.getenv("PARLA_NUM_CORES")
        if num_cores:
            num_cores = int(num_cores)
        else:
            num_cores = len(os.sched_getaffinity(0))
        if num_cores == 0:
            raise RuntimeError("No CPU cores available for Parla.")
        mem_sz = os.getenv("PARLA_CPU_MEM")
        if mem_sz:
            mem_sz = int(mem_sz)
        else:
            mem_sz = long(psutil.virtual_memory().total)
        
        py_cpu_device = PyCPUDevice(0, mem_sz, VCU_BASELINE)
        cpu_arch = PyCPUArchitecture()
        self.py_registered_archs[cpu] = cpu_arch
        cpu_arch.add_device(py_cpu_device)
        self.registered_devices.append(py_cpu_device)
        cy_device = py_cpu_device.get_cy_device()
        self.cy_device_manager.register_device(cy_device)
        
References parla.cython.device_manager.PyDeviceManager.cy_device_manager, parla.cython.device_manager.PyDeviceManager.py_registered_archs, parla.cython.device_manager.PyCPUArchitecture, parla.cython.device_manager.PyCPUDevice, and parla.cython.device_manager.PyDeviceManager.registered_devices.
register_cupy_gpu_devices()
def parla.cython.device_manager.PyDeviceManager.register_cupy_gpu_devices (self)
This function adds cupy GPU devices.
Definition at line 163 of file device_manager.pyx.
    def register_cupy_gpu_devices(self):
        """
        This function adds cupy GPU devices.
        """
        # TODO(hc): Later, it will extend a GPU architecture type, like ones
        # from AMD.
        if cupy is not None:
            try:
                num_of_gpus = cupy.cuda.runtime.getDeviceCount()
            except cupy.cuda.runtime.CUDARuntimeError:
                num_of_gpus = 0
        else:
            num_of_gpus = 0
        if num_of_gpus > 0:
            gpu_arch = PyCUDAArchitecture()
            self.py_registered_archs[gpu] = gpu_arch
            for dev_id in range(num_of_gpus):
                gpu_dev = cupy.cuda.Device(dev_id)
                mem_info = gpu_dev.mem_info # tuple of free and total memory
                                            # in bytes.
                mem_sz = long(mem_info[1])
                py_cuda_device = PyCUDADevice(dev_id, mem_sz, VCU_BASELINE)
                #Add device to the architecture
                gpu_arch.add_device(py_cuda_device)
                #Add device to the device manager (list of devices)
                self.registered_devices.append(py_cuda_device)
                #Register device to the C++ runtime
                cy_device = py_cuda_device.get_cy_device()
                self.cy_device_manager.register_device(cy_device)
References parla.cython.device_manager.PyDeviceManager.cy_device_manager, parla.cython.device_manager.PyDeviceManager.py_registered_archs, parla.cython.device_manager.PyCUDAArchitecture, parla.cython.device_manager.PyCUDADevice, and parla.cython.device_manager.PyDeviceManager.registered_devices.
register_devices_to_cpp()
def parla.cython.device_manager.PyDeviceManager.register_devices_to_cpp (self)
Register devices to the both Python/C++ runtime.
Definition at line 234 of file device_manager.pyx.
    def register_devices_to_cpp(self):
        """
        Register devices to the both Python/C++ runtime.
        """
        current_idx = 0
        for py_arch in self.py_registered_archs:
            for py_device in py_arch.devices:
                cy_device = py_device.get_cy_device()
                self.cy_device_manager.register_device(cy_device)
                py_device.global_id = current_idx
                current_idx += 1
References parla.cython.device_manager.PyDeviceManager.cy_device_manager, and parla.cython.device_manager.PyDeviceManager.py_registered_archs.
unpack_placements()
def parla.cython.device_manager.PyDeviceManager.unpack_placements (self, placement_components, vcus, memory)
 Unpack a placement parameter and return a list of
    a pair of devices and requirements in a proper hierarchy structure.
    Placements (from @spawn) could be collections, for
    multi-device placements, a pair of architecture and
    resource requirement, or a pair of device and resource requirement.
Definition at line 371 of file device_manager.pyx.
    def unpack_placements(self, placement_components, vcus, memory):
        """ Unpack a placement parameter and return a list of
            a pair of devices and requirements in a proper hierarchy structure.
            Placements (from @spawn) could be collections, for
            multi-device placements, a pair of architecture and
            resource requirement, or a pair of device and resource requirement.
        """
        assert(isinstance(placement_components, List) or \
            isinstance(placement_components, Tuple))
        # Multi-device resource requirement or
        # a list of devices, architectures, or multi-device
        # requirements.
        unpacked_devices = []
        for c in placement_components:
            if isinstance(c, Tuple) and self.is_multidevice_placement(c):
                # Multi-device placement is specified
                # through a nested tuple of the placement API.
                # Which means that, each nested tuple in the
                # placement specifies a single placement for
                # a task. The placement API allows multiple tuples for
                # multi-device placements (e.g., placement=[(), (), ..]),
                # and the task mapper chooses one of those options
                # as the target requirement based on device states.
                # In this case, recursively call this function and
                # construct a list of member devices and their resource
                # requirements to distinguish them from other flat
                # resource requirements.
                unpacked_devices.append(self.unpack_placements(c, vcus, memory))
            else:
                unpacked_devices.append(self.construct_resource_requirements(c, vcus, memory))
        return unpacked_devices
References parla.cython.device_manager.PyDeviceManager.construct_resource_requirements(), parla.cython.device_manager.PyDeviceManager.is_multidevice_placement(), and parla.cython.device_manager.PyDeviceManager.unpack_placements().
Referenced by parla.cython.device_manager.PyDeviceManager.get_device_reqs_from_placement(), and parla.cython.device_manager.PyDeviceManager.unpack_placements().
Member Data Documentation
cy_device_manager
parla.cython.device_manager.PyDeviceManager.cy_device_manager
Definition at line 134 of file device_manager.pyx.
Referenced by parla.cython.device_manager.PyDeviceManager.get_cy_device_manager(), parla.cython.device_manager.PyDeviceManager.globalid_to_parrayid(), parla.cython.device_manager.PyDeviceManager.parrayid_to_globalid(), parla.cython.device_manager.PyDeviceManager.parse_config_and_register_devices(), parla.cython.device_manager.PyDeviceManager.print_registered_devices(), parla.cython.device_manager.PyDeviceManager.register_cpu_devices(), parla.cython.device_manager.PyDeviceManager.register_cupy_gpu_devices(), and parla.cython.device_manager.PyDeviceManager.register_devices_to_cpp().
num_real_gpus
parla.cython.device_manager.PyDeviceManager.num_real_gpus
Definition at line 141 of file device_manager.pyx.
Referenced by parla.cython.device_manager.PyDeviceManager.parse_config_and_register_devices().
py_registered_archs
parla.cython.device_manager.PyDeviceManager.py_registered_archs
Definition at line 136 of file device_manager.pyx.
Referenced by parla.cython.device_manager.PyDeviceManager.__dealloc__(), parla.cython.device_manager.PyDeviceManager.get_all_architectures(), parla.cython.device_manager.PyDeviceManager.get_architecture(), parla.cython.device_manager.PyDeviceManager.get_devices(), parla.cython.device_manager.PyDeviceManager.get_num_cpus(), parla.cython.device_manager.PyDeviceManager.get_num_gpus(), parla.cython.device_manager.PyDeviceManager.parse_config_and_register_devices(), parla.cython.device_manager.PyDeviceManager.print_registered_devices(), parla.cython.device_manager.PyDeviceManager.register_cpu_devices(), parla.cython.device_manager.PyDeviceManager.register_cupy_gpu_devices(), and parla.cython.device_manager.PyDeviceManager.register_devices_to_cpp().
registered_devices
parla.cython.device_manager.PyDeviceManager.registered_devices
Definition at line 137 of file device_manager.pyx.
Referenced by parla.cython.device_manager.PyDeviceManager.get_all_devices(), parla.cython.device_manager.PyDeviceManager.parse_config_and_register_devices(), parla.cython.device_manager.PyDeviceManager.register_cpu_devices(), and parla.cython.device_manager.PyDeviceManager.register_cupy_gpu_devices().
stream_pool
parla.cython.device_manager.PyDeviceManager.stream_pool
Definition at line 156 of file device_manager.pyx.
The documentation for this class was generated from the following file:
src/python/parla/cython/device_manager.pyx