parla.common.parray.core.PArray Class Reference
Public Member Functions
None __init__ (self, ndarray array, `PArray` parent=None, slices=None, str name=`NA`)
def name (self)
def cy_parray (self)
ndarray array (self)
def nbytes_at (self, int device_id)
def exists_on_device (self, int device_id)
None update (self, array)
None print_overview (self)
PArray|Any __getitem__ (self, SlicesType slices)
None __setitem__ (self, SlicesType slices, PArray|ndarray|Any value)
None evict_all (self)
bool evict (self, int device_id=None, bool keep_one_copy=True)
def __getattr__ (self, item)
def __lt__ (x, y)
def __le__ (x, y)
def __eq__ (x, y)
def __ne__ (x, y)
def __gt__ (x, y)
def __ge__ (x, y)
def __nonzero__ (self)
def __neg__ (self)
def __pos__ (self)
def __abs__ (self)
def __invert__ (self)
def __add__ (x, y)
def __sub__ (x, y)
def __mul__ (x, y)
def __matmul__ (x, y)
def __div__ (x, y)
def __truediv__ (x, y)
def __floordiv__ (x, y)
def __mod__ (x, y)
def __divmod__ (x, y)
def __pow__ (x, y, modulo)
def __lshift__ (x, y)
def __rshift__ (x, y)
def __and__ (x, y)
def __or__ (x, y)
def __xor__ (x, y)
def __iadd__ (self, other)
def __isub__ (self, other)
def __imul__ (self, other)
def __idiv__ (self, other)
def __itruediv__ (self, other)
def __ifloordiv__ (self, other)
def __imod__ (self, other)
def __ipow__ (self, other)
def __ilshift__ (self, other)
def __irshift__ (self, other)
def __iand__ (self, other)
def __ior__ (self, other)
def __ixor__ (self, other)
def __iter__ (self)
def __len__ (self)
def __int__ (self)
def __float__ (self)
def __complex__ (self)
def __oct__ (self)
def __hex__ (self)
def __bytes__ (self)
def __repr__ (self)
def __str__ (self)
def __format__ (self, format_spec)
def get_parray_parentid_from_cpp (self)
def get_num_active_tasks (self, global_dev_id)
Public Attributes
parent_ID
ID
nbytes
subarray_nbytes
parent
Private Member Functions
bool _on_gpu (self)
int _current_device_index (self)
None _coherence_read (self, int device_id=None, SlicesType slices=None)
None _coherence_write (self, int device_id=None, SlicesType slices=None)
None _process_operations (self, List[MemoryOperation] operations, SlicesType slices=None)
def _get_compute_device_for_crosspy (self, int index=0)
None _auto_move (self, int device_id=None, bool do_write=False)
bool _on_same_device (self, `PArray` other)
Static Private Member Functions
PyDevice|None _get_current_device ()
Private Attributes
_array
_coherence
_cyparray_state
_slices
_name
_coherence_cv
_slices_hash
_cy_parray
Detailed Description
Multi-dimensional array on a CPU or CUDA device.

This class is a wrapper around :class:`numpy.ndarray` and :class:`cupy.ndarray`,
It is used to support Parla sheduler optimization and automatic data movement.

Args:
    array: :class:`cupy.ndarray` or :class:`numpy.array` object

Note: some methods should be called within the current task context
Definition at line 30 of file core.py.
Constructor & Destructor Documentation
__init__()
None parla.common.parray.core.PArray.__init__ (self, ndarray array, `PArray` parent = None, slices = None, str name = `NA`)
Definition at line 49 of file core.py.
    def __init__(self, array: ndarray, parent: "PArray" = None, slices=None, name: str = "NA") -> None:
        if parent is not None: # create a view (a subarray) of a PArray
            # inherit parent's buffer and coherence states
            # so this PArray will becomes a 'view' of its parents
            self._array = parent._array
            self._coherence = parent._coherence
            self._cyparray_state = parent._cyparray_state
            # _slices is a list so subarray of subarray works
            self._slices = parent._slices.copy() # copy parent's slices list
            # add current slices to the end
            self._slices.append(slices)
            # self._name = parent._name + "::subarray::" + str(slices)
            self._name = parent._name + "::subarray::" + str(self._slices)
            # inherit parent's condition variables
            self._coherence_cv = parent._coherence_cv
            # identify the slices
            self._slices_hash = self._array.get_slices_hash(slices)
            # a unique ID for this subarray
            # which is the combine of parent id and slice hash
            self.parent_ID = parent.ID
            # use a prime number to avoid collision
            # modulo over uint64 to make it compatible with C++ end
            self.ID = (parent.ID * 31 + self._slices_hash) % UINT64_LIMIT
            self.nbytes = parent.nbytes # the bytes used by the complete array
            self.subarray_nbytes = array.nbytes # the bytes used by this subarray
            self.parent = parent
            # no need to register again since parent already did that
        else: # initialize a new PArray
            # init Cython PArrayState
            self._cyparray_state = CyPArrayState()
            # per device buffer of data
            self._array = MultiDeviceBuffer(num_gpu, self._cyparray_state)
            location = self._array.set_complete_array(array)
            # coherence protocol for managing data among multi device
            self._coherence = Coherence(
                location, num_gpu, self._cyparray_state)
            # no slices since it is a new array rather than a subarray
            self._slices = []
            # a condition variable to acquire when moving data on the device
            self._coherence_cv = {n: threading.Condition()
                                  for n in range(num_gpu)}
            self._coherence_cv[CPU_INDEX] = threading.Condition()
            # there is no slices
            self._slices_hash = None
            # use id() of buffer as unique ID
            self.parent_ID = id(self._array) # no parent
            self.ID = self.parent_ID
            self.nbytes = array.nbytes
            self.subarray_nbytes = self.nbytes # no subarray
            self.parent = self
            self._name = name
        # record the size in Cython PArray
        scheduler = get_scheduler()
        num_devices = len(scheduler.device_manager.get_all_devices())
        self._cy_parray = CyPArray(
            self, self.ID, self.parent_ID, self.parent, self._cyparray_state, num_devices)
        self._cy_parray.set_size(self.subarray_nbytes)
        target_dev_id = - \
            1 if isinstance(array, numpy.ndarray) else array.device.id
        if (target_dev_id >= 0):
            assert isinstance(array, cupy.ndarray)
        target_global_dev_id = scheduler.device_manager.parrayid_to_globalid(
            target_dev_id)
        scheduler.reserve_parray(self._cy_parray, target_global_dev_id)
Member Function Documentation
__abs__()
def parla.common.parray.core.PArray.__abs__ (self)
Definition at line 598 of file core.py.
    def __abs__(self):
        return PArray(self.array.__abs__())
References parla.common.parray.core.PArray.array().
__add__()
def parla.common.parray.core.PArray.__add__ (x, y)
Definition at line 606 of file core.py.
    def __add__(x, y):
        if isinstance(y, PArray):
            if not x._on_same_device(y):
                raise ValueError("Arrays are not on the same device")
            return PArray(x.array + y.array)
        else:
            return PArray(x.array + y)
__and__()
def parla.common.parray.core.PArray.__and__ (x, y)
Definition at line 702 of file core.py.
    def __and__(x, y):
        if isinstance(y, PArray):
            if not x._on_same_device(y):
                raise ValueError("Arrays are not on the same device")
            return PArray(x.array.__and__(y.array))
        else:
            return PArray(x.array.__and__(y))
__bytes__()
def parla.common.parray.core.PArray.__bytes__ (self)
Definition at line 869 of file core.py.
    def __bytes__(self):
        return bytes(self.array)
References parla.common.parray.core.PArray.array().
__complex__()
def parla.common.parray.core.PArray.__complex__ (self)
Definition at line 860 of file core.py.
    def __complex__(self):
        return complex(self.array)
References parla.common.parray.core.PArray.array().
__div__()
def parla.common.parray.core.PArray.__div__ (x, y)
Definition at line 638 of file core.py.
    def __div__(x, y):
        if isinstance(y, PArray):
            if not x._on_same_device(y):
                raise ValueError("Arrays are not on the same device")
            return PArray(x.array / y.array)
        else:
            return PArray(x.array / y)
__divmod__()
def parla.common.parray.core.PArray.__divmod__ (x, y)
Definition at line 670 of file core.py.
    def __divmod__(x, y):
        if isinstance(y, PArray):
            if not x._on_same_device(y):
                raise ValueError("Arrays are not on the same device")
            return PArray(x.array.__divmod__(y.array))
        else:
            return PArray(x.array.__divmod__(y))
__eq__()
def parla.common.parray.core.PArray.__eq__ (x, y)
Definition at line 553 of file core.py.
    def __eq__(x, y):
        if isinstance(y, PArray):
            if not x._on_same_device(y):
                raise ValueError("Arrays are not on the same device")
            return x.array.__eq__(y.array)
        else:
            return x.array.__eq__(y)
Referenced by parla.cython.tasks.TaskCollection.__ne__().
__float__()
def parla.common.parray.core.PArray.__float__ (self)
Definition at line 857 of file core.py.
    def __float__(self):
        return float(self.array)
References parla.common.parray.core.PArray.array().
__floordiv__()
def parla.common.parray.core.PArray.__floordiv__ (x, y)
Definition at line 654 of file core.py.
    def __floordiv__(x, y):
        if isinstance(y, PArray):
            if not x._on_same_device(y):
                raise ValueError("Arrays are not on the same device")
            return PArray(x.array.__floordiv__(y.array))
        else:
            return PArray(x.array.__floordiv__(y))
__format__()
def parla.common.parray.core.PArray.__format__ (self, format_spec)
Definition at line 880 of file core.py.
    def __format__(self, format_spec):
        return self._array.__format__(format_spec)
References parla.common.parray.core.PArray._array.
__ge__()
def parla.common.parray.core.PArray.__ge__ (x, y)
Definition at line 577 of file core.py.
    def __ge__(x, y):
        if isinstance(y, PArray):
            if not x._on_same_device(y):
                raise ValueError("Arrays are not on the same device")
            return x.array.__ge__(y.array)
        else:
            return x.array.__ge__(y)
__getattr__()
def parla.common.parray.core.PArray.__getattr__ (self, item)
A proxy method that redirect call to methods in :class:`numpy.ndarray` or :class:`cupy.ndarray`
Definition at line 529 of file core.py.
    def __getattr__(self, item):
        """
        A proxy method that redirect call to methods in :class:`numpy.ndarray` or :class:`cupy.ndarray`
        """
        return getattr(self.array, item)
References parla.common.parray.core.PArray.array().
__getitem__()
PArray | Any parla.common.parray.core.PArray.__getitem__ (self, SlicesType slices)
Definition at line 306 of file core.py.
    def __getitem__(self, slices: SlicesType) -> PArray | Any:
        if self._slices: # resolve saved slices first
            ret = self.array[slices]
        else:
            ret = self._array.get_by_global_slices(
                self._current_device_index, slices)
        # ndarray.__getitem__() may return a ndarray
        if ret is None:
            # when current device has no copy (could happen when a slice annotation is needed at @spawn)
            # get ret from owner, so it could have an estimation of the number of bytes used
            ret = self._array.get_by_global_slices(
                self._coherence.owner, slices)
            return PArray(ret, parent=self, slices=slices)
        elif isinstance(ret, numpy.ndarray):
            return PArray(ret, parent=self, slices=slices)
        elif isinstance(ret, cupy.ndarray):
            if ret.shape == ():
                return ret.item()
            else:
                return PArray(ret, parent=self, slices=slices)
        else:
            return ret
References parla.common.parray.core.PArray._array, parla.common.parray.core.PArray._coherence, parla.common.parray.core.PArray._current_device_index(), parla.common.parray.core.PArray._slices, and parla.common.parray.core.PArray.array().
__gt__()
def parla.common.parray.core.PArray.__gt__ (x, y)
Definition at line 569 of file core.py.
    def __gt__(x, y):
        if isinstance(y, PArray):
            if not x._on_same_device(y):
                raise ValueError("Arrays are not on the same device")
            return x.array.__gt__(y.array)
        else:
            return x.array.__gt__(y)
__hex__()
def parla.common.parray.core.PArray.__hex__ (self)
Definition at line 866 of file core.py.
    def __hex__(self):
        return hex(self.array)
References parla.common.parray.core.PArray.array().
__iadd__()
def parla.common.parray.core.PArray.__iadd__ (self, other)
Definition at line 727 of file core.py.
    def __iadd__(self, other):
        if isinstance(other, PArray):
            if not self._on_same_device(other):
                raise ValueError("Arrays are not on the same device")
            self.array.__iadd__(other.array)
        else:
            self.array.__iadd__(other)
        return self
References parla.common.parray.core.PArray._on_same_device(), and parla.common.parray.core.PArray.array().
__iand__()
def parla.common.parray.core.PArray.__iand__ (self, other)
Definition at line 817 of file core.py.
    def __iand__(self, other):
        if isinstance(other, PArray):
            if not self._on_same_device(other):
                raise ValueError("Arrays are not on the same device")
            self.array.__iand__(other.array)
        else:
            self.array.__iand__(other)
        return self
References parla.common.parray.core.PArray._on_same_device(), and parla.common.parray.core.PArray.array().
__idiv__()
def parla.common.parray.core.PArray.__idiv__ (self, other)
Definition at line 754 of file core.py.
    def __idiv__(self, other):
        if isinstance(other, PArray):
            if not self._on_same_device(other):
                raise ValueError("Arrays are not on the same device")
            self.array.__idiv__(other.array)
        else:
            self.array.__idiv__(other)
        return self
References parla.common.parray.core.PArray._on_same_device(), and parla.common.parray.core.PArray.array().
__ifloordiv__()
def parla.common.parray.core.PArray.__ifloordiv__ (self, other)
Definition at line 772 of file core.py.
    def __ifloordiv__(self, other):
        if isinstance(other, PArray):
            if not self._on_same_device(other):
                raise ValueError("Arrays are not on the same device")
            self.array.__ifloordiv__(other.array)
        else:
            self.array.__ifloordiv__(other)
        return self
References parla.common.parray.core.PArray._on_same_device(), and parla.common.parray.core.PArray.array().
__ilshift__()
def parla.common.parray.core.PArray.__ilshift__ (self, other)
Definition at line 799 of file core.py.
    def __ilshift__(self, other):
        if isinstance(other, PArray):
            if not self._on_same_device(other):
                raise ValueError("Arrays are not on the same device")
            self.array.__ilshift__(other.array)
        else:
            self.array.__ilshift__(other)
        return self
References parla.common.parray.core.PArray._on_same_device(), and parla.common.parray.core.PArray.array().
__imod__()
def parla.common.parray.core.PArray.__imod__ (self, other)
Definition at line 781 of file core.py.
    def __imod__(self, other):
        if isinstance(other, PArray):
            if not self._on_same_device(other):
                raise ValueError("Arrays are not on the same device")
            self.array.__imod__(other.array)
        else:
            self.array.__imod__(other)
        return self
References parla.common.parray.core.PArray._on_same_device(), and parla.common.parray.core.PArray.array().
__imul__()
def parla.common.parray.core.PArray.__imul__ (self, other)
Definition at line 745 of file core.py.
    def __imul__(self, other):
        if isinstance(other, PArray):
            if not self._on_same_device(other):
                raise ValueError("Arrays are not on the same device")
            self.array.__imul__(other.array)
        else:
            self.array.__imul__(other)
        return self
References parla.common.parray.core.PArray._on_same_device(), and parla.common.parray.core.PArray.array().
__int__()
def parla.common.parray.core.PArray.__int__ (self)
Definition at line 854 of file core.py.
    def __int__(self):
        return int(self.array)
References parla.common.parray.core.PArray.array().
__invert__()
def parla.common.parray.core.PArray.__invert__ (self)
Definition at line 601 of file core.py.
    def __invert__(self):
        return PArray(self.array.__invert__())
References parla.common.parray.core.PArray.array().
__ior__()
def parla.common.parray.core.PArray.__ior__ (self, other)
Definition at line 826 of file core.py.
    def __ior__(self, other):
        if isinstance(other, PArray):
            if not self._on_same_device(other):
                raise ValueError("Arrays are not on the same device")
            self.array.__ior__(other.array)
        else:
            self.array.__ior__(other)
        return self
References parla.common.parray.core.PArray._on_same_device(), and parla.common.parray.core.PArray.array().
__ipow__()
def parla.common.parray.core.PArray.__ipow__ (self, other)
Definition at line 790 of file core.py.
    def __ipow__(self, other):
        if isinstance(other, PArray):
            if not self._on_same_device(other):
                raise ValueError("Arrays are not on the same device")
            self.array.__ipow__(other.array)
        else:
            self.array.__ipow__(other)
        return self
References parla.common.parray.core.PArray._on_same_device(), and parla.common.parray.core.PArray.array().
__irshift__()
def parla.common.parray.core.PArray.__irshift__ (self, other)
Definition at line 808 of file core.py.
    def __irshift__(self, other):
        if isinstance(other, PArray):
            if not self._on_same_device(other):
                raise ValueError("Arrays are not on the same device")
            self.array.__irshift__(other.array)
        else:
            self.array.__irshift__(other)
        return self
References parla.common.parray.core.PArray._on_same_device(), and parla.common.parray.core.PArray.array().
__isub__()
def parla.common.parray.core.PArray.__isub__ (self, other)
Definition at line 736 of file core.py.
    def __isub__(self, other):
        if isinstance(other, PArray):
            if not self._on_same_device(other):
                raise ValueError("Arrays are not on the same device")
            self.array.__isub__(other.array)
        else:
            self.array.__isub__(other)
        return self
References parla.common.parray.core.PArray._on_same_device(), and parla.common.parray.core.PArray.array().
__iter__()
def parla.common.parray.core.PArray.__iter__ (self)
Definition at line 846 of file core.py.
    def __iter__(self):
        return self.array.__iter__()
References parla.common.parray.core.PArray.array().
__itruediv__()
def parla.common.parray.core.PArray.__itruediv__ (self, other)
Definition at line 763 of file core.py.
    def __itruediv__(self, other):
        if isinstance(other, PArray):
            if not self._on_same_device(other):
                raise ValueError("Arrays are not on the same device")
            self.array.__itruediv__(other.array)
        else:
            self.array.__itruediv__(other)
        return self
References parla.common.parray.core.PArray._on_same_device(), and parla.common.parray.core.PArray.array().
__ixor__()
def parla.common.parray.core.PArray.__ixor__ (self, other)
Definition at line 835 of file core.py.
    def __ixor__(self, other):
        if isinstance(other, PArray):
            if not self._on_same_device(other):
                raise ValueError("Arrays are not on the same device")
            self.array.__ixor__(other.array)
        else:
            self.array.__ixor__(other)
        return self
References parla.common.parray.core.PArray._on_same_device(), and parla.common.parray.core.PArray.array().
__le__()
def parla.common.parray.core.PArray.__le__ (x, y)
Definition at line 545 of file core.py.
    def __le__(x, y):
        if isinstance(y, PArray):
            if not x._on_same_device(y):
                raise ValueError("Arrays are not on the same device")
            return x.array.__le__(y.array)
        else:
            return x.array.__le__(y)
__len__()
def parla.common.parray.core.PArray.__len__ (self)
Definition at line 849 of file core.py.
    def __len__(self):
        return self.array.__len__()
References parla.common.parray.core.PArray.array().
__lshift__()
def parla.common.parray.core.PArray.__lshift__ (x, y)
Definition at line 686 of file core.py.
    def __lshift__(x, y):
        if isinstance(y, PArray):
            if not x._on_same_device(y):
                raise ValueError("Arrays are not on the same device")
            return PArray(x.array.__lshift__(y.array))
        else:
            return PArray(x.array.__lshift__(y))
__lt__()
def parla.common.parray.core.PArray.__lt__ (x, y)
Definition at line 537 of file core.py.
    def __lt__(x, y):
        if isinstance(y, PArray):
            if not x._on_same_device(y):
                raise ValueError("Arrays are not on the same device")
            return x.array.__lt__(y.array)
        else:
            return x.array.__lt__(y)
__matmul__()
def parla.common.parray.core.PArray.__matmul__ (x, y)
Definition at line 630 of file core.py.
    def __matmul__(x, y):
        if isinstance(y, PArray):
            if not x._on_same_device(y):
                raise ValueError("Arrays are not on the same device")
            return PArray(x.array @ y.array)
        else:
            return PArray(x.array @ y)
__mod__()
def parla.common.parray.core.PArray.__mod__ (x, y)
Definition at line 662 of file core.py.
    def __mod__(x, y):
        if isinstance(y, PArray):
            if not x._on_same_device(y):
                raise ValueError("Arrays are not on the same device")
            return PArray(x.array.__mod__(y.array))
        else:
            return PArray(x.array.__mod__(y))
__mul__()
def parla.common.parray.core.PArray.__mul__ (x, y)
Definition at line 622 of file core.py.
    def __mul__(x, y):
        if isinstance(y, PArray):
            if not x._on_same_device(y):
                raise ValueError("Arrays are not on the same device")
            return PArray(x.array * y.array)
        else:
            return PArray(x.array * y)
__ne__()
def parla.common.parray.core.PArray.__ne__ (x, y)
Definition at line 561 of file core.py.
    def __ne__(x, y):
        if isinstance(y, PArray):
            if not x._on_same_device(y):
                raise ValueError("Arrays are not on the same device")
            return x.array.__ne__(y.array)
        else:
            return x.array.__ne__(y)
__neg__()
def parla.common.parray.core.PArray.__neg__ (self)
Definition at line 592 of file core.py.
    def __neg__(self):
        return PArray(self.array.__neg__())
References parla.common.parray.core.PArray.array().
__nonzero__()
def parla.common.parray.core.PArray.__nonzero__ (self)
Definition at line 587 of file core.py.
    def __nonzero__(self):
        return PArray(self.array.__nonzero__())
References parla.common.parray.core.PArray.array().
__oct__()
def parla.common.parray.core.PArray.__oct__ (self)
Definition at line 863 of file core.py.
    def __oct__(self):
        return oct(self.array)
References parla.common.parray.core.PArray.array().
__or__()
def parla.common.parray.core.PArray.__or__ (x, y)
Definition at line 710 of file core.py.
    def __or__(x, y):
        if isinstance(y, PArray):
            if not x._on_same_device(y):
                raise ValueError("Arrays are not on the same device")
            return PArray(x.array.__or__(y.array))
        else:
            return PArray(x.array.__or__(y))
__pos__()
def parla.common.parray.core.PArray.__pos__ (self)
Definition at line 595 of file core.py.
    def __pos__(self):
        return PArray(self.array.__pos__())
References parla.common.parray.core.PArray.array().
__pow__()
def parla.common.parray.core.PArray.__pow__ (x, y, modulo)
Definition at line 678 of file core.py.
    def __pow__(x, y, modulo):
        if isinstance(y, PArray):
            if not x._on_same_device(y):
                raise ValueError("Arrays are not on the same device")
            return PArray(x.array.__pow__(y.array))
        else:
            return PArray(x.array.__pow__(y))
__repr__()
def parla.common.parray.core.PArray.__repr__ (self)
Definition at line 874 of file core.py.
    def __repr__(self):
        return repr(self._array)
References parla.common.parray.core.PArray._array.
Referenced by parla.common.globals.Storage.__str__(), parla.common.globals.LocalStack.__str__(), parla.cython.device.Stream.__str__(), parla.cython.device.CupyStream.__str__(), and parla.cython.tasks.TaskState.__str__().
__rshift__()
def parla.common.parray.core.PArray.__rshift__ (x, y)
Definition at line 694 of file core.py.
    def __rshift__(x, y):
        if isinstance(y, PArray):
            if not x._on_same_device(y):
                raise ValueError("Arrays are not on the same device")
            return PArray(x.array.__rshift__(y.array))
        else:
            return PArray(x.array.__rshift__(y))
__setitem__()
None parla.common.parray.core.PArray.__setitem__ (self, SlicesType slices, PArray | ndarray | Any value)
Acceptable Slices: Slice, Int, tuple of (Slice, Int, List of Int)
Example:
    A[0]  # int
    A[:]  # slice
    A[0,:,10]  # tuple of int slice int
    A[2:10:2, 0, [1, 3, 5]]  # tuple of slice int list of Int

Note: `:` equals to slice(None, None, None)
Note: `None` or tuple of `None` is not acceptable (even if `numpy.ndarray` accept `None`)
# TODO: support `None` and `ndarray` as slices
Definition at line 330 of file core.py.
    def __setitem__(self, slices: SlicesType, value: PArray | ndarray | Any) -> None:
        """
        Acceptable Slices: Slice, Int, tuple of (Slice, Int, List of Int)
        Example:
            A[0] # int
            A[:] # slice
            A[0,:,10] # tuple of int slice int
            A[2:10:2, 0, [1, 3, 5]] # tuple of slice int list of Int
        Note: `:` equals to slice(None, None, None)
        Note: `None` or tuple of `None` is not acceptable (even if `numpy.ndarray` accept `None`)
        # TODO: support `None` and `ndarray` as slices
        """
        if isinstance(value, PArray):
            value = value.array
        if self._slices: # resolve saved slices first
            self.array.__setitem__(slices, value)
        else:
            self._array.set_by_global_slices(
                self._current_device_index, slices, value)
References parla.common.parray.core.PArray._array, parla.common.parray.core.PArray._current_device_index(), parla.common.parray.core.PArray._slices, and parla.common.parray.core.PArray.array().
__str__()
def parla.common.parray.core.PArray.__str__ (self)
Definition at line 877 of file core.py.
    def __str__(self):
        return str(self._array)
References parla.common.parray.core.PArray._array.
__sub__()
def parla.common.parray.core.PArray.__sub__ (x, y)
Definition at line 614 of file core.py.
    def __sub__(x, y):
        if isinstance(y, PArray):
            if not x._on_same_device(y):
                raise ValueError("Arrays are not on the same device")
            return PArray(x.array - y.array)
        else:
            return PArray(x.array - y)
__truediv__()
def parla.common.parray.core.PArray.__truediv__ (x, y)
Definition at line 646 of file core.py.
    def __truediv__(x, y):
        if isinstance(y, PArray):
            if not x._on_same_device(y):
                raise ValueError("Arrays are not on the same device")
            return PArray(x.array / y.array)
        else:
            return PArray(x.array / y)
__xor__()
def parla.common.parray.core.PArray.__xor__ (x, y)
Definition at line 718 of file core.py.
    def __xor__(x, y):
        if isinstance(y, PArray):
            if not x._on_same_device(y):
                raise ValueError("Arrays are not on the same device")
            return PArray(x.array.__xor__(y.array))
        else:
            return PArray(x.array.__xor__(y))
_auto_move()
None parla.common.parray.core.PArray._auto_move (self, int device_id = None, bool do_write = False) [private]
 Automatically move data to current device.

Multiple copies on different devices will be made based on coherence protocol.

Args:
    device_id: current device id. CPU use CPU_INDEX as id
    do_write: True if want make the device MO in coherence protocol
        False if this is only for read only in current task

Note: should be called within the current task context.
Note: auto-move of subarray's subarray is not supported.
Definition at line 496 of file core.py.
    def _auto_move(self, device_id: int = None, do_write: bool = False) -> None:
        """ Automatically move data to current device.
        Multiple copies on different devices will be made based on coherence protocol.
        Args:
            device_id: current device id. CPU use CPU_INDEX as id
            do_write: True if want make the device MO in coherence protocol
                False if this is only for read only in current task
        Note: should be called within the current task context.
        Note: auto-move of subarray's subarray is not supported.
        """
        # this is the view of current array, only data within this range should be moved
        # currently, only use first slices, which means automove of subarray of subarray is not supported
        # TODO: support auto-move subarray of subarray
        slices = None if not self._slices else self._slices[0]
        if do_write:
            self._coherence_write(device_id, slices)
        else:
            self._coherence_read(device_id, slices)
References parla.common.parray.core.PArray._coherence_read(), parla.common.parray.core.PArray._coherence_write(), and parla.common.parray.core.PArray._slices.
_coherence_read()
None parla.common.parray.core.PArray._coherence_read (self, int device_id = None, SlicesType slices = None) [private]
 Tell the coherence protocol a read happened on a device.

And do data movement based on the operations given by protocol.

Args:
    device_id: if is this not None, data will be moved to this device,
            else move to current device
    slices: a slices of the subarray to be manipulated
            by default equals to None, which means the whole array is manipulated

Note: should be called within the current task context
Definition at line 388 of file core.py.
    def _coherence_read(self, device_id: int = None, slices: SlicesType = None) -> None:
        """ Tell the coherence protocol a read happened on a device.
        And do data movement based on the operations given by protocol.
        Args:
            device_id: if is this not None, data will be moved to this device,
                    else move to current device
            slices: a slices of the subarray to be manipulated
                    by default equals to None, which means the whole array is manipulated
        Note: should be called within the current task context
        """
        if device_id is None:
            device_id = self._current_device_index
        # update protocol and get operation
        with self._coherence._lock: # locks involve
            operations = self._coherence.read(device_id, self._slices_hash)
            self._process_operations(operations, slices)
References parla.common.parray.core.PArray._coherence, parla.common.parray.core.PArray._current_device_index(), parla.common.parray.core.PArray._process_operations(), and parla.common.parray.core.PArray._slices_hash.
Referenced by parla.common.parray.core.PArray._auto_move().
_coherence_write()
None parla.common.parray.core.PArray._coherence_write (self, int device_id = None, SlicesType slices = None) [private]
Tell the coherence protocol a write happened on a device.

And do data movement based on the operations given by protocol.

Args:
    device_id: if is this not None, data will be moved to this device,
            else move to current device
    slices: a slices of the subarray to be manipulated
            by default equals to None, which means the whole array is manipulated

Note: should be called within the current task context
Definition at line 409 of file core.py.
    def _coherence_write(self, device_id: int = None, slices: SlicesType = None) -> None:
        """Tell the coherence protocol a write happened on a device.
        And do data movement based on the operations given by protocol.
        Args:
            device_id: if is this not None, data will be moved to this device,
                    else move to current device
            slices: a slices of the subarray to be manipulated
                    by default equals to None, which means the whole array is manipulated
        Note: should be called within the current task context
        """
        if device_id is None:
            device_id = self._current_device_index
        # update protocol and get operation
        with self._coherence._lock: # locks involve
            operations = self._coherence.write(device_id, self._slices_hash)
            self._process_operations(operations, slices)
References parla.common.parray.core.PArray._coherence, parla.common.parray.core.PArray._current_device_index(), parla.common.parray.core.PArray._process_operations(), and parla.common.parray.core.PArray._slices_hash.
Referenced by parla.common.parray.core.PArray._auto_move().
_current_device_index()
int parla.common.parray.core.PArray._current_device_index (self) [private]
-1 if the current device is CPU.
Otherwise GPU ID.
If called outside the current task context, return data owner's device_id by default
Definition at line 176 of file core.py.
    def _current_device_index(self) -> int:
        """
        -1 if the current device is CPU.
        Otherwise GPU ID.
        If called outside the current task context, return data owner's device_id by default
        """
        device = PArray._get_current_device()
        if device is None: # not called inside current task
            return self._coherence.owner
        elif isinstance(device, PyCPUDevice):
            return CPU_INDEX
        else:
            # assume GPU here, won't check isinstance(device, PyCUDADevice)
            # to avoid import gpu context, which is slow to setup.
            return device.device.id # device.device should be a cupy.cuda.Device object
References parla.common.parray.core.PArray._coherence.
Referenced by parla.common.parray.core.PArray.__getitem__(), parla.common.parray.core.PArray.__setitem__(), parla.common.parray.core.PArray._coherence_read(), parla.common.parray.core.PArray._coherence_write(), parla.common.parray.core.PArray._on_gpu(), parla.common.parray.core.PArray._on_same_device(), parla.common.parray.core.PArray.array(), parla.common.parray.core.PArray.evict(), and parla.common.parray.core.PArray.update().
_get_compute_device_for_crosspy()
def parla.common.parray.core.PArray._get_compute_device_for_crosspy (self, int index = 0) [private]
Get the active device context for crosspy.
Returns None if not called from within a task. 
Definition at line 486 of file core.py.
    def _get_compute_device_for_crosspy(self, index: int = 0):
        """
        Get the active device context for crosspy.
        Returns None if not called from within a task.
        """
        if has_environment():
            current_device = get_current_devices()[index]
            return current_device
        return None
References parla.common.globals.get_current_devices(), and parla.common.globals.has_environment().
_get_current_device()
PyDevice | None parla.common.parray.core.PArray._get_current_device () [static], [private]
Get current device from task environment.

Return None if it is not called within the current task context

Note: should not be called within multi-device task since that is ambigous
Definition at line 474 of file core.py.
    def _get_current_device() -> PyDevice | None:
        """
        Get current device from task environment.
        Return None if it is not called within the current task context
        Note: should not be called within multi-device task since that is ambigous
        """
        if has_environment():
            return get_current_devices()[0].get_parla_device()
        return None
References parla.common.globals.get_current_devices(), and parla.common.globals.has_environment().
_on_gpu()
bool parla.common.parray.core.PArray._on_gpu (self) [private]
True if the array is on GPU.
Note: should be called within the current task context
Definition at line 168 of file core.py.
    def _on_gpu(self) -> bool:
        """
        True if the array is on GPU.
        Note: should be called within the current task context
        """
        return self._current_device_index != CPU_INDEX
References parla.common.parray.core.PArray._current_device_index().
_on_same_device()
bool parla.common.parray.core.PArray._on_same_device (self, `PArray` other) [private]
Return True if the two PArrays are in the same device.
Note: other has to be a PArray object.
Definition at line 519 of file core.py.
    def _on_same_device(self, other: "PArray") -> bool:
        """
        Return True if the two PArrays are in the same device.
        Note: other has to be a PArray object.
        """
        this_device = self._current_device_index
        return this_device in other._array
References parla.common.parray.core.PArray._current_device_index().
Referenced by parla.common.parray.core.PArray.__iadd__(), parla.common.parray.core.PArray.__iand__(), parla.common.parray.core.PArray.__idiv__(), parla.common.parray.core.PArray.__ifloordiv__(), parla.common.parray.core.PArray.__ilshift__(), parla.common.parray.core.PArray.__imod__(), parla.common.parray.core.PArray.__imul__(), parla.common.parray.core.PArray.__ior__(), parla.common.parray.core.PArray.__ipow__(), parla.common.parray.core.PArray.__irshift__(), parla.common.parray.core.PArray.__isub__(), parla.common.parray.core.PArray.__itruediv__(), and parla.common.parray.core.PArray.__ixor__().
_process_operations()
None parla.common.parray.core.PArray._process_operations (self, List[MemoryOperation] operations, SlicesType slices = None) [private]
Process the given memory operations.
Data will be moved, and protocol states is kept unchanged.
Definition at line 432 of file core.py.
    def _process_operations(self, operations: List[MemoryOperation], slices: SlicesType = None) -> None:
        """
        Process the given memory operations.
        Data will be moved, and protocol states is kept unchanged.
        """
        for op in operations:
            if op.inst == MemoryOperation.NOOP:
                pass # do nothing
            elif op.inst == MemoryOperation.LOAD:
                if MemoryOperation.LOAD_SUBARRAY in op.flag:
                    # build slices mapping first
                    self._array.set_slices_mapping(op.dst, slices)
                # check flag to see if dst is current device
                dst_is_current_device = op.flag != MemoryOperation.SWITCH_DEVICE_FLAG
                # copy data
                self._array.copy_data_between_device(
                    op.dst, op.src, dst_is_current_device)
                # sync stream before set it as ready, so asyc call is ensured to be done
                if num_gpu > 0:
                    cupy.cuda.stream.get_current_stream().synchronize()
            elif op.inst == MemoryOperation.EVICT:
                scheduler = get_scheduler()
                src_global_dev_id = scheduler.device_manager.parrayid_to_globalid(
                    op.src)
                if self._cy_parray.get_num_active_tasks(src_global_dev_id) == 0:
                    # If none of visible tasks will refer this PArray, release
                    # this PArray instance of the source device from the PArray tracker.
                    scheduler.release_parray(
                        self._cy_parray, src_global_dev_id)
                # decrement the reference counter, relying on GC to free the memor
                self._array.clear(op.src)
            elif op.inst == MemoryOperation.ERROR:
                raise RuntimeError(
                    "PArray gets an error from coherence protocol")
            else:
                raise RuntimeError(f"PArray gets invalid memory operation from coherence protocol, "
                                   f"detail: opcode {op.inst}, dst {op.dst}, src {op.src}")
References parla.common.parray.core.PArray._array, parla.common.parray.core.PArray._cy_parray, parla.common.parray.core.PArray.get_num_active_tasks(), and parla.common.globals.get_scheduler().
Referenced by parla.common.parray.core.PArray._coherence_read(), parla.common.parray.core.PArray._coherence_write(), and parla.common.parray.core.PArray.evict().
array()
ndarray parla.common.parray.core.PArray.array (self)
The reference to cupy/numpy array on current device.
Note: should be called within the current task context
Note: should call A[valid_slices].array instead of A.array,
    when in a tasks which only subarray is auto-moved.
    `valid_slices` is a slices within the auto-moved subarray.
Definition at line 144 of file core.py.
    def array(self) -> ndarray:
        """
        The reference to cupy/numpy array on current device.
        Note: should be called within the current task context
        Note: should call A[valid_slices].array instead of A.array,
            when in a tasks which only subarray is auto-moved.
            `valid_slices` is a slices within the auto-moved subarray.
        """
        if self._slices: # so this is a sub-parray object
            # index into origin array by saved slices
            ret = self._array.get_by_global_slices(
                self._current_device_index, self._slices[0])
            for s in self._slices[1:]:
                ret = ret[s]
            return ret
        else: # this is a complete copy
            ret = self._array.get(self._current_device_index)
            if isinstance(ret, list): # get a subarray instead
                raise IndexError(
                    "Current device doesn't have a complete copy of this array")
            return ret
References parla.common.parray.core.PArray._array, parla.common.parray.core.PArray._current_device_index(), and parla.common.parray.core.PArray._slices.
Referenced by parla.common.parray.core.PArray.__abs__(), parla.common.parray.core.PArray.__bytes__(), parla.common.parray.core.PArray.__complex__(), parla.common.parray.core.PArray.__float__(), parla.common.parray.core.PArray.__getattr__(), parla.common.parray.core.PArray.__getitem__(), parla.common.parray.core.PArray.__hex__(), parla.common.parray.core.PArray.__iadd__(), parla.common.parray.core.PArray.__iand__(), parla.common.parray.core.PArray.__idiv__(), parla.common.parray.core.PArray.__ifloordiv__(), parla.common.parray.core.PArray.__ilshift__(), parla.common.parray.core.PArray.__imod__(), parla.common.parray.core.PArray.__imul__(), parla.common.parray.core.PArray.__int__(), parla.common.parray.core.PArray.__invert__(), parla.common.parray.core.PArray.__ior__(), parla.common.parray.core.PArray.__ipow__(), parla.common.parray.core.PArray.__irshift__(), parla.common.parray.core.PArray.__isub__(), parla.common.parray.core.PArray.__iter__(), parla.common.parray.core.PArray.__itruediv__(), parla.common.parray.core.PArray.__ixor__(), parla.common.parray.core.PArray.__len__(), parla.common.parray.core.PArray.__neg__(), parla.common.parray.core.PArray.__nonzero__(), parla.common.parray.core.PArray.__oct__(), parla.common.parray.core.PArray.__pos__(), and parla.common.parray.core.PArray.__setitem__().
cy_parray()
def parla.common.parray.core.PArray.cy_parray (self)
Definition at line 140 of file core.py.
    def cy_parray(self):
        return self._cy_parray
References parla.common.parray.core.PArray._cy_parray.
evict()
bool parla.common.parray.core.PArray.evict (self, int device_id = None, bool keep_one_copy = True)
Evict a device's copy and update coherence states.

Args:
    device_id: if is this not None, data will be moved to this device,
            else move to current device
    keep_one_copy: if it is True and this is the last copy, 
            write it back to CPU before evict.
Return:
    true if the copy is evicted successfully
    false if the eviction cannot be performed since it has last copy
        and `keep_one_copy` is false
Definition at line 361 of file core.py.
    def evict(self, device_id: int = None, keep_one_copy: bool = True) -> bool:
        """
        Evict a device's copy and update coherence states.
        Args:
            device_id: if is this not None, data will be moved to this device,
                    else move to current device
            keep_one_copy: if it is True and this is the last copy,
                    write it back to CPU before evict.
        Return:
            true if the copy is evicted successfully
            false if the eviction cannot be performed since it has last copy
                and `keep_one_copy` is false
        """
        if device_id is None:
            device_id = self._current_device_index
        with self._coherence_cv[device_id]:
            operations = self._coherence.evict(device_id, keep_one_copy)
            if operations[0].inst == MemoryOperation.ERROR:
                return False # cannot perform the eviction
            self._process_operations(operations)
    
        return True
References parla.common.parray.core.PArray._coherence, parla.common.parray.core.PArray._coherence_cv, parla.common.parray.core.PArray._current_device_index(), and parla.common.parray.core.PArray._process_operations().
evict_all()
None parla.common.parray.core.PArray.evict_all (self)
Evict all copies from buffer, and clean all related fields

Note: this object should not be accessed anymore after called this method
Definition at line 352 of file core.py.
    def evict_all(self) -> None:
        """
        Evict all copies from buffer, and clean all related fields
        Note: this object should not be accessed anymore after called this method
        """
        self._array = None
        self._coherence = None
References parla.common.parray.core.PArray._array, and parla.common.parray.core.PArray._coherence.
exists_on_device()
def parla.common.parray.core.PArray.exists_on_device (self, int device_id)
Definition at line 212 of file core.py.
    def exists_on_device(self, device_id: int):
        return (self._array._buffer[device_id] is not None)
References parla.common.parray.core.PArray._array.
get_num_active_tasks()
def parla.common.parray.core.PArray.get_num_active_tasks (self, global_dev_id)
Definition at line 888 of file core.py.
    def get_num_active_tasks(self, global_dev_id):
        return self._cy_parray.get_num_active_tasks(global_dev_id)
References parla.common.parray.core.PArray._cy_parray.
Referenced by parla.common.parray.core.PArray._process_operations().
get_parray_parentid_from_cpp()
def parla.common.parray.core.PArray.get_parray_parentid_from_cpp (self)
Definition at line 885 of file core.py.
    def get_parray_parentid_from_cpp(self):
        return self._cy_parray.get_parray_parentid()
References parla.common.parray.core.PArray._cy_parray.
name()
def parla.common.parray.core.PArray.name (self)
Definition at line 134 of file core.py.
    def name(self):
        if self._name is None:
            return "PArray::"+str(self.ID)
        return self._name
References parla.common.containers.TaskSpace._name, parla.common.parray.core.PArray._name, parla.cython.device.PyArchitecture._name, parla.cython.device.ImportableArchitecture._name, parla.cython.tasks.TaskCollection._name, parla.cython.tasks.TaskList._name, parla.cython.tasks.BackendTaskList._name, parla.cython.tasks.TaskSpace._name, and parla.common.parray.core.PArray.ID.
Referenced by parla.cython.tasks.Task.__hash__(), parla.cython.tasks.Task.get_name(), parla.cython.tasks.Task.unpack_name(), and parla.cython.tasks.Task.update_name().
nbytes_at()
def parla.common.parray.core.PArray.nbytes_at (self, int device_id)
 An estimate of bytes used in `device_id` after data is moved there.
It is neither lower bound nor upper bound.
Definition at line 194 of file core.py.
    def nbytes_at(self, device_id: int):
        """ An estimate of bytes used in `device_id` after data is moved there.
        It is neither lower bound nor upper bound.
        """
        if self._slices:
            # there are subarrays no this device
            if isinstance(self._coherence._local_states[device_id], dict):
                # this subarray is already there
                if self._slices_hash in self._coherence._local_states[device_id].keys():
                    return self._array.nbytes_at(device_id)
                else: # the subarray will be moved to there
                    # add the incoming subarray size
                    return self._array.nbytes_at(device_id) + self.subarray_nbytes
            else: # there is a complete copy on this device, no need to prepare subarray
                return self.nbytes
        else:
            return self.nbytes
References parla.common.parray.core.PArray._array, parla.common.parray.core.PArray._coherence, parla.common.parray.core.PArray._slices, parla.common.parray.core.PArray._slices_hash, parla.cython.tasks.keys, parla.common.parray.core.PArray.nbytes, and parla.common.parray.core.PArray.subarray_nbytes.
print_overview()
None parla.common.parray.core.PArray.print_overview (self)
Print global overview of current PArray for debugging
Definition at line 272 of file core.py.
    def print_overview(self) -> None:
        """
        Print global overview of current PArray for debugging
        """
        state_str_map = {0: "INVALID",
                         1: "SHARED",
                         2: "MODIFIED"}
        print(f"---Overview of PArray\n"
              f"ID: {self.ID}, "
              f"Name: {self._name}, "
              f"Parent_ID: {self.parent_ID if self.ID != self.parent_ID else None}, "
              f"Slice: {self._slices[0] if self.ID != self.parent_ID else None}, "
              f"Bytes: {self.subarray_nbytes}, "
              f"Owner: {'GPU ' + str(self._coherence.owner) if self._coherence.owner != CPU_INDEX else 'CPU'}")
        for device_id, state in self._coherence._local_states.items():
            if device_id == CPU_INDEX:
                device_name = "CPU"
            else:
                device_name = f"GPU {device_id}"
            print(f"At {device_name}: ", end="")
            if isinstance(state, dict):
                print(
                    f"state: {[state_str_map[s] for s in list(state.values())]}, including sliced copy: # states of slices is unordered wrt the below slices")
                for slice, slice_id in zip(self._array._indices_map[device_id], range(len(self._array._indices_map[device_id]))):
                    print(
                        f"\tslice {slice_id} - indices: {slice}, bytes: {self._array._buffer[device_id][slice_id].nbytes}")
            else:
                print(f"state: {state_str_map[state]}")
        print("---End of Overview")
References parla.common.parray.core.PArray._array, and parla.common.parray.core.PArray._coherence.
update()
None parla.common.parray.core.PArray.update (self, array)
 Update the copy on current device.
Previous copy on other device are lost.
This will replace the internal buffer and coherence object completly.

Args:
    array: :class:`cupy.ndarray` or :class:`numpy.array` object

Note: should be called within the current task context
Note: data should be put in OUT/INOUT fields of spawn
Note: should not call this over an sliced array
Definition at line 215 of file core.py.
    def update(self, array) -> None:
        """ Update the copy on current device.
        Previous copy on other device are lost.
        This will replace the internal buffer and coherence object completly.
        Args:
            array: :class:`cupy.ndarray` or :class:`numpy.array` object
        Note: should be called within the current task context
        Note: data should be put in OUT/INOUT fields of spawn
        Note: should not call this over an sliced array
        """
        this_device = self._current_device_index
        # clean up data
        self._array._buffer = {n: None for n in range(num_gpu)}
        self._array._buffer[CPU_INDEX] = None
        # update it to cpp side
        for n in range(num_gpu):
            self._cyparray_state.set_exist_on_device(n, False)
        self._cyparray_state.set_exist_on_device(CPU_INDEX, False)
        # copy new data to buffer
        if isinstance(array, numpy.ndarray):
            if this_device != CPU_INDEX: # CPU to GPU
                self._array.set(this_device, cupy.asarray(array))
            else: # data already in CPU
                self._array.set(this_device, array)
        else:
            if this_device == CPU_INDEX: # GPU to CPU
                self._array.set(this_device, cupy.asnumpy(array))
            else: # GPU to GPU
                if int(array.device) == this_device: # data already in this device
                    self._array.set(this_device, array)
                else: # GPU to GPU
                    dst_data = cupy.empty_like(array)
                    dst_data.data.copy_from_device_async(
                        array.data, array.nbytes)
                    self._array.set(this_device, dst_data)
        # update size
        self.nbytes = array.nbytes
        self.subarray_nbytes = self.nbytes
        self._cy_parray.set_size(self.nbytes)
        self._slices = []
        # reset coherence
        self._coherence.reset(this_device)
        # update shape
        self._array.shape = array.shape
        if num_gpu > 0:
            cupy.cuda.stream.get_current_stream().synchronize()
References parla.common.parray.core.PArray._array, parla.common.parray.core.PArray._coherence, parla.common.parray.core.PArray._current_device_index(), parla.common.parray.core.PArray._cy_parray, parla.common.parray.coherence.Coherence._cyparray_state, parla.common.parray.core.PArray._cyparray_state, parla.common.parray.memory.MultiDeviceBuffer._cyparray_state, parla.common.parray.core.PArray._slices, parla.common.parray.core.PArray.nbytes, and parla.common.parray.core.PArray.subarray_nbytes.
Member Data Documentation
_array
parla.common.parray.core.PArray._array [private]
Definition at line 53 of file core.py.
Referenced by parla.common.parray.core.PArray.__format__(), parla.common.parray.core.PArray.__getitem__(), parla.common.parray.core.PArray.__repr__(), parla.common.parray.core.PArray.__setitem__(), parla.common.parray.core.PArray.__str__(), parla.common.parray.core.PArray._process_operations(), parla.common.parray.core.PArray.array(), parla.common.parray.core.PArray.evict_all(), parla.common.parray.core.PArray.exists_on_device(), parla.common.parray.core.PArray.nbytes_at(), parla.common.parray.core.PArray.print_overview(), and parla.common.parray.core.PArray.update().
_coherence
parla.common.parray.core.PArray._coherence [private]
Definition at line 54 of file core.py.
Referenced by parla.common.parray.core.PArray.__getitem__(), parla.common.parray.core.PArray._coherence_read(), parla.common.parray.core.PArray._coherence_write(), parla.common.parray.core.PArray._current_device_index(), parla.common.parray.core.PArray.evict(), parla.common.parray.core.PArray.evict_all(), parla.common.parray.core.PArray.nbytes_at(), parla.common.parray.core.PArray.print_overview(), and parla.common.parray.core.PArray.update().
_coherence_cv
parla.common.parray.core.PArray._coherence_cv [private]
Definition at line 66 of file core.py.
Referenced by parla.common.parray.core.PArray.evict().
_cy_parray
parla.common.parray.core.PArray._cy_parray [private]
Definition at line 120 of file core.py.
Referenced by parla.common.parray.core.PArray._process_operations(), parla.common.parray.core.PArray.cy_parray(), parla.common.parray.core.PArray.get_num_active_tasks(), parla.common.parray.core.PArray.get_parray_parentid_from_cpp(), and parla.common.parray.core.PArray.update().
_cyparray_state
parla.common.parray.core.PArray._cyparray_state [private]
Definition at line 55 of file core.py.
Referenced by parla.common.parray.coherence.Coherence._write_back_to(), parla.common.parray.memory.MultiDeviceBuffer.clear(), parla.common.parray.memory.MultiDeviceBuffer.copy_data_between_device(), parla.common.parray.coherence.Coherence.read(), parla.common.parray.coherence.Coherence.reset(), parla.common.parray.memory.MultiDeviceBuffer.set(), parla.common.parray.memory.MultiDeviceBuffer.set_complete_array(), parla.common.parray.core.PArray.update(), and parla.common.parray.coherence.Coherence.write().
_name
parla.common.parray.core.PArray._name [private]
Definition at line 63 of file core.py.
Referenced by parla.common.containers.TaskSpace.__dealloc__(), parla.common.parray.core.PArray.name(), parla.cython.device.PyArchitecture.name(), parla.cython.device.ImportableArchitecture.name(), parla.cython.tasks.TaskSpace.name(), and parla.cython.tasks.TaskSpace.view().
_slices
parla.common.parray.core.PArray._slices [private]
Definition at line 58 of file core.py.
Referenced by parla.common.parray.core.PArray.__getitem__(), parla.common.parray.core.PArray.__setitem__(), parla.common.parray.core.PArray._auto_move(), parla.common.parray.core.PArray.array(), parla.common.parray.core.PArray.nbytes_at(), and parla.common.parray.core.PArray.update().
_slices_hash
parla.common.parray.core.PArray._slices_hash [private]
Definition at line 69 of file core.py.
Referenced by parla.common.parray.core.PArray._coherence_read(), parla.common.parray.core.PArray._coherence_write(), and parla.common.parray.core.PArray.nbytes_at().
ID
parla.common.parray.core.PArray.ID
Definition at line 76 of file core.py.
Referenced by parla.common.parray.core.PArray.name().
nbytes
parla.common.parray.core.PArray.nbytes
Definition at line 78 of file core.py.
Referenced by parla.common.parray.core.PArray.nbytes_at(), and parla.common.parray.core.PArray.update().
parent
parla.common.parray.core.PArray.parent
Definition at line 80 of file core.py.
parent_ID
parla.common.parray.core.PArray.parent_ID
Definition at line 73 of file core.py.
subarray_nbytes
parla.common.parray.core.PArray.subarray_nbytes
Definition at line 79 of file core.py.
Referenced by parla.common.parray.core.PArray.nbytes_at(), and parla.common.parray.core.PArray.update().
The documentation for this class was generated from the following file:
src/python/parla/common/parray/core.py