RuntimeReserver Class Reference
RuntimeReserver phase of the scheduler.
#include <phases.hpp>
Public Member Functions
RuntimeReserver (InnerScheduler *scheduler, DeviceManager *devices)
void enqueue (InnerTask *task)
Enqueue a task to the phase.
void enqueue (std::vector< InnerTask * > &tasks)
Enqueue a vector of tasks to the phase.
void run (SchedulerPhase *next_phase)
Run the phase. Check tasks in the enqueued buffer, check phase condition, and move tasks to the next phase.
size_t get_count ()
Get the number of tasks enqueued (and waiting) in the phase.
size_t get_compute_count ()
size_t get_movement_count ()
const std::string & get_name () const
const RuntimeReserverStatus & get_status () const
const void print_status () const
Protected Member Functions
bool check_resources (InnerTask *task)
Check if the NonPersistentResources are available for a ComputeTask.
bool check_data_resources (InnerTask *task)
Check the resources for a data movement task (number of free copy engines).
void reserve_resources (InnerTask *task)
Reserve (decrease) the NonPersistentResources for a ComputeTask.
void reserve_data_resources (InnerTask *task)
Reserve (decrease) the resources for a data movement task (number of copy engines).
Protected Attributes
std::shared_ptr< PhaseManager< ResourceCategory::NonPersistent > > runnable_tasks
The multidevice queues for compute tasks.
std::shared_ptr< PhaseManager< ResourceCategory::Movement > > movement_tasks
The multidevice queues for data movement tasks.
RuntimeReserverStatus status {name}
The status of the phase. Used for debugging and tracing.
std::vector< InnerTask * > launchable_tasks_buffer
The buffer of tasks enqueued (and waiting) in the phase.
Static Protected Attributes
static const std::string name {`Runtime Reserver`}
The name of the phase. Used for debugging and tracing.
Detailed Description
RuntimeReserver phase of the scheduler.
RuntimeReserver reserves all 'non-persistent resources. Here all 'non-persistent resources that have a lifetime equal to the task body are reserved and are not directly shared between tasks. At the moment this is only the VCUS/Threads a task uses. This phase submits the task to the launcher.
Definition at line 291 of file phases.hpp.
Constructor & Destructor Documentation
RuntimeReserver()
RuntimeReserver::RuntimeReserver (InnerScheduler * scheduler, DeviceManager * devices) [inline]
Definition at line 293 of file phases.hpp.
      : SchedulerPhase(scheduler, devices) {
    // std::cout << "RuntimeReserver created" << std::endl;
    // FIXME: This leaks memory. Need to add deconstructor.
    this->runnable_tasks =
        std::make_shared<PhaseManager<ResourceCategory::NonPersistent>>(
            devices);
    this->movement_tasks =
        std::make_shared<PhaseManager<ResourceCategory::Movement>>(devices);
  }
References SchedulerPhase::SchedulerPhase().
Referenced by InnerScheduler::InnerScheduler().
Member Function Documentation
check_data_resources()
bool RuntimeReserver::check_data_resources (InnerTask * task) [protected]
Check the resources for a data movement task (number of free copy engines).
Definition at line 351 of file phases.cpp.
                                                          {
  bool status = true;
  for (Device *device : task->assigned_devices) {
    ResourcePool_t &task_pool =
        task->device_constraints[device->get_global_id()];
    ResourcePool_t &device_pool = device->get_reserved_pool();
    status = device_pool.check_greater<ResourceCategory::Movement>(task_pool);
    if (!status) {
      break;
    }
  }
  return status;
}
check_resources()
bool RuntimeReserver::check_resources (InnerTask * task) [protected]
Check if the NonPersistentResources are available for a ComputeTask.
Definition at line 334 of file phases.cpp.
                                                     {
  bool status = true;
  for (Device *device : task->assigned_devices) {
    ResourcePool_t &task_pool =
        task->device_constraints[device->get_global_id()];
    ResourcePool_t &device_pool = device->get_reserved_pool();
    status =
        device_pool.check_greater<ResourceCategory::NonPersistent>(task_pool);
    if (!status) {
      break;
    }
  }
  return status;
}
enqueue() [1/2]
void RuntimeReserver::enqueue (InnerTask * task) [virtual]
Enqueue a task to the phase.
Implements SchedulerPhase.
Definition at line 302 of file phases.cpp.
                                             {
  bool is_data_task = task->is_data_task();
  if (!is_data_task) {
    // std::cout << "RuntimeReserver::enqueue: compute task" << std::endl;
    this->runnable_tasks->enqueue(task);
  } else {
    // std::cout << "RuntimeReserver::enqueue: data task" << std::endl;
    this->movement_tasks->enqueue(task);
  }
}
Referenced by InnerScheduler::enqueue_task().
enqueue() [2/2]
void RuntimeReserver::enqueue (std::vector< InnerTask * > & tasks) [virtual]
Enqueue a vector of tasks to the phase.
Implements SchedulerPhase.
Definition at line 313 of file phases.cpp.
                                                           {
  for (InnerTask *task : tasks) {
    this->enqueue(task);
  }
}
get_compute_count()
size_t RuntimeReserver::get_compute_count ()
Definition at line 319 of file phases.cpp.
                                          {
  size_t count = this->runnable_tasks->size();
  return count;
}
get_count()
size_t RuntimeReserver::get_count () [virtual]
Get the number of tasks enqueued (and waiting) in the phase.
Implements SchedulerPhase.
Definition at line 329 of file phases.cpp.
                                  {
  size_t count = this->get_compute_count() + this->get_movement_count();
  return count;
}
Referenced by InnerScheduler::get_num_ready_tasks().
get_movement_count()
size_t RuntimeReserver::get_movement_count ()
Definition at line 324 of file phases.cpp.
                                           {
  size_t count = this->movement_tasks->size();
  return count;
}
get_name()
const std::string& RuntimeReserver::get_name () const [inline]
Definition at line 311 of file phases.hpp.
{ return this->name; }
Referenced by parla.cython.device_manager.PrintableFrozenSet::__repr__().
get_status()
const RuntimeReserverStatus& RuntimeReserver::get_status () const [inline]
Definition at line 312 of file phases.hpp.
{ return this->status; }
print_status()
const void RuntimeReserver::print_status () const [inline]
Definition at line 313 of file phases.hpp.
{ this->status.print(); }
reserve_data_resources()
void RuntimeReserver::reserve_data_resources (InnerTask * task) [protected]
Reserve (decrease) the resources for a data movement task (number of copy engines).
Definition at line 377 of file phases.cpp.
                                                            {
  // TODO(wlr): Add runtime error check if resource failure
  for (Device *device : task->assigned_devices) {
    ResourcePool_t &task_pool =
        task->device_constraints[device->get_global_id()];
    ResourcePool_t &device_pool = device->get_reserved_pool();
    device_pool.decrease<ResourceCategory::Movement>(task_pool);
  }
}
reserve_resources()
void RuntimeReserver::reserve_resources (InnerTask * task) [protected]
Reserve (decrease) the NonPersistentResources for a ComputeTask.
Definition at line 367 of file phases.cpp.
                                                       {
  // TODO(wlr): Add runtime error check if resource failure
  for (Device *device : task->assigned_devices) {
    ResourcePool_t &task_pool =
        task->device_constraints[device->get_global_id()];
    ResourcePool_t &device_pool = device->get_reserved_pool();
    device_pool.decrease<ResourceCategory::NonPersistent>(task_pool);
  }
}
run()
void RuntimeReserver::run (SchedulerPhase * next_phase) [virtual]
Run the phase. Check tasks in the enqueued buffer, check phase condition, and move tasks to the next phase.
Parameters
next_phase The next phase to move tasks to.
Implements SchedulerPhase.
Definition at line 387 of file phases.cpp.
                                                    {
  NVTX_RANGE("RuntimeReserver::run", NVTX_COLOR_LIGHT_GREEN)
  // std::cout << "RuntimeReserver::run" << std::endl;
  Launcher *launcher = dynamic_cast<Launcher *>(next_phase);
  // Only one thread can reserve runtime resources at a time.
  // Useful for a multi-threaded scheduler. Not needed for a single-threaded.
  // std::unique_lock<std::mutex> lock(this->mtx);
  // Try to launch as many compute tasks as possible
  int fail_count = 0;
  int max_fail = this->runnable_tasks->get_num_devices() * 2;
  bool has_task = true;
  int num_tasks = 0;
  while (has_task && (fail_count < max_fail)) {
    num_tasks = this->get_compute_count();
    has_task = num_tasks > 0;
    if (has_task) {
      InnerTask *task = this->runnable_tasks->front();
      bool has_resources = check_resources(task);
      if (has_resources) {
        bool has_thread = scheduler->workers.get_num_available_workers() > 0;
        if (has_thread) {
          InnerTask *task = this->runnable_tasks->pop();
          InnerWorker *worker = scheduler->workers.dequeue_worker();
          // Decrease Resources
          this->reserve_resources(task);
          launcher->enqueue(task, worker);
          this->status.increase(RuntimeReserverState::Success);
        } else {
          this->status.increase(RuntimeReserverState::NoWorker);
          fail_count++; // += max_fail;
          // break; // No more workers available
        }
      } else {
        this->status.increase(RuntimeReserverState::NoResource);
        fail_count++;
        // break; // No more resources available
      }
    } else {
      this->status.increase(RuntimeReserverState::NoTask);
      fail_count++; //+= max_fail;
      // break; // No more tasks available
    }
  }
  // Try to launch as many data movement tasks as possible
  has_task = true;
  num_tasks = 0;
  while (has_task) {
    num_tasks = this->get_movement_count();
    // std::cout << "RuntimeReserver::run: num movement tasks: " << num_tasks
    // << std::endl;
    has_task = num_tasks > 0;
    if (has_task) {
      InnerTask *task = this->movement_tasks->front();
      bool has_resources = check_data_resources(task);
      if (has_resources) {
        bool has_thread = scheduler->workers.get_num_available_workers() > 0;
        if (has_thread) {
          InnerTask *task = this->movement_tasks->pop();
          InnerWorker *worker = scheduler->workers.dequeue_worker();
          // Decrease Resources
          this->reserve_data_resources(task);
          launcher->enqueue(task, worker);
          this->status.increase(RuntimeReserverState::Success);
        } else {
          this->status.increase(RuntimeReserverState::NoWorker);
          break; // No more workers available
        }
      } else {
        this->status.increase(RuntimeReserverState::NoResource);
        break; // No more resources available
      }
    } else {
      this->status.increase(RuntimeReserverState::NoTask);
      break; // No more tasks available
    }
  }
}
Referenced by InnerScheduler::activate().
Member Data Documentation
launchable_tasks_buffer
std::vector<InnerTask *> RuntimeReserver::launchable_tasks_buffer [protected]
The buffer of tasks enqueued (and waiting) in the phase.
Definition at line 326 of file phases.hpp.
movement_tasks
std::shared_ptr<PhaseManager<ResourceCategory::Movement> > RuntimeReserver::movement_tasks [protected]
The multidevice queues for data movement tasks.
Definition at line 319 of file phases.hpp.
name
const std::string RuntimeReserver::name {`Runtime Reserver`} [inline], [static], [protected]
The name of the phase. Used for debugging and tracing.
Definition at line 322 of file phases.hpp.
Referenced by parla.cython.tasks.Task::__hash__(), parla.cython.tasks.Task::get_name(), parla.cython.tasks.Task::unpack_name(), and parla.cython.tasks.Task::update_name().
runnable_tasks
std::shared_ptr<PhaseManager<ResourceCategory::NonPersistent> > RuntimeReserver::runnable_tasks [protected]
The multidevice queues for compute tasks.
Definition at line 317 of file phases.hpp.
status
RuntimeReserverStatus RuntimeReserver::status {name} [protected]
The status of the phase. Used for debugging and tracing.
Definition at line 324 of file phases.hpp.
Referenced by parla.cython.scheduler.WorkerThread::run().
The documentation for this class was generated from the following files:
src/c/backend/include/phases.hpp
src/c/backend/phases.cpp