Device Class Reference
Devices can be distinguished from other devices by a class type and its index.
#include <device.hpp>
Public Member Functions
Device ()=delete
Device (DeviceType arch, DevID_t dev_id, MemorySz_t mem_sz, VCU_t num_vcus, void *py_dev, int copy_engines=2)
const DevID_t get_id () const
Return a device id.
const std::string get_name () const
const Resource_t query_resource (Resource type) const
const Resource_t query_reserved_resource (Resource type) const
const Resource_t query_mapped_resource (Resource type) const
const DeviceType get_type () const
const ResourcePool_t & get_resource_pool () const
Returns the device details (maximum resources available) This is assumed to be constant after device creation.
ResourcePool_t & get_mapped_pool ()
Returns the currently mapped resources on the device.
ResourcePool_t & get_reserved_pool ()
Returns the currently reserved resources on the device.
void * get_py_device ()
Returns the pointer to the python device object.
void set_global_id (DevID_t global_id)
const DevID_t get_global_id () const
const MemorySz_t get_memory_size () const
const VCU_t get_num_vcus () const
const Resource_t get_max_resource (Resource type) const
const Resource_t get_reserved_resource (Resource type) const
const Resource_t get_mapped_resource (Resource type) const
const bool check_resource_availability (DeviceRequirement *dev_req) const
Protected Attributes
DeviceType dev_type_
DevID_t dev_id_
DevID_t dev_global_id_
ResourcePool_t res_
ResourcePool_t mapped_res_
ResourcePool_t reserved_res_
void * py_dev_
std::unordered_map< std::string, size_t > resource_map_
Detailed Description
Devices can be distinguished from other devices by a class type and its index.
Definition at line 37 of file device.hpp.
Constructor & Destructor Documentation
Device() [1/2]
Device::Device () [delete]
Device() [2/2]
Device::Device (DeviceType arch, DevID_t dev_id, MemorySz_t mem_sz, VCU_t num_vcus, void * py_dev, int copy_engines = 2) [inline]
Definition at line 42 of file device.hpp.
      : py_dev_(py_dev), dev_id_(dev_id), dev_type_(arch) {
    res_.set(Resource::VCU, num_vcus);
    res_.set(Resource::Memory, mem_sz);
    res_.set(Resource::Copy, copy_engines);
    reserved_res_.set(Resource::VCU, num_vcus);
    reserved_res_.set(Resource::Memory, mem_sz);
    reserved_res_.set(Resource::Copy, copy_engines);
    mapped_res_.set(Resource::VCU, 0);
    mapped_res_.set(Resource::Memory, 0);
    mapped_res_.set(Resource::Copy, 0);
  }
References Copy, dev_type_, Device(), mapped_res_, Memory, py_dev_, res_, reserved_res_, and VCU.
Referenced by Device().
Member Function Documentation
check_resource_availability()
const bool Device::check_resource_availability (DeviceRequirement * dev_req) const
Definition at line 5 of file device.cpp.
                                                                    {
  return get_resource_pool().check_greater<ResourceCategory::All>(
      dev_req->res_req());
}
References All, get_resource_pool(), and DeviceRequirement::res_req().
get_global_id()
const DevID_t Device::get_global_id () const [inline]
Definition at line 111 of file device.hpp.
{ return dev_global_id_; }
get_id()
const DevID_t Device::get_id () const [inline]
Return a device id.
Definition at line 60 of file device.hpp.
{ return dev_id_; }
get_mapped_pool()
ResourcePool_t& Device::get_mapped_pool () [inline]
Returns the currently mapped resources on the device.
This starts at 0 and increases as resources are mapped. Decreased when resources are released at the end of a task. This is not runtime necessary, but useful to mapping policy.
Definition at line 95 of file device.hpp.
{ return mapped_res_; }
References mapped_res_.
Referenced by PArrayTracker::release_parray(), and PArrayTracker::reserve_parray().
get_mapped_resource()
const Resource_t Device::get_mapped_resource (Resource type) const [inline]
Definition at line 127 of file device.hpp.
                                                            {
    return this->mapped_res_.get(type);
  }
References mapped_res_.
get_max_resource()
const Resource_t Device::get_max_resource (Resource type) const [inline]
Definition at line 119 of file device.hpp.
                                                         {
    return this->res_.get(type);
  }
References res_.
get_memory_size()
const MemorySz_t Device::get_memory_size () const [inline]
Definition at line 113 of file device.hpp.
                                           {
    return res_.get(Resource::Memory);
  }
References Memory, and res_.
get_name()
const std::string Device::get_name () const [inline]
Definition at line 62 of file device.hpp.
                                   {
    return architecture_names[static_cast<int>(this->dev_type_)] + ":" +
           std::to_string(dev_id_);
  }
Referenced by parla.cython.device_manager.PrintableFrozenSet::__repr__().
get_num_vcus()
const VCU_t Device::get_num_vcus () const [inline]
Definition at line 117 of file device.hpp.
{ return res_.get(Resource::VCU); }
References res_, and VCU.
get_py_device()
void* Device::get_py_device () [inline]
Returns the pointer to the python device object.
Definition at line 109 of file device.hpp.
{ return py_dev_; }
References py_dev_.
get_reserved_pool()
ResourcePool_t& Device::get_reserved_pool () [inline]
Returns the currently reserved resources on the device.
This starts at max and decreases as resources are reserved. This represents the resources currently in use by the tasks. This is necessary to determine if tasks can be scheduled without oversubscription or OOM errors.
Definition at line 104 of file device.hpp.
{ return reserved_res_; }
References reserved_res_.
Referenced by InnerScheduler::task_cleanup_postsync().
get_reserved_resource()
const Resource_t Device::get_reserved_resource (Resource type) const [inline]
Definition at line 123 of file device.hpp.
                                                              {
    return this->reserved_res_.get(type);
  }
References reserved_res_.
get_resource_pool()
const ResourcePool_t& Device::get_resource_pool () const [inline]
Returns the device details (maximum resources available) This is assumed to be constant after device creation.
Definition at line 87 of file device.hpp.
{ return res_; }
References res_.
Referenced by check_resource_availability().
get_type()
const DeviceType Device::get_type () const [inline]
Definition at line 79 of file device.hpp.
{ return dev_type_; }
References dev_type_.
Referenced by DeviceManager::globalid_to_parrayid(), and DeviceManager::register_device().
query_mapped_resource()
const Resource_t Device::query_mapped_resource (Resource type) const [inline]
Definition at line 75 of file device.hpp.
                                                              {
    return this->mapped_res_.get(type);
  }
References mapped_res_.
query_reserved_resource()
const Resource_t Device::query_reserved_resource (Resource type) const [inline]
Definition at line 71 of file device.hpp.
                                                                {
    return this->reserved_res_.get(type);
  }
References reserved_res_.
query_resource()
const Resource_t Device::query_resource (Resource type) const [inline]
Definition at line 67 of file device.hpp.
                                                       {
    return this->res_.get(type);
  }
References res_.
set_global_id()
void Device::set_global_id (DevID_t global_id) [inline]
Definition at line 110 of file device.hpp.
{ dev_global_id_ = global_id; }
Member Data Documentation
dev_global_id_
DevID_t Device::dev_global_id_ [protected]
Definition at line 136 of file device.hpp.
dev_id_
DevID_t Device::dev_id_ [protected]
Definition at line 135 of file device.hpp.
dev_type_
DeviceType Device::dev_type_ [protected]
Definition at line 134 of file device.hpp.
Referenced by Device(), and get_type().
mapped_res_
ResourcePool_t Device::mapped_res_ [protected]
Definition at line 138 of file device.hpp.
Referenced by Device(), get_mapped_pool(), get_mapped_resource(), and query_mapped_resource().
py_dev_
void* Device::py_dev_ [protected]
Definition at line 140 of file device.hpp.
Referenced by Device(), and get_py_device().
res_
ResourcePool_t Device::res_ [protected]
Definition at line 137 of file device.hpp.
Referenced by Device(), get_max_resource(), get_memory_size(), get_num_vcus(), get_resource_pool(), and query_resource().
reserved_res_
ResourcePool_t Device::reserved_res_ [protected]
Definition at line 139 of file device.hpp.
Referenced by Device(), get_reserved_pool(), get_reserved_resource(), and query_reserved_resource().
resource_map_
std::unordered_map<std::string, size_t> Device::resource_map_ [protected]
Definition at line 141 of file device.hpp.
The documentation for this class was generated from the following files:
src/c/backend/include/device.hpp
src/c/backend/device.cpp