DeviceRequirement Class Reference
#include <resource_requirements.hpp>
Public Member Functions
DeviceRequirement (Device *dev, ResourcePool_t res_req)
bool is_multidev_req () override
bool is_arch_req () override
bool is_dev_req () override
Device * device ()
const ResourcePool_t & res_req () const
ResourcePool_t & res_req ()
Private Attributes
Device * dev_
ResourcePool_t res_req_
Detailed Description
Definition at line 51 of file resource_requirements.hpp.
Constructor & Destructor Documentation
DeviceRequirement()
DeviceRequirement::DeviceRequirement (Device * dev, ResourcePool_t res_req) [inline]
Definition at line 53 of file resource_requirements.hpp.
      : dev_(dev), res_req_(res_req) {}
References dev_, res_req_, and ResourcePool::ResourcePool().
Member Function Documentation
device()
Device* DeviceRequirement::device () [inline]
Definition at line 60 of file resource_requirements.hpp.
{ return dev_; }
References dev_.
Referenced by parla.cython.device.DeviceResourceRequirement::__repr__().
is_arch_req()
bool DeviceRequirement::is_arch_req () [inline], [override], [virtual]
Implements PlacementRequirementBase.
Definition at line 57 of file resource_requirements.hpp.
{ return false; }
is_dev_req()
bool DeviceRequirement::is_dev_req () [inline], [override], [virtual]
Implements PlacementRequirementBase.
Definition at line 58 of file resource_requirements.hpp.
{ return true; }
is_multidev_req()
bool DeviceRequirement::is_multidev_req () [inline], [override], [virtual]
Implements PlacementRequirementBase.
Definition at line 56 of file resource_requirements.hpp.
{ return false; }
res_req() [1/2]
ResourcePool_t& DeviceRequirement::res_req () [inline]
Definition at line 63 of file resource_requirements.hpp.
{ return res_req_; }
References res_req_.
Referenced by parla.cython.device.DeviceResourceRequirement::__repr__(), and Device::check_resource_availability().
res_req() [2/2]
const ResourcePool_t& DeviceRequirement::res_req () const [inline]
Definition at line 62 of file resource_requirements.hpp.
{ return res_req_; }
References res_req_.
Referenced by parla.cython.device.DeviceResourceRequirement::__repr__().
Member Data Documentation
dev_
Device* DeviceRequirement::dev_ [private]
Definition at line 66 of file resource_requirements.hpp.
Referenced by device(), and DeviceRequirement().
res_req_
ResourcePool_t DeviceRequirement::res_req_ [private]
Definition at line 67 of file resource_requirements.hpp.
Referenced by DeviceRequirement(), and res_req().
The documentation for this class was generated from the following file:
src/c/backend/include/resource_requirements.hpp