Launcher Class Reference
The Launcher phase of the scheduler. Dispatches tasks to workers.
#include <phases.hpp>
Public Member Functions
Launcher (InnerScheduler *scheduler, DeviceManager *devices)
void enqueue (InnerTask *task)
Add a task to the launcher. Assigns a task to a free worker.
void enqueue (InnerTask *task, InnerWorker *worker)
Add a task to the launcher. Assigns a task to a free worker.
void enqueue (std::vector< InnerTask * > &tasks)
Add a batch of tasks to the launcher. Assigns them to free workers.
void run ()
A placeholder function in case work needs to be done at this stage.
void run (SchedulerPhase *next_phase)
Run the phase. Check tasks in the enqueued buffer, check phase condition, and move tasks to the next phase.
size_t get_count ()
Number of running tasks.
Public Attributes
std::atomic< size_t > num_running_tasks {0}
Protected Attributes
LauncherStatus status {name}
The status of the phase. Used for debugging and tracing.
TaskList task_buffer
Buffer to store not yet launched tasks. Currently unused.
WorkerList worker_buffer
Buffer to store unassigned workers. Currently unused.
Static Protected Attributes
static const std::string name {`Launcher`}
The name of the phase. Used for debugging and tracing.
Detailed Description
The Launcher phase of the scheduler. Dispatches tasks to workers.
Definition at line 354 of file phases.hpp.
Constructor & Destructor Documentation
Launcher()
Launcher::Launcher (InnerScheduler * scheduler, DeviceManager * devices) [inline]
Definition at line 360 of file phases.hpp.
      : SchedulerPhase(scheduler, devices) {}
References SchedulerPhase::SchedulerPhase().
Referenced by InnerScheduler::InnerScheduler().
Member Function Documentation
enqueue() [1/3]
void Launcher::enqueue (InnerTask * task) [inline], [virtual]
Add a task to the launcher. Assigns a task to a free worker.
Implements SchedulerPhase.
Definition at line 364 of file phases.hpp.
{};
enqueue() [2/3]
void Launcher::enqueue (InnerTask * task, InnerWorker * worker)
Add a task to the launcher. Assigns a task to a free worker.
Definition at line 473 of file phases.cpp.
                                                           {
  NVTX_RANGE("Launcher::enqueue", NVTX_COLOR_LIGHT_GREEN)
  // std::cout << "Launcher::enqueue" << std::endl;
  // Immediately launch task
  task->set_state(TaskState::RUNNING);
  this->num_running_tasks++;
  // Assign task to thread and notify via c++ condition variable.
  // No GIL needed until worker wakes.
  worker->assign_task(task);
  // std::cout << "Assigned " << task->name << " to " << worker->thread_idx
  // << std::endl;
  LOG_INFO(WORKER, "Assigned {} to {}", task, worker);
}
enqueue() [3/3]
void Launcher::enqueue (std::vector< InnerTask * > & tasks) [inline], [virtual]
Add a batch of tasks to the launcher. Assigns them to free workers.
Implements SchedulerPhase.
Definition at line 368 of file phases.hpp.
{};
get_count()
size_t Launcher::get_count () [inline], [virtual]
Number of running tasks.
A task is running if it has been assigned to a worker and is not complete
Implements SchedulerPhase.
Definition at line 377 of file phases.hpp.
{ return this->num_running_tasks.load(); }
Referenced by InnerScheduler::get_num_running_tasks().
run() [1/2]
void Launcher::run ()
A placeholder function in case work needs to be done at this stage.
Not used.
Definition at line 491 of file phases.cpp.
                   {
  throw std::runtime_error("Launcher::run() not implemented.");
}
Referenced by run().
run() [2/2]
void Launcher::run (SchedulerPhase * next_phase) [inline], [virtual]
Run the phase. Check tasks in the enqueued buffer, check phase condition, and move tasks to the next phase.
Parameters
next_phase The next phase to move tasks to.
Implements SchedulerPhase.
Definition at line 373 of file phases.hpp.
{ this->run(); };
References run().
Member Data Documentation
name
const std::string Launcher::name {`Launcher`} [inline], [static], [protected]
The name of the phase. Used for debugging and tracing.
Definition at line 381 of file phases.hpp.
Referenced by parla.cython.tasks.Task::__hash__(), parla.cython.tasks.Task::get_name(), parla.cython.tasks.Task::unpack_name(), and parla.cython.tasks.Task::update_name().
num_running_tasks
std::atomic<size_t> Launcher::num_running_tasks {0}
Definition at line 358 of file phases.hpp.
status
LauncherStatus Launcher::status {name} [protected]
The status of the phase. Used for debugging and tracing.
Definition at line 383 of file phases.hpp.
Referenced by parla.cython.scheduler.WorkerThread::run().
task_buffer
TaskList Launcher::task_buffer [protected]
Buffer to store not yet launched tasks. Currently unused.
Definition at line 385 of file phases.hpp.
worker_buffer
WorkerList Launcher::worker_buffer [protected]
Buffer to store unassigned workers. Currently unused.
Definition at line 387 of file phases.hpp.
The documentation for this class was generated from the following files:
src/c/backend/include/phases.hpp
src/c/backend/phases.cpp