parla.cython.device_manager.StreamPool Class Reference
Public Member Functions
def __init__ (self, device_list, per_device=8)
def get_stream (self, device)
def return_stream (self, stream)
def __summarize__ (self)
def __repr__ (self)
Public Attributes
StreamClass
Private Attributes
_device_list
_per_device
_pool
Detailed Description
Definition at line 79 of file device_manager.pyx.
Constructor & Destructor Documentation
__init__()
def parla.cython.device_manager.StreamPool.__init__ (self, device_list, per_device = 8)
Definition at line 81 of file device_manager.pyx.
    def __init__(self, device_list, per_device=8):
        if CUPY_ENABLED:
            self.StreamClass = CupyStream
        else:
            self.StreamClass = Stream
        self._device_list = device_list
        self._per_device = per_device
        self._pool = {}
        for device in self._device_list:
            self._pool[device] = []
            
            with device.device as d:
                for i in range(self._per_device):
                    self._pool[device].append(self.StreamClass(device=device))
Member Function Documentation
__repr__()
def parla.cython.device_manager.StreamPool.__repr__ (self)
Definition at line 117 of file device_manager.pyx.
    def __repr__(self):
        return f"StreamPool({self.__summarize__()})"
#TODO(wlr): - Allow device manager to initialize non-contiguous gpu ids.
#TODO(wlr): - Provide a way to iterate over these real device ids
           
Referenced by parla.common.globals.Storage.__str__(), parla.common.globals.LocalStack.__str__(), parla.cython.device.Stream.__str__(), parla.cython.device.CupyStream.__str__(), and parla.cython.tasks.TaskState.__str__().
__summarize__()
def parla.cython.device_manager.StreamPool.__summarize__ (self)
Definition at line 110 of file device_manager.pyx.
    def __summarize__(self):
        summary = ""
        for device in self._device_list:
            summary += f"({device} : {len(self._pool[device])})"
        return summary
References parla.cython.device_manager.StreamPool._device_list.
get_stream()
def parla.cython.device_manager.StreamPool.get_stream (self, device)
Definition at line 99 of file device_manager.pyx.
    def get_stream(self, device):
        if len(self._pool[device]) == 0:
            #Create a new stream if the pool is empty.
            new_stream = self.StreamClass(device=device)
            return new_stream
        return self._pool[device].pop()
References parla.cython.device_manager.StreamPool._pool, and parla.cython.device_manager.StreamPool.StreamClass.
return_stream()
def parla.cython.device_manager.StreamPool.return_stream (self, stream)
Definition at line 107 of file device_manager.pyx.
    def return_stream(self, stream):
        self._pool[stream.device].append(stream)
References parla.cython.device_manager.StreamPool._pool.
Member Data Documentation
_device_list
parla.cython.device_manager.StreamPool._device_list [private]
Definition at line 88 of file device_manager.pyx.
Referenced by parla.cython.device_manager.StreamPool.__summarize__().
_per_device
parla.cython.device_manager.StreamPool._per_device [private]
Definition at line 89 of file device_manager.pyx.
_pool
parla.cython.device_manager.StreamPool._pool [private]
Definition at line 90 of file device_manager.pyx.
Referenced by parla.cython.device_manager.StreamPool.get_stream(), and parla.cython.device_manager.StreamPool.return_stream().
StreamClass
parla.cython.device_manager.StreamPool.StreamClass
Definition at line 84 of file device_manager.pyx.
Referenced by parla.cython.device_manager.StreamPool.get_stream().
The documentation for this class was generated from the following file:
src/python/parla/cython/device_manager.pyx