parla.common.globals Namespace Reference
Classes
class SynchronizationType
class DeviceType
class AccessMode
class Storage
class LocalStorage
class LocalStack
class Locals
Functions
def get_locals ()
def get_current_task ()
def get_current_devices ()
def get_active_device ()
def get_current_stream ()
def get_default_taskspace ()
def get_current_context ()
def get_scheduler ()
def get_device_manager ()
def get_stream_pool ()
def has_environment ()
Variables
num_gpu = cupy.cuda.runtime.getDeviceCount()
tuple CUPY_ENABLED = (os.getenv(`PARLA_ENABLE_CUPY`, `1`) == `1`)
cupy = None
tuple CROSSPY_ENABLED = (os.getenv(`PARLA_ENABLE_CROSSPY`, `1`) == `1`)
crosspy = None
tuple USE_PYTHON_RUNAHEAD = (os.getenv(`PARLA_ENABLE_PYTHON_RUNAHEAD`, `1`) == `1`)
tuple PREINIT_THREADS = (os.getenv(`PARLA_PREINIT_THREADS`, `1`) == `1`)
dictionary _global_data_tasks = {}
int VCU_BASELINE = 1000
SYNC_FLAG = os.getenv(`PARLA_DEFAULT_SYNC`, `0`)
default_sync = SynchronizationType.NONE
_GlobalStorage = Storage()
_Locals = Locals()
Function Documentation
get_active_device()
def parla.common.globals.get_active_device ()
Definition at line 255 of file globals.py.
def get_active_device():
    return _Locals.active_device
get_current_context()
def parla.common.globals.get_current_context ()
Definition at line 266 of file globals.py.
def get_current_context():
    return _Locals.context
Referenced by parla.common.array.clone_here(), parla.common.array.NumpyArray.copy_from(), parla.common.array.CupyArray.copy_from(), and parla.utility.execute.synthetic_kernel_gpu().
get_current_devices()
def parla.common.globals.get_current_devices ()
Definition at line 251 of file globals.py.
def get_current_devices():
    return _Locals.devices
Referenced by parla.common.parray.core.PArray._get_compute_device_for_crosspy(), and parla.common.parray.core.PArray._get_current_device().
get_current_stream()
def parla.common.globals.get_current_stream ()
Definition at line 259 of file globals.py.
def get_current_stream():
    return _Locals.stream
get_current_task()
def parla.common.globals.get_current_task ()
Definition at line 248 of file globals.py.
def get_current_task():
    return _Locals.task
get_default_taskspace()
def parla.common.globals.get_default_taskspace ()
Definition at line 262 of file globals.py.
def get_default_taskspace():
    return _Locals.scheduler.default_taskspace
get_device_manager()
def parla.common.globals.get_device_manager ()
Definition at line 274 of file globals.py.
def get_device_manager():
    scheduler = get_scheduler()
    if scheduler is None:
        raise RuntimeError("Attempted to access device manager, but no scheduler is active.")
    else:
        return scheduler.device_manager
References parla.common.globals.get_scheduler().
Referenced by parla.cython.device.ImportableArchitecture.__call__(), parla.cython.device.ImportableArchitecture.__getitem__(), parla.cython.device.ImportableArchitecture.__len__(), parla.cython.device.ImportableArchitecture.add_device(), parla.cython.device.ImportableArchitecture.devices(), and parla.common.globals.get_stream_pool().
get_locals()
def parla.common.globals.get_locals ()
Definition at line 245 of file globals.py.
def get_locals():
    return _Locals
get_scheduler()
def parla.common.globals.get_scheduler ()
Definition at line 270 of file globals.py.
def get_scheduler():
    return _Locals.scheduler
Referenced by parla.common.parray.core.PArray._process_operations(), and parla.common.globals.get_device_manager().
get_stream_pool()
def parla.common.globals.get_stream_pool ()
Definition at line 281 of file globals.py.
def get_stream_pool():
    return get_device_manager().stream_pool
References parla.common.globals.get_device_manager().
Referenced by parla.cython.tasks.GPUEnvironment.__init__(), parla.cython.tasks.TaskEnvironment.finalize(), parla.cython.tasks.GPUEnvironment.finalize(), parla.cython.tasks.TaskEnvironment.return_streams(), parla.cython.tasks.GPUEnvironment.return_streams(), and parla.cython.tasks.TaskEnvironment.synchronize().
has_environment()
def parla.common.globals.has_environment ()
Definition at line 285 of file globals.py.
def has_environment():
    return True if _Locals.context else False
Referenced by parla.common.parray.core.PArray._get_compute_device_for_crosspy(), and parla.common.parray.core.PArray._get_current_device().
Variable Documentation
_global_data_tasks
dictionary parla.common.globals._global_data_tasks = {} [private]
Definition at line 40 of file globals.py.
_GlobalStorage
parla.common.globals._GlobalStorage = Storage() [private]
Definition at line 131 of file globals.py.
_Locals
parla.common.globals._Locals = Locals() [private]
Definition at line 242 of file globals.py.
crosspy
parla.common.globals.crosspy = None
Definition at line 27 of file globals.py.
CROSSPY_ENABLED
bool parla.common.globals.CROSSPY_ENABLED = (os.getenv(`PARLA_ENABLE_CROSSPY`, `1`) == `1`)
Definition at line 24 of file globals.py.
cupy
parla.common.globals.cupy = None
Definition at line 18 of file globals.py.
CUPY_ENABLED
bool parla.common.globals.CUPY_ENABLED = (os.getenv(`PARLA_ENABLE_CUPY`, `1`) == `1`)
Definition at line 16 of file globals.py.
default_sync
parla.common.globals.default_sync = SynchronizationType.NONE
Definition at line 59 of file globals.py.
num_gpu
parla.common.globals.num_gpu = cupy.cuda.runtime.getDeviceCount()
Definition at line 15 of file globals.py.
PREINIT_THREADS
tuple parla.common.globals.PREINIT_THREADS = (os.getenv(`PARLA_PREINIT_THREADS`, `1`) == `1`)
Definition at line 34 of file globals.py.
SYNC_FLAG
parla.common.globals.SYNC_FLAG = os.getenv(`PARLA_DEFAULT_SYNC`, `0`)
Definition at line 56 of file globals.py.
USE_PYTHON_RUNAHEAD
tuple parla.common.globals.USE_PYTHON_RUNAHEAD = (os.getenv(`PARLA_ENABLE_PYTHON_RUNAHEAD`, `1`) == `1`)
Definition at line 33 of file globals.py.
VCU_BASELINE
int parla.common.globals.VCU_BASELINE = 1000
Definition at line 43 of file globals.py.