parla.cython.tasks.TaskReady Class Reference
This state specifies that a task is `ready` to be launched.
Public Member Functions
def value (self)
def is_terminal (self)
Detailed Description
This state specifies that a task is `ready` to be launched.
Its dependencies have been dispatched to hardware queues (or have completed)
Definition at line 121 of file tasks.pyx.
Member Function Documentation
is_terminal()
def parla.cython.tasks.TaskReady.is_terminal (self)
Reimplemented from parla.cython.tasks.TaskState.
Definition at line 130 of file tasks.pyx.
    def is_terminal(self):
        return False
Referenced by parla.cython.tasks.TaskEnvironment.streams(), and parla.cython.tasks.TaskEnvironment.synchronize().
value()
def parla.cython.tasks.TaskReady.value (self)
Reimplemented from parla.cython.tasks.TaskState.
Definition at line 126 of file tasks.pyx.
    def value(self):
        return 4
Referenced by parla.utility.threads.Propagate.run().
The documentation for this class was generated from the following file:
src/python/parla/cython/tasks.pyx