parla.cython.tasks.TaskState Class Reference
Abstract base class for Task State.
Public Member Functions
int value (self)
bool is_terminal (self)
Static Private Attributes
list __slots__ = []
Detailed Description
Abstract base class for Task State.
Definition at line 50 of file tasks.pyx.
Member Function Documentation
is_terminal()
bool parla.cython.tasks.TaskState.is_terminal (self)
Reimplemented in parla.cython.tasks.TaskException, parla.cython.tasks.TaskCompleted, parla.cython.tasks.TaskRunahead, parla.cython.tasks.TaskRunning, parla.cython.tasks.TaskReady, parla.cython.tasks.TaskReserved, parla.cython.tasks.TaskMapped, parla.cython.tasks.TaskSpawned, and parla.cython.tasks.TaskCreated.
Definition at line 64 of file tasks.pyx.
    def is_terminal(self) -> bool:
        raise NotImplementedError()
Referenced by parla.cython.tasks.TaskEnvironment.streams(), and parla.cython.tasks.TaskEnvironment.synchronize().
value()
int parla.cython.tasks.TaskState.value (self)
Reimplemented in parla.cython.tasks.TaskException, parla.cython.tasks.TaskCompleted, parla.cython.tasks.TaskRunahead, parla.cython.tasks.TaskRunning, parla.cython.tasks.TaskReady, parla.cython.tasks.TaskReserved, parla.cython.tasks.TaskMapped, parla.cython.tasks.TaskSpawned, and parla.cython.tasks.TaskCreated.
Definition at line 59 of file tasks.pyx.
    def value(self) -> int:
        raise NotImplementedError()
        
Referenced by parla.utility.threads.Propagate.run().
Member Data Documentation
__slots__
list parla.cython.tasks.TaskState.__slots__ = [] [static], [private]
Definition at line 55 of file tasks.pyx.
The documentation for this class was generated from the following file:
src/python/parla/cython/tasks.pyx