parla.cython.tasks.TaskMapped Class Reference
This state specifies that a task has been mapped to a device set, but not yet resered its resources there.
Public Member Functions
def value (self)
def is_terminal (self)
Detailed Description
This state specifies that a task has been mapped to a device set, but not yet resered its resources there.
Definition at line 95 of file tasks.pyx.
Member Function Documentation
is_terminal()
def parla.cython.tasks.TaskMapped.is_terminal (self)
Reimplemented from parla.cython.tasks.TaskState.
Definition at line 104 of file tasks.pyx.
    def is_terminal(self):
        return False
Referenced by parla.cython.tasks.TaskEnvironment.streams(), and parla.cython.tasks.TaskEnvironment.synchronize().
value()
def parla.cython.tasks.TaskMapped.value (self)
Reimplemented from parla.cython.tasks.TaskState.
Definition at line 100 of file tasks.pyx.
    def value(self):
        return 2
Referenced by parla.utility.threads.Propagate.run().
The documentation for this class was generated from the following file:
src/python/parla/cython/tasks.pyx