parla.cython.tasks._TaskLocals Class Reference
Public Member Functions
def __init__ (self)
def ctx (self)
def ctx (self, v)
def global_tasks (self)
def global_tasks (self, v)
Public Attributes
task_scopes
spawn_count
Private Attributes
_ctx
_global_tasks
Detailed Description
Definition at line 248 of file tasks.pyx.
Constructor & Destructor Documentation
__init__()
def parla.cython.tasks._TaskLocals.__init__ (self)
Definition at line 249 of file tasks.pyx.
    def __init__(self):
        super(_TaskLocals, self).__init__()
        self.task_scopes = []
        self.spawn_count = 0
Member Function Documentation
ctx() [1/2]
def parla.cython.tasks._TaskLocals.ctx (self)
Definition at line 255 of file tasks.pyx.
    def ctx(self):
        return getattr(self, "_ctx", None)
Referenced by parla.cython.tasks._TaskLocals.ctx().
ctx() [2/2]
def parla.cython.tasks._TaskLocals.ctx (self, v)
Definition at line 259 of file tasks.pyx.
    def ctx(self, v):
        self._ctx = v
References parla.cython.tasks._TaskLocals.ctx().
global_tasks() [1/2]
def parla.cython.tasks._TaskLocals.global_tasks (self)
Definition at line 263 of file tasks.pyx.
    def global_tasks(self):
        return getattr(self, "_global_tasks", [])
Referenced by parla.cython.tasks._TaskLocals.global_tasks().
global_tasks() [2/2]
def parla.cython.tasks._TaskLocals.global_tasks (self, v)
Definition at line 267 of file tasks.pyx.
    def global_tasks(self, v):
        self._global_tasks = v
References parla.cython.tasks._TaskLocals.global_tasks().
Member Data Documentation
_ctx
parla.cython.tasks._TaskLocals._ctx [private]
Definition at line 260 of file tasks.pyx.
_global_tasks
parla.cython.tasks._TaskLocals._global_tasks [private]
Definition at line 268 of file tasks.pyx.
spawn_count
parla.cython.tasks._TaskLocals.spawn_count
Definition at line 252 of file tasks.pyx.
task_scopes
parla.cython.tasks._TaskLocals.task_scopes
Definition at line 251 of file tasks.pyx.
The documentation for this class was generated from the following file:
src/python/parla/cython/tasks.pyx