parla.utility.graphs Namespace Reference
Classes
class DeviceType
class LogState
class MovementType
class DataInitType
class TaskID
class TaskRuntimeInfo
class TaskDataInfo
class TaskInfo
class DataInfo
class TaskTime
class TimeSample
class TaskConfig
class TaskConfigs
class GraphConfig
class IndependentConfig
class SerialConfig
class ReductionConfig
class ReductionScatterConfig
class RunConfig
Functions
Dict[TaskID, TaskInfo] convert_to_dictionary (List[TaskInfo] task_list)
Dict[TaskID, TaskInfo] shuffle_tasks (Dict[TaskID, TaskInfo] tasks)
Union[int, Fraction] extract (str string)
Tuple[Dict[int, DataInfo], Dict[TaskID, TaskInfo]] read_pgraph (str filename)
int get_time (str line)
int check_log_line (str line)
TaskID convert_task_id (str task_id, int instance=0)
def get_task_properties (str line)
Tuple[Dict[TaskID, TaskTime], Dict[TaskID, List[TaskID]]] parse_blog (str filename='parla.blog')
str generate_serial_graph (SerialConfig config)
str generate_reduction_graph (ReductionConfig config)
str generate_independent_graph (IndependentConfig config)
str generate_reduction_scatter_graph (ReductionScatterConfig tgraph_config)
Variables
int num_gpus = 4
task_filter = re.compile(r'InnerTask\{ .*? \}')
list __all__
Function Documentation
check_log_line()
int parla.utility.graphs.check_log_line (str line)
Definition at line 435 of file graphs.py.
def check_log_line(line: str) -> int:
    if "Running task" in line:
        return LogState.START_TASK
    elif "Notified dependents" in line:
        return LogState.NOTIFY_DEPENDENTS
    elif "Assigned " in line:
        return LogState.ASSIGNED_TASK
    elif "Runahead task" in line:
        return LogState.RUNAHEAD_TASK
    elif "Completed task" in line:
        return LogState.COMPLETED_TASK
    elif "Adding dependencies" in line:
        return LogState.ADDING_DEPENDENCIES
    elif "has constraints" in line:
        return LogState.ADD_CONSTRAINT
    else:
        return LogState.UNKNOWN
Referenced by parla.utility.graphs.parse_blog().
convert_task_id()
TaskID parla.utility.graphs.convert_task_id (str task_id, int instance = 0)
Definition at line 454 of file graphs.py.
def convert_task_id(task_id: str, instance: int = 0) -> TaskID:
    id = task_id.strip().split('_')
    taskspace = id[0]
    task_idx = tuple([int(i) for i in id[1:]])
    return TaskID(taskspace, task_idx, int(instance))
Referenced by parla.utility.graphs.get_task_properties().
convert_to_dictionary()
Dict[TaskID, TaskInfo] parla.utility.graphs.convert_to_dictionary (List[TaskInfo] task_list)
Converts a task list to a task graph dictionary
Definition at line 260 of file graphs.py.
def convert_to_dictionary(task_list: List[TaskInfo]) -> Dict[TaskID, TaskInfo]:
    """
    Converts a task list to a task graph dictionary
    """
    task_dict = dict()
    for task in task_list:
        task_dict[task.task_id] = task
    return task_dict
Referenced by parla.utility.graphs.read_pgraph(), and parla.utility.graphs.shuffle_tasks().
extract()
Union[int, Fraction] parla.utility.graphs.extract (str string)
Extracts string as decimal or int
Definition at line 280 of file graphs.py.
def extract(string: str) -> Union[int, Fraction]:
    """
    Extracts string as decimal or int
    """
    if "." in string:
        return Fraction(string)
    else:
        return int(string)
Referenced by parla.utility.graphs.read_pgraph().
generate_independent_graph()
str parla.utility.graphs.generate_independent_graph (IndependentConfig config)
Definition at line 797 of file graphs.py.
def generate_independent_graph(config: IndependentConfig) -> str:
    task_config = config.task_config
    configurations = task_config.configurations
    num_gpus = config.num_gpus
    graph = ""
    data_config_string = ""
    # TODO(hc): for now, assume that data allocation starts from cpu.
    if config.data_pattern == DataInitType.NO_DATA:
        data_config_string = f"{1 , -1}"
    elif config.data_pattern == DataInitType.INDEPENDENT_DATA:
        single_data_block_size = config.total_data_width
        config.data_partitions = 64
        for i in range(config.data_partitions):
            data_config_string += f"{single_data_block_size , -1}"
            if i+1 < config.data_partitions:
                data_config_string += f" | "
    elif config.data_pattern == DataInitType.OVERLAPPED_DATA:
        raise NotImplementedError(
            "[Independent] Data patterns not implemented")
    else:
        raise ValueError("[Independent] Data patterns not implemented")
    data_config_string += "\n"
    if task_config is None:
        raise ValueError("Task config must be specified")
    graph += data_config_string
    for i in range(config.task_count):
        read_data_block = i % config.data_partitions
        configuration_string = ""
        for device_id, task_config in configurations.items():
            last_flag = 1 if device_id == list(
                configurations.keys())[-1] else 0
            if config.fixed_placement:
                device_id = int(DeviceType.USER_CHOSEN_DEVICE + i % num_gpus)
            configuration_string += f"{{ {device_id} : {task_config.task_time}, {task_config.device_fraction}, {task_config.gil_accesses}, {task_config.gil_fraction}, {task_config.memory} }}"
            if last_flag == 0:
                configuration_string += ", "
        graph += f"{i} | {configuration_string} | | {read_data_block} : :\n"
    return graph
generate_reduction_graph()
str parla.utility.graphs.generate_reduction_graph (ReductionConfig config)
Definition at line 713 of file graphs.py.
def generate_reduction_graph(config: ReductionConfig) -> str:
    task_config = config.task_config
    num_gpus = config.num_gpus
    configurations = task_config.configurations
    graph = ""
    if task_config is None:
        raise ValueError("Task config must be specified")
    data_config_string = ""
    if config.data_pattern == DataInitType.NO_DATA:
        data_config_string = "{1 : -1}\n"
    elif config.data_pattern == DataInitType.INDEPENDENT_DATA:
        raise NotImplementedError("[Reduction] Data patterns not implemented")
    else:
        single_data_block_size = config.total_data_width
        for i in range(config.branch_factor**config.levels):
            if i > 0:
                data_config_string += " | "
            data_config_string += f"{single_data_block_size, -1}"
    data_config_string += "\n"
    graph += data_config_string
    post_configuration_string = ""
    # TODO(hc): when this was designed, we considered multidevice placement.
    # but for now, we only consider a single device placement and so,
    # follow the old generator's graph generation rule.
    device_id = DeviceType.ANY_GPU_DEVICE
    for config_device_id, task_config in configurations.items():
        last_flag = 1 if config_device_id == list(
            configurations.keys())[-1] else 0
        post_configuration_string += f"{task_config.task_time}, {task_config.device_fraction}, {task_config.gil_accesses}, {task_config.gil_fraction}, {task_config.memory} }}"
        # TODO(hc): This should be refined.
        # If users did not set "fixed", then it should be any cpu or gpu.
        device_id = config_device_id[-1]
        if last_flag == 0:
            post_configuration_string += ", "
    reverse_level = 0
    global_idx = 0
    for i in range(config.levels, -1, -1):
        total_tasks_in_level = config.branch_factor ** i
        segment = total_tasks_in_level / num_gpus
        for j in range(total_tasks_in_level):
            if reverse_level > 0:
                dependency_string = " "
                for k in range(config.branch_factor):
                    dependency_string += f"{reverse_level-1, config.branch_factor*j + k}"
                    if k+1 < config.branch_factor:
                        dependency_string += " : "
            else:
                dependency_string = " "
            if reverse_level > 0:
                l = 0
                read_dependency = " "
                targets = [config.branch_factor**(reverse_level-1)]
                for k in targets:
                    read_dependency += f"{(config.branch_factor**(reverse_level))*j+k}"
                    l += 1
                    if l < len(targets):
                        read_dependency += " , "
                write_dependency = f"{config.branch_factor**(reverse_level)*j}"
            else:
                read_dependency = " "
                write_dependency = f"{global_idx}"
            if config.fixed_placement:
                # USER_CHOSEN_DEVICE acts as an offset.
                device_id = int(DeviceType.USER_CHOSEN_DEVICE + j // segment)
            else:
                assert device_id == DeviceType.CPU_DEVICE or device_id == DeviceType.ANY_GPU_DEVICE
            pre_configuration_string = f"{{ {device_id} : "
            configuration_string = pre_configuration_string + post_configuration_string
            graph += f"{reverse_level, j} | {configuration_string} | {dependency_string} | {read_dependency} : : {write_dependency} \n"
            global_idx += 1
        reverse_level += 1
    return graph
generate_reduction_scatter_graph()
str parla.utility.graphs.generate_reduction_scatter_graph (ReductionScatterConfig tgraph_config)
Generate reduction-scatter graph input file.

e.g.,
* * * * * * (bulk tasks) 
\ | | | | /
     *      (bridge task)
/ | | | | \
* * * * * *
...
Definition at line 841 of file graphs.py.
def generate_reduction_scatter_graph(tgraph_config: ReductionScatterConfig) -> str:
    """
    Generate reduction-scatter graph input file.
    e.g.,
    * * * * * * (bulk tasks)
    \ | | | | /
         * (bridge task)
    / | | | | \
    * * * * * *
    ...
    """
    task_config = tgraph_config.task_config
    configurations = task_config.configurations
    num_gpus = tgraph_config.num_gpus
    num_tasks = tgraph_config.task_count
    # Level starts from 1
    levels = tgraph_config.levels
    # Calcualte the number of bridge tasks in the graph.
    num_bridge_tasks = levels // 2
    num_bridge_tasks += 1 if (levels % 2 > 0) else 0
    # Calculate the number of bulk tasks in the graph.
    num_bulk_tasks = (num_tasks - num_bridge_tasks)
    # Calculate the number of bulk tasks per level.
    num_levels_for_bulk_tasks = levels // 2 + 1
    num_bulk_tasks_per_level = num_bulk_tasks // num_levels_for_bulk_tasks
    # All the remaining bulk tasks are added to the last level.
    num_bulk_tasks_last_level = (
        num_bulk_tasks % num_levels_for_bulk_tasks) + num_bulk_tasks_per_level
    # Calculate the number of tasks per gpu per level.
    num_bulk_tasks_per_gpu = (num_bulk_tasks_per_level) // num_gpus
    """
    for l in range(levels + 1):
        if l % 2 > 0:
            print(f"Level {l}: -- 1 --", flush=True)
        else:
            if l == levels:
                print(f"Level {l}: {num_bulk_tasks_last_level}, {num_bulk_tasks_per_gpu}", flush=True)
            else:
                print(f"Level {l}: {num_bulk_tasks_per_level}, {num_bulk_tasks_per_gpu}", flush=True)
    """
    graph = ""
    data_config_string = ""
    # TODO(hc): for now, assume that data allocation starts from cpu.
    if tgraph_config.data_pattern == DataInitType.NO_DATA:
        data_config_string = f"{1, -1}"
    elif tgraph_config.data_pattern == DataInitType.OVERLAPPED_DATA:
        # Each bulk task takes an individual (non-overlapped) data block.
        # A bridge task reduces all data blocks from the bulk tasks in the previous level.
        single_data_block_size = tgraph_config.total_data_width
        for d in range(num_bulk_tasks_last_level):
            if d > 0:
                data_config_string += " | "
            data_config_string += f"{single_data_block_size, -1}"
    elif tgraph_config.data_pattern == DataInitType.INDEPENDENT_DATA:
        raise NotImplementedError(
            "[Independent] Data patterns not implemented")
    data_config_string += "\n"
    graph += data_config_string
    # TODO(hc): I don't know how to handle user-fixed placement on multi-device
    # tasks. Let me design single device task workload.
    assert len(task_config.configurations) == 1
    # Construct task graphs.
    task_id = 0
    bridge_task_dev_id = DeviceType.USER_CHOSEN_DEVICE if tgraph_config.fixed_placement else \
        DeviceType.ANY_GPU_DEVICE
    last_bridge_task_id_str = ""
    last_bridge_task_id = 0
    for l in range(levels + 1):
        # If the last level has a bridge task, the previous level should take all remaining bulk
        # tasks.
        if levels % 2 > 0:
            l_num_bulk_tasks = num_bulk_tasks_per_level if l < (
                levels - 1) else num_bulk_tasks_last_level
        else:
            l_num_bulk_tasks = num_bulk_tasks_per_level if l < levels else num_bulk_tasks_last_level
        if l % 2 > 0: # Bridge task condition
            dependency_block = ""
            inout_data_block = ""
            for d in range(l_num_bulk_tasks):
                inout_data_block += f"{d}"
                if l == 1:
                    dependency_block += f"{d + last_bridge_task_id}"
                else:
                    dependency_block += f"{d + last_bridge_task_id + 1}"
                if d != (l_num_bulk_tasks - 1):
                    inout_data_block += ","
                    dependency_block += " : "
            # TODO(hc): assume a single device task.
            for _, sdevice_task_config in task_config.configurations.items():
                graph += (f"{task_id} | {{ {bridge_task_dev_id} : {sdevice_task_config.task_time}, "
                          f"{sdevice_task_config.device_fraction}, {sdevice_task_config.gil_accesses}, "
                          f"{sdevice_task_config.gil_fraction}, {sdevice_task_config.memory} }}")
            graph += f" | {dependency_block}"
            graph += f" | : : {inout_data_block}\n"
            if tgraph_config.fixed_placement:
                bridge_task_dev_id += 1
                if bridge_task_dev_id == num_gpus + DeviceType.USER_CHOSEN_DEVICE:
                    bridge_task_dev_id = DeviceType.USER_CHOSEN_DEVICE
            last_bridge_task_id_str = f"{task_id}"
            last_bridge_task_id = int(task_id)
            task_id += 1
        else: # Bulk tasks condition
            bulk_task_id_per_gpu = 0
            bulk_task_dev_id = DeviceType.USER_CHOSEN_DEVICE if tgraph_config.fixed_placement else \
                DeviceType.ANY_GPU_DEVICE
            for bulk_task_id in range(l_num_bulk_tasks):
                inout_data_block = f"{bulk_task_id}"
                # TODO(hc): assume a single device task.
                for _, sdevice_task_config in task_config.configurations.items():
                    graph += (f"{task_id} | {{ {bulk_task_dev_id} : {sdevice_task_config.task_time}, "
                              f"{sdevice_task_config.device_fraction}, {sdevice_task_config.gil_accesses}, "
                              f"{sdevice_task_config.gil_fraction}, {sdevice_task_config.memory} }}")
                graph += f" | {last_bridge_task_id_str}"
                graph += f" | : : {inout_data_block}\n"
                l_num_bulk_tasks_per_gpu = l_num_bulk_tasks // num_gpus
                if tgraph_config.fixed_placement:
                    if l_num_bulk_tasks % num_gpus >= (bulk_task_dev_id - DeviceType.USER_CHOSEN_DEVICE):
                        l_num_bulk_tasks_per_gpu += 1
                    bulk_task_id_per_gpu += 1
                    if bulk_task_id_per_gpu == l_num_bulk_tasks_per_gpu:
                        bulk_task_id_per_gpu = 0
                        bulk_task_dev_id += 1
                        if bulk_task_dev_id == num_gpus:
                            bulk_task_id = DeviceType.USER_CHOSEN_DEVICE
                task_id += 1
    return graph
generate_serial_graph()
str parla.utility.graphs.generate_serial_graph (SerialConfig config)
Definition at line 652 of file graphs.py.
def generate_serial_graph(config: SerialConfig) -> str:
    task_config = config.task_config
    configurations = task_config.configurations
    graph = ""
    data_config_string = ""
    if config.data_pattern == DataInitType.NO_DATA:
        data_config_string = "{1 , -1}\n"
    elif config.data_pattern == DataInitType.OVERLAPPED_DATA:
        config.data_partitions = 1
        single_data_block_size = (
            config.total_data_width // config.data_partitions)
        for i in range(config.data_partitions):
            data_config_string += f"{single_data_block_size , -1}"
            if i+1 < config.data_partitions:
                data_config_string += f" | "
    elif config.data_pattern == DataInitType.INDEPENDENT_DATA:
        raise NotImplementedError("[Serial] Data patterns not implemented")
    else:
        raise ValueError(
            f"[Serial] Not supported data configuration: {config.data_pattern}")
    data_config_string += "\n"
    if task_config is None:
        raise ValueError("Task config must be specified")
    configuration_string = ""
    for device_id, task_config in configurations.items():
        last_flag = 1 if device_id == list(
            configurations.keys())[-1] else 0
        if config.fixed_placement:
            device_id = DeviceType.GPU_0
        # Othrewise, expect any cpu or any gpu.
        configuration_string += f"{{ {device_id} : {task_config.task_time}, {task_config.device_fraction}, {task_config.gil_accesses}, {task_config.gil_fraction}, {task_config.memory} }}"
        if last_flag == 0:
            configuration_string += ", "
    graph += data_config_string
    for i in range(config.steps): # height
        inout_data_index = i
        if config.data_pattern == DataInitType.OVERLAPPED_DATA:
            inout_data_index = 0
        for j in range(config.chains): # width
            # TODO(hc): for now, do not support chain
            dependency_string = ""
            dependency_limit = min(i, config.dependency_count)
            for k in range(1, dependency_limit+1):
                assert (i-k >= 0)
                dependency_string += f"{i-k, j}"
                if k < dependency_limit:
                    dependency_string += " : "
            # TODO(hc): for now, do not support chain
            graph += f"{i, 0} | {configuration_string} | {dependency_string} | : : {inout_data_index} \n"
    return graph
get_task_properties()
def parla.utility.graphs.get_task_properties (str line)
Definition at line 461 of file graphs.py.
def get_task_properties(line: str):
    message = line.split('>>')[1].strip()
    tasks = re.findall(task_filter, message)
    tprops = []
    for task in tasks:
        properties = {}
        task = task.strip('InnerTask{').strip('}').strip()
        task_properties = task.split(',')
        for prop in task_properties:
            prop_name, prop_value = prop.strip().split(':')
            properties[prop_name] = prop_value.strip()
        # If ".dm." is in the task name, ignore it since
        # this is a data movement task.
        # TODO(hc): we may need to verify data movemnt task too.
        if ".dm." in properties['name']:
            continue
        properties['name'] = convert_task_id(
            properties['name'], properties['instance'])
        tprops.append(properties)
    return tprops
References parla.utility.graphs.convert_task_id().
Referenced by parla.utility.graphs.parse_blog().
get_time()
int parla.utility.graphs.get_time (str line)
Definition at line 430 of file graphs.py.
def get_time(line: str) -> int:
    logged_time = line.split('>>')[0].strip().strip("\`").strip('[]')
    return int(logged_time)
Referenced by parla.utility.graphs.parse_blog().
parse_blog()
Tuple[Dict[TaskID, TaskTime], Dict[TaskID, List[TaskID]]] parla.utility.graphs.parse_blog (str filename = 'parla.blog')
Definition at line 487 of file graphs.py.
def parse_blog(filename: str = 'parla.blog') -> Tuple[Dict[TaskID, TaskTime], Dict[TaskID, List[TaskID]]]:
    try:
        result = subprocess.run(
            ['bread', '-s', r"-f `[%r] >> %m`", filename], stdout=subprocess.PIPE)
        output = result.stdout.decode('utf-8')
    except subprocess.CalledProcessError as e:
        raise Exception(e.output)
    output = output.splitlines()
    task_start_times = {}
    task_runahead_times = {}
    task_notify_times = {}
    task_end_times = {}
    task_assigned_times = {}
    task_start_order = []
    task_end_order = []
    task_runahead_order = []
    task_times = {}
    task_states = defaultdict(list)
    task_dependencies = {}
    final_instance_map = {}
    for line in output:
        line_type = check_log_line(line)
        if line_type == LogState.START_TASK:
            start_time = get_time(line)
            task_properties = get_task_properties(line)
            if len(task_properties) == 0:
                # If the length of the task properties is 0,
                # it implies that this task is data movement task.
                # Ignore it.
                continue
            task_properties = task_properties[0]
            task_start_times[task_properties['name']] = start_time
            task_start_order.append(task_properties['name'])
            current_name = task_properties['name']
            base_name = TaskID(current_name.taskspace,
                               current_name.task_idx,
                               0)
            if base_name in final_instance_map:
                if current_name.instance > final_instance_map[base_name].instance:
                    final_instance_map[base_name] = current_name
            else:
                # if current_name.instance > 0:
                # raise RuntimeError(
                # "Instance number is not 0 for first instance of task")
                final_instance_map[base_name] = base_name
        elif line_type == LogState.RUNAHEAD_TASK:
            runahead_time = get_time(line)
            task_properties = get_task_properties(line)
            if len(task_properties) == 0:
                # If the length of the task properties is 0,
                # it implies that this task is data movement task.
                # Ignore it.
                continue
            task_properties = task_properties[0]
            current_name = task_properties['name']
            base_name = TaskID(current_name.taskspace,
                               current_name.task_idx,
                               0)
            task_runahead_times[base_name] = runahead_time
            task_runahead_order.append(base_name)
        elif line_type == LogState.COMPLETED_TASK:
            end_time = get_time(line)
            task_properties = get_task_properties(line)
            if len(task_properties) == 0:
                # If the length of the task properties is 0,
                # it implies that this task is data movement task.
                # Ignore it.
                continue
            task_properties = task_properties[0]
            current_name = task_properties['name']
            base_name = TaskID(current_name.taskspace,
                               current_name.task_idx,
                               0)
            task_end_times[base_name] = end_time
            task_end_order.append(base_name)
        elif line_type == LogState.NOTIFY_DEPENDENTS:
            notify_time = get_time(line)
            task_properties = get_task_properties(line)
            if len(task_properties) == 0:
                # If the length of the task properties is 0,
                # it implies that this task is data movement task.
                # Ignore it.
                continue
            notifying_task = task_properties[0]
            current_name = notifying_task['name']
            current_state = notifying_task['get_state']
            instance = notifying_task['instance']
            if int(instance) > 0:
                base_name = TaskID(current_name.taskspace,
                                   current_name.task_idx,
                                   0)
                task_states[base_name] += [current_state]
            task_states[current_name] += [current_state]
        elif line_type == LogState.ASSIGNED_TASK:
            assigned_time = get_time(line)
            task_properties = get_task_properties(line)
            if len(task_properties) == 0:
                # If the length of the task properties is 0,
                # it implies that this task is data movement task.
                # Ignore it.
                continue
            task_properties = task_properties[0]
            current_name = task_properties['name']
            base_name = TaskID(current_name.taskspace,
                               current_name.task_idx,
                               0)
            task_assigned_times[base_name] = assigned_time
        elif line_type == LogState.ADDING_DEPENDENCIES:
            task_properties = get_task_properties(line)
            if len(task_properties) == 0:
                # If the length of the task properties is 0,
                # it implies that this task is data movement task.
                # Ignore it.
                continue
            current_task = task_properties[0]['name']
            current_dependencies = []
            for d in task_properties[1:]:
                dependency = d['name']
                current_dependencies.append(dependency)
            task_dependencies[current_task] = current_dependencies
    for task in task_end_times:
        assigned_t = task_assigned_times[task]
        start_t = task_start_times[task]
        # end_t = task_end_times[task]
        end_t = task_end_times[task]
        duration = end_t - start_t
        task_times[task] = TaskTime(assigned_t, start_t, end_t, duration)
    return task_times, task_dependencies, task_states
References parla.utility.graphs.check_log_line(), parla.utility.graphs.get_task_properties(), and parla.utility.graphs.get_time().
read_pgraph()
Tuple[Dict[int, DataInfo], Dict[TaskID, TaskInfo]] parla.utility.graphs.read_pgraph (str filename)
Reads a pgraph file and returns:
1. A list of the nodes in the graph
2. The initial data configuration
Definition at line 290 of file graphs.py.
def read_pgraph(filename: str) -> Tuple[Dict[int, DataInfo], Dict[TaskID, TaskInfo]]:
    """
    Reads a pgraph file and returns:
    1. A list of the nodes in the graph
    2. The initial data configuration
    """
    task_list = []
    data_config = dict()
    with open(filename, 'r') as graph_file:
        lines = graph_file.readlines()
        # Read the initial data configuration
        data_info = lines.pop(0)
        data_info = data_info.split('|')
        idx = 0
        for data in data_info:
            info = data.strip().strip("()").strip().split(",")
            size = int(info[0].strip())
            location = int(info[1].strip())
            data_config[idx] = DataInfo(idx, size, location)
            idx += 1
        # print("Data Config", data_config)
        # Read the task graph
        for line in lines:
            task = line.split("|")
            # Breaks into [task_id, task_runtime, task_dependencies, data_dependencies]
            # Process task id (can't be empty)
            ids = task[0].strip()
            ids = make_tuple(ids)
            if not isinstance(ids, tuple):
                ids = (ids,)
            if isinstance(ids[0], str) and ids[0].isalpha():
                taskspace = ids[0]
                idx = ids[1]
                if not isinstance(idx, tuple):
                    idx = (idx,)
                task_ids = TaskID(taskspace, idx, 0)
            else:
                taskspace = "T"
                task_ids = TaskID(taskspace, ids, 0)
            # Process task runtime (can't be empty)
            configurations = task[1].strip().split("},")
            task_runtime = dict()
            for config in configurations:
                config = config.strip().strip("{}").strip()
                config = config.split(":")
                targets = config[0].strip().strip("()").strip().split(",")
                targets = [int(target.strip())
                           for target in targets if target.strip() != ""]
                target = tuple(targets)
                details = config[1].strip().split(",")
                details = [extract(detail.strip()) for detail in details]
                details = TaskRuntimeInfo(*details)
                task_runtime[target] = details
            # Process task dependencies (can be empty)
            if len(task) > 2:
                dependencies = task[2].split(":")
                if (len(dependencies) > 0) and (not dependencies[0].isspace()):
                    task_dependencies = []
                    for i in range(len(dependencies)):
                        if not dependencies[i].isspace():
                            ids = dependencies[i].strip()
                            ids = make_tuple(ids)
                            if not isinstance(ids, tuple):
                                ids = (ids,)
                            if isinstance(ids[0], str) and ids[0].isalpha():
                                name, idx = ids[0], ids[1]
                                if not isinstance(idx, tuple):
                                    idx = (idx,)
                                dep_id = TaskID(name, idx, 0)
                            else:
                                dep_id = TaskID(taskspace, ids, 0)
                            task_dependencies.append(dep_id)
                else:
                    task_dependencies = []
            else:
                task_dependencies = []
            task_dependencies = task_dependencies
            # Process data dependencies (can be empty)
            if len(task) > 3:
                # Split into [read, write, read/write]
                types = task[3].split(":")
                check = [not t.isspace() for t in types]
                if any(check):
                    task_data = [[], [], []]
                    for i in range(len(types)):
                        if check[i]:
                            data = types[i].strip().split(",")
                            if not data[0].isspace():
                                task_data[i] = [0 for _ in range(len(data))]
                                for j in range(len(data)):
                                    if not data[j].isspace():
                                        task_data[i][j] = int(data[j])
                else:
                    task_data = [[], [], []]
            else:
                task_data = [[], [], []]
            task_data = TaskDataInfo(*task_data)
            task_tuple = TaskInfo(task_ids, task_runtime,
                                  task_dependencies, task_data)
            task_list.append(task_tuple)
    task_graph = convert_to_dictionary(task_list)
    return data_config, task_graph
References parla.utility.graphs.convert_to_dictionary(), and parla.utility.graphs.extract().
shuffle_tasks()
Dict[TaskID, TaskInfo] parla.utility.graphs.shuffle_tasks (Dict[TaskID, TaskInfo] tasks)
Shuffles the task graph
Definition at line 271 of file graphs.py.
def shuffle_tasks(tasks: Dict[TaskID, TaskInfo]) -> Dict[TaskID, TaskInfo]:
    """
    Shuffles the task graph
    """
    task_list = list(tasks.values())
    np.random.shuffle(task_list)
    return convert_to_dictionary(task_list)
References parla.utility.graphs.convert_to_dictionary().
Variable Documentation
__all__
list parla.utility.graphs.__all__ [private]
Initial value:
= [DeviceType, LogState, MovementType, DataInitType, TaskID, TaskRuntimeInfo,
           TaskDataInfo, TaskInfo, DataInfo, TaskTime, TimeSample, read_pgraph,
           parse_blog, TaskConfigs, RunConfig, shuffle_tasks,
           generate_independent_graph, generate_serial_graph,
           generate_reduction_scatter_graph]
Definition at line 974 of file graphs.py.
num_gpus
int parla.utility.graphs.num_gpus = 4
Definition at line 25 of file graphs.py.
task_filter
parla.utility.graphs.task_filter = re.compile(r'InnerTask\{ .*? \}')
Definition at line 257 of file graphs.py.