parla.cython.tasks Namespace Reference
Classes
class TaskState
Abstract base class for Task State.
class TaskCreated
This state specifies that a task has been created but not yet spawned.
class TaskSpawned
This state specifies that a task is ready to be mapped to a specific device set.
class TaskMapped
This state specifies that a task has been mapped to a device set, but not yet resered its resources there.
class TaskReserved
This state specifies that a task has reserved its persistent resources (e.g.
class TaskReady
This state specifies that a task is `ready` to be launched.
class TaskRunning
This state specifies that a task is executing in a stream.
class TaskRunahead
State: A task is executing in a stream but the body has completed.
class TaskCompleted
This state specifies that a task has completed execution.
class TaskException
This state specifies that a task has completed execution with an exception.
class _TaskLocals
class Task
Python Task interface.
class ComputeTask
A compute task is a task that executes a user defined Python function on a device.
class DataMovementTask
A data movement task is a task that moves data between devices.
class TaskEnvironment
A TaskEnvironment is a collection of devices or other TaskEnvironments used to coordinate and synchronize kernels in the Task body.
class TerminalEnvironment
An endpoint TaskEnvironment representing a single device.
class CPUEnvironment
class GPUEnvironment
class TaskCollection
class TaskList
class AtomicTaskList
class BackendTaskList
class TaskSpace
class AtomicTaskSpace
class BackendTaskSpace
Functions
def create_device_env (device)
Create a terminal device environment from a PyDevice.
def create_env (sources)
Create the union TaskEnvironment from a list of TaskEnvironments or PyDevices.
def parse_index (prefix, index, step, stop)
Variables
PyDevice = device.PyDevice
PyCUDADevice = device.PyCUDADevice
PyCPUDevice = device.PyCPUDevice
PyArchitecture = device.PyArchitecture
PyCUDAArchitecture = device.PyCUDAArchitecture
DeviceType = PyDeviceType
DeviceResourceRequirement = device.DeviceResourceRequirement
cpu = device_manager.cpu
TaskAwaitTasks = namedtuple(`AwaitTasks`, [`dependencies`, `value_task`])
task_locals = _TaskLocals()
output
tasks = tasks.tasks
task = tasks[i]
keys = tasks.keys()
depth
shape = None
None
start
tuple shape_flag = (shape is not None)
max_dim
dim
tuple start_flag = (start is not None)
lower_boundary
upper_boundary
istart = max(i.start, lower_boundary) if i.start is not None else lower_boundary
istop = min(i.stop, upper_boundary) if i.stop is not None else upper_boundary
istep = i.step or 1
remainder
i = i.tasks
index_list
create
task_list
new_tasks
new_index
index = index_list[i]
barrier = BackendTaskList(barrier)
dictionary _task_space_globals = {}
Function Documentation
create_device_env()
def parla.cython.tasks.create_device_env (device)
Create a terminal device environment from a PyDevice.
Parameters
device The PyDevice to create the environment from.
Definition at line 749 of file tasks.pyx.
def create_device_env(device):
    """!
    @brief Create a terminal device environment from a PyDevice.
    @param device The PyDevice to create the environment from.
    """
    if isinstance(device, PyCPUDevice):
        return CPUEnvironment(device), DeviceType.CPU
    elif isinstance(device, PyCUDADevice):
        return GPUEnvironment(device), DeviceType.CUDA
Referenced by parla.cython.tasks.create_env().
create_env()
def parla.cython.tasks.create_env (sources)
Create the union TaskEnvironment from a list of TaskEnvironments or PyDevices.
Parameters
sources The list of PyDevices (or Environments) to create the new environment from.
Definition at line 759 of file tasks.pyx.
def create_env(sources):
    """!
    @brief Create the union TaskEnvironment from a list of TaskEnvironments or PyDevices.
    @param sources The list of PyDevices (or Environments) to create the new environment from.
    """
    targets = []
    for env in sources:
        if isinstance(env, PyDevice):
            device = env
            new_env, dev_type = create_device_env(env)
            targets.append(new_env)
    if len(targets) == 1:
        return targets[0]
    else:
        return TaskEnvironment(targets)
References parla.cython.tasks.create_device_env().
Referenced by parla.cython.tasks.TaskEnvironment.__getitem__().
parse_index()
def parla.cython.tasks.parse_index (prefix, index, step, stop)
Traverse :param:`index`, update :param:`prefix` by applying :param:`step`, :param:`stop` at leaf calls.

:param prefix: the initial state
:param index: the index tuple containing subindexes
:param step: a function with 2 input arguments (current_state, subindex) which returns the next state, applied for each subindex.
:param stop: a function with 1 input argument (final_state), applied each time subindexes exhaust.
Definition at line 1420 of file tasks.pyx.
def parse_index(prefix, index, step, stop):
    """Traverse :param:`index`, update :param:`prefix` by applying :param:`step`, :param:`stop` at leaf calls.
    :param prefix: the initial state
    :param index: the index tuple containing subindexes
    :param step: a function with 2 input arguments (current_state, subindex) which returns the next state, applied for each subindex.
    :param stop: a function with 1 input argument (final_state), applied each time subindexes exhaust.
    """
    if len(index) > 0:
        i, *rest = index
        if isinstance(i, TaskCollection):
            i = i.tasks
        if isinstance(i, slice):
            for v in range(i.start or 0, i.stop, i.step or 1):
                parse_index(step(prefix, v), rest, step, stop)
        elif isinstance(i, Iterable):
            for v in i:
                parse_index(step(prefix, v), rest, step, stop)
        else:
            parse_index(step(prefix, i), rest, step, stop)
    else:
        stop(prefix)
Variable Documentation
_task_space_globals
dictionary parla.cython.tasks._task_space_globals = {} [private]
Definition at line 1585 of file tasks.pyx.
barrier
parla.cython.tasks.barrier = BackendTaskList(barrier)
Definition at line 1549 of file tasks.pyx.
cpu
parla.cython.tasks.cpu = device_manager.cpu
Definition at line 47 of file tasks.pyx.
create
parla.cython.tasks.create
Definition at line 1446 of file tasks.pyx.
depth
parla.cython.tasks.depth
Definition at line 1359 of file tasks.pyx.
DeviceResourceRequirement
parla.cython.tasks.DeviceResourceRequirement = device.DeviceResourceRequirement
Definition at line 46 of file tasks.pyx.
DeviceType
parla.cython.tasks.DeviceType = PyDeviceType
Definition at line 30 of file tasks.pyx.
dim
parla.cython.tasks.dim
Definition at line 1365 of file tasks.pyx.
i
parla.cython.tasks.i = i.tasks
Definition at line 1386 of file tasks.pyx.
index
parla.cython.tasks.index = index_list[i]
Definition at line 1454 of file tasks.pyx.
index_list
parla.cython.tasks.index_list
Definition at line 1446 of file tasks.pyx.
istart
parla.cython.tasks.istart = max(i.start, lower_boundary) if i.start is not None else lower_boundary
Definition at line 1376 of file tasks.pyx.
istep
int parla.cython.tasks.istep = i.step or 1
Definition at line 1378 of file tasks.pyx.
istop
int parla.cython.tasks.istop = min(i.stop, upper_boundary) if i.stop is not None else upper_boundary
Definition at line 1377 of file tasks.pyx.
keys
parla.cython.tasks.keys = tasks.keys()
Definition at line 1344 of file tasks.pyx.
Referenced by parla.cython.variants._VariantFunction.__repr__(), parla.common.parray.core.PArray.nbytes_at(), and parla.common.parray.coherence.Coherence.reset().
lower_boundary
parla.cython.tasks.lower_boundary
Definition at line 1373 of file tasks.pyx.
max_dim
parla.cython.tasks.max_dim
Definition at line 1364 of file tasks.pyx.
new_index
parla.cython.tasks.new_index
Definition at line 1449 of file tasks.pyx.
new_tasks
parla.cython.tasks.new_tasks
Definition at line 1448 of file tasks.pyx.
None
parla.cython.tasks.None
Definition at line 1359 of file tasks.pyx.
output
parla.cython.tasks.output
Definition at line 1331 of file tasks.pyx.
PyArchitecture
parla.cython.tasks.PyArchitecture = device.PyArchitecture
Definition at line 27 of file tasks.pyx.
PyCPUDevice
parla.cython.tasks.PyCPUDevice = device.PyCPUDevice
Definition at line 26 of file tasks.pyx.
PyCUDAArchitecture
parla.cython.tasks.PyCUDAArchitecture = device.PyCUDAArchitecture
Definition at line 28 of file tasks.pyx.
PyCUDADevice
parla.cython.tasks.PyCUDADevice = device.PyCUDADevice
Definition at line 25 of file tasks.pyx.
PyDevice
parla.cython.tasks.PyDevice = device.PyDevice
Definition at line 24 of file tasks.pyx.
remainder
parla.cython.tasks.remainder
Definition at line 1383 of file tasks.pyx.
shape
parla.cython.tasks.shape = None
Definition at line 1359 of file tasks.pyx.
shape_flag
tuple parla.cython.tasks.shape_flag = (shape is not None)
Definition at line 1362 of file tasks.pyx.
start
parla.cython.tasks.start
Definition at line 1359 of file tasks.pyx.
start_flag
tuple parla.cython.tasks.start_flag = (start is not None)
Definition at line 1371 of file tasks.pyx.
task
parla.cython.tasks.task = tasks[i]
Definition at line 1339 of file tasks.pyx.
task_list
parla.cython.tasks.task_list
Definition at line 1447 of file tasks.pyx.
task_locals
parla.cython.tasks.task_locals = _TaskLocals()
Definition at line 271 of file tasks.pyx.
TaskAwaitTasks
parla.cython.tasks.TaskAwaitTasks = namedtuple(`AwaitTasks`, [`dependencies`, `value_task`])
Definition at line 244 of file tasks.pyx.
Referenced by parla.cython.tasks.Task.__await__(), and parla.cython.tasks.TaskCollection.__await__().
tasks
parla.cython.tasks.tasks = tasks.tasks
Definition at line 1335 of file tasks.pyx.
upper_boundary
parla.cython.tasks.upper_boundary
Definition at line 1374 of file tasks.pyx.