parla.cython.scheduler Namespace Reference
Classes
class TaskBodyException
class SchedulerException
class WorkerThreadException
class _SchedulerLocals
class SchedulerContext
class ControllableThread
class WorkerThread
class Scheduler
Functions
def get_scheduler_context ()
def get_device_manager ()
def get_stream_pool ()
def _task_callback (task, body)
Variables
Task = tasks.Task
ComputeTask = tasks.ComputeTask
DataMovementTask = tasks.DataMovementTask
TaskSpace = tasks.TaskSpace
create_env = tasks.create_env
PyInnerScheduler = core.PyInnerScheduler
PyInnerWorker = core.PyInnerWorker
PyInnerTask = core.PyInnerTask
nvtx = NVTXTracer
_scheduler_locals = _SchedulerLocals()
Function Documentation
_task_callback()
def parla.cython.scheduler._task_callback (task, body) [private]
A function which forwards to a python function in the appropriate device context.
Definition at line 484 of file scheduler.pyx.
def _task_callback(task, body):
    """
    A function which forwards to a python function in the appropriate device context.
    """
    try:
        body = body
        if inspect.iscoroutinefunction(body):
            body = body()
        if inspect.iscoroutine(body):
            try:
                in_value_task = getattr(task, "value_task", None)
                in_value = in_value_task and in_value_task.result
                new_task_info = body.send(in_value)
                task.value_task = None
                if not isinstance(new_task_info, tasks.TaskAwaitTasks):
                    raise TypeError(
                        "Parla coroutine tasks must yield a TaskAwaitTasks")
                dependencies = new_task_info.dependencies
                value_task = new_task_info.value_task
                if value_task:
                    assert isinstance(value_task, Task)
                    task.value_task = value_task
                return tasks.TaskRunning(_task_callback, (body,), dependencies)
            except StopIteration as e:
                result = None
                if e.args:
                    (result,) = e.args
                return tasks.TaskRunahead(result)
        else:
            result = body()
            return tasks.TaskRunahead(result)
    finally:
        pass
get_device_manager()
def parla.cython.scheduler.get_device_manager ()
Definition at line 71 of file scheduler.pyx.
def get_device_manager():
    return get_scheduler_context().device_manager
References parla.cython.scheduler.get_scheduler_context().
get_scheduler_context()
def parla.cython.scheduler.get_scheduler_context ()
Definition at line 68 of file scheduler.pyx.
def get_scheduler_context():
    return _scheduler_locals.scheduler_context
Referenced by parla.cython.scheduler.get_device_manager(), and parla.cython.scheduler.get_stream_pool().
get_stream_pool()
def parla.cython.scheduler.get_stream_pool ()
Definition at line 74 of file scheduler.pyx.
def get_stream_pool():
    return get_scheduler_context().device_manager.stream_pool
References parla.cython.scheduler.get_scheduler_context().
Variable Documentation
_scheduler_locals
parla.cython.scheduler._scheduler_locals = _SchedulerLocals() [private]
Definition at line 66 of file scheduler.pyx.
ComputeTask
parla.cython.scheduler.ComputeTask = tasks.ComputeTask
Definition at line 30 of file scheduler.pyx.
create_env
parla.cython.scheduler.create_env = tasks.create_env
Definition at line 33 of file scheduler.pyx.
DataMovementTask
parla.cython.scheduler.DataMovementTask = tasks.DataMovementTask
Definition at line 31 of file scheduler.pyx.
nvtx
parla.cython.scheduler.nvtx = NVTXTracer
Definition at line 41 of file scheduler.pyx.
PyInnerScheduler
parla.cython.scheduler.PyInnerScheduler = core.PyInnerScheduler
Definition at line 37 of file scheduler.pyx.
PyInnerTask
parla.cython.scheduler.PyInnerTask = core.PyInnerTask
Definition at line 39 of file scheduler.pyx.
PyInnerWorker
parla.cython.scheduler.PyInnerWorker = core.PyInnerWorker
Definition at line 38 of file scheduler.pyx.
Task
parla.cython.scheduler.Task = tasks.Task
Definition at line 29 of file scheduler.pyx.
TaskSpace
parla.cython.scheduler.TaskSpace = tasks.TaskSpace
Definition at line 32 of file scheduler.pyx.