parla.common.array Namespace Reference
Classes
class ArrayType
class NumpyArray
class CupyArray
Functions
def _register_array_type (ty, ArrayType get_memory_impl)
def can_assign_from (a, b)
def get_array_module (a)
bool is_array (a)
def asnumpy (a)
def copy (destination, source)
def clone_here (source, kind=None)
def storage_size (*arrays)
Function Documentation
_register_array_type()
def parla.common.array._register_array_type (ty, ArrayType get_memory_impl) [private]
Definition at line 196 of file array.py.
def _register_array_type(ty, get_memory_impl: ArrayType):
    _array_types[ty] = get_memory_impl
_register_array_type(numpy.ndarray, NumpyArray())
asnumpy()
def parla.common.array.asnumpy (a)
Definition at line 231 of file array.py.
def asnumpy(a):
    ar = get_array_module(a)
    if hasattr(ar, "asnumpy"):
        return ar.asnumpy(a)
    else:
        return ar.asarray(a)
References parla.common.array.get_array_module().
can_assign_from()
def parla.common.array.can_assign_from (a, b)
:param a: An array.
:param b: An array.
:return: True iff `a` supports assignments from `b`.
Definition at line 206 of file array.py.
def can_assign_from(a, b):
    """
    :param a: An array.
    :param b: An array.
    :return: True iff `a` supports assignments from `b`.
    """
    return _array_types[type(a)].can_assign_from(a, b)
clone_here()
def parla.common.array.clone_here (source, kind = None)
Create a local copy of `source` stored at the current location.
:param source: The array to read from.
Definition at line 259 of file array.py.
def clone_here(source, kind=None):
    """
    Create a local copy of `source` stored at the current location.
    :param source: The array to read from.
    """
    if is_array(source):
        current_content = get_current_context()
        if current_content is None:
            raise ValueError(
                "No device context exists for the current copy. Operation is ambiguous.")
        if len(current_content.devices) != 1:
            raise ValueError(
                "Multiple devices exist for the current copy. Operation is ambiguous.")
        current_device = current_content.devices[0]
        # FIXME: Make this a property of the device
        if (current_device.architecture == DeviceType.CUDA) and CUPY_ENABLED:
            AType = CupyArray()
        else:
            AType = NumpyArray()
        target_device_id = current_device().device_id
        dst = AType.copy_from(source, target_device_id)
        return dst
    else:
        raise TypeError(
            "ArrayType required, given value of type {}".format(type(source)))
References parla.common.globals.get_current_context(), and parla.common.array.is_array().
Referenced by parla.utility.execute.create_task_lazy_data().
copy()
def parla.common.array.copy (destination, source)
Copy the contents of `source` into `destination`.
:param destination: The array to write into.
:param source: The array to read from or the scalar value to put in destination.
Definition at line 239 of file array.py.
def copy(destination, source):
    """
    Copy the contents of `source` into `destination`.
    :param destination: The array to write into.
    :param source: The array to read from or the scalar value to put in destination.
    """
    try:
        if is_array(source):
            _array_types[type(destination)].copy_into(source, destination)
        else:
            # We assume all non-array types are by-value and hence already exist in the Python interpreter
            # and don't need to be copied.
            destination[:] = source
    except ValueError as e:
        print("Error in copy: ", e)
        raise ValueError("Failed to copy ({} {} to {} {})".format(source, getattr(
            source, "shape", None),
            destination, getattr(destination, "shape", None))) from e
References parla.common.array.is_array().
get_array_module()
def parla.common.array.get_array_module (a)
:param a: A numpy-compatible array.
:return: The numpy-compatible module associated with the array class (e.g., cupy or numpy).
Definition at line 215 of file array.py.
def get_array_module(a):
    """
    :param a: A numpy-compatible array.
    :return: The numpy-compatible module associated with the array class (e.g., cupy or numpy).
    """
    return _array_types[type(a)].get_array_module(a)
Referenced by parla.common.array.asnumpy().
is_array()
bool parla.common.array.is_array (a)
:param a: A value.
:return: True if `a` is an array of some type known to parla.
Definition at line 223 of file array.py.
def is_array(a) -> bool:
    """
    :param a: A value.
    :return: True if `a` is an array of some type known to parla.
    """
    return type(a) in _array_types
Referenced by parla.common.array.clone_here(), and parla.common.array.copy().
storage_size()
def parla.common.array.storage_size (* arrays)
:return: the total size of the arrays passed as arguments.
Definition at line 294 of file array.py.
def storage_size(*arrays):
    """
    :return: the total size of the arrays passed as arguments.
    """
    return sum(a.size * a.itemsize for a in arrays)