build-job:
  stage: build
  variables:
    COMPILER: 'gcc/8.3.1'
    CUDA_ARCH: 'sm_70'
    CUDA_VER: '11.2.0'
    CUDA_PATH: '/usr/tce/packages/cuda/cuda-${CUDA_VER}'
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_DEPTH: 1
  tags:
    - lassen
    - shell
  script:
    - bash
    - module swap xl ${COMPILER}
    - cat ~/.bashrc
    - source ~/.bashrc
    - source /usr/workspace/ruys1/mambaforge/etc/profile.d/mamba.sh
    - echo "hello world!"
    - module list
    - which conda
    - which mamba
    - which python
    - mamba activate parla
    - make clean
    - CC=gcc CXX=g++ make

test-job:
  stage: test
  tags:
    - lassen
    - shell
  script:
    - bash
    - module swap xl ${COMPILER}
    - cat ~/.bashrc
    - source ~/.bashrc
    - source /usr/workspace/ruys1/mambaforge/etc/profile.d/mamba.sh
    - echo "hello world!"
    - module list
    - which conda
    - which mamba
    - which python
    - mamba activate parla
    - lalloc 1 -q pdebug pytest testing/python
