[build-system]
requires = [
    "setuptools",
    "wheel",
    "scikit-build",
    "cmake",
    "pip>=21",
    "cython<=0.29.36",
    "ninja",
    "numpy",
    "pyyaml"
]
build-backend = "setuptools.build_meta"

[project]
name = "parla"
version = "0.3.0"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["cupy>=9.2", "psutil", "pyyaml"]

[tool.ruff]
extend-ignore = ["F841", "401"]
