[build-system]
requires = [
    "setuptools",
    "wheel",
    "scikit-build",
    "cmake",
    "pip>=21",
    "cython<=0.29.36",
    "ninja",
    "numpy",
    "pyyaml"
]
build-backend = "setuptools.build_meta"

[project]
name = "parla"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["psutil", "pyyaml", "cython<=0.29.36"]
dynamic = ["version", "authors", "description"]

[project.optional-dependencies]
gpu = ["cupy>=9.2"]

[tool.ruff]
extend-ignore = ["F841", "401"]
