parla.cython.device.DeviceResource Class Reference
Public Member Functions
def __init__ (self, memory_sz=0, num_vcus=0)
def __repr__ (self)
Public Attributes
memory_sz
num_vcus
Detailed Description
Definition at line 78 of file device.pyx.
Constructor & Destructor Documentation
__init__()
def parla.cython.device.DeviceResource.__init__ (self, memory_sz = 0, num_vcus = 0)
Definition at line 79 of file device.pyx.
    def __init__(self, memory_sz = 0, num_vcus = 0):
        # This class represents a device total resource size.
        # This can also be used to specify resource requirements
        # of a task for task mapping.
        # 0 value implies that there is no constraint in a
        # resource. In the same sense, 0 value in a requirement
        # implies that it can be mapped to a device even though
        # that device does not have enough resource.
        # TODO(hc): better design? map still has a problem that
        # users should remember keys.
        self.memory_sz = memory_sz
        self.num_vcus = num_vcus
Member Function Documentation
__repr__()
def parla.cython.device.DeviceResource.__repr__ (self)
Definition at line 93 of file device.pyx.
    def __repr__(self):
        return f"DeviceResource(memory_sz={self.memory_sz}, num_vcus={self.num_vcus})"
Referenced by parla.common.globals.Storage.__str__(), parla.common.globals.LocalStack.__str__(), parla.cython.device.Stream.__str__(), and parla.cython.device.CupyStream.__str__().
Member Data Documentation
memory_sz
parla.cython.device.DeviceResource.memory_sz
Definition at line 89 of file device.pyx.
num_vcus
parla.cython.device.DeviceResource.num_vcus
Definition at line 90 of file device.pyx.
The documentation for this class was generated from the following file:
src/python/parla/cython/device.pyx