parla.cython.variants._VariantFunction Class Reference
Function wrapper that dispatches to different architecture targets.
Public Member Functions
def __init__ (self, func)
def variant (self, spec_list, override=False)
Decorator to declare a variant of this function for a specific architecture.
def get_variant (self, spec_key)
Get the variant for a given specialization key.
def __repr__ (self)
def __call__ (self, *args, **kwargs)
Call the function, dispatching to the appropriate variant.
Private Attributes
_default
_variants
Detailed Description
Function wrapper that dispatches to different architecture targets.
Specialization is only supported on the architecture level. Specifying specifications for specific devices (e.g. gpu(0))is not supported.
Definition at line 17 of file variants.pyx.
Constructor & Destructor Documentation
__init__()
def parla.cython.variants._VariantFunction.__init__ (self, func)
Definition at line 26 of file variants.pyx.
    def __init__(self, func):
        self._default = func
        self._variants = {}
        functools.update_wrapper(self, func)
Member Function Documentation
__call__()
def parla.cython.variants._VariantFunction.__call__ (self, * args, ** kwargs)
Call the function, dispatching to the appropriate variant.
Definition at line 63 of file variants.pyx.
    def __call__(self, *args, **kwargs):
        """!
        @brief Call the function, dispatching to the appropriate variant.
        """
        local_context = Locals.context
        local_devices = local_context.get_all_devices()
        if len(local_devices) == 0:
            return self._default(*args, **kwargs)
        # Construct a architecture specialization key from the local devices.
        spec_key = tuple([d.architecture for d in local_devices])
        # If a single architecture variant type, it needs a single id, not a tuple.
        spec_key = spec_key[0] if len(spec_key) == 1 else spec_key
        # Get the variant for the current specialization key.
        variant_f = self.get_variant(spec_key)
        # Call the variant.
        return variant_f(*args, **kwargs)
References parla.cython.variants._VariantFunction._default, and parla.cython.variants._VariantFunction.get_variant().
__repr__()
def parla.cython.variants._VariantFunction.__repr__ (self)
Definition at line 60 of file variants.pyx.
    def __repr__(self):
        return "{f} specialized to {targets}>".format(f=repr(self._default)[:-1], targets=tuple(self._variants.keys()))
References parla.cython.variants._VariantFunction._default, parla.cython.variants._VariantFunction._variants, and parla.cython.tasks.keys.
Referenced by parla.common.globals.Storage.__str__(), parla.common.globals.LocalStack.__str__(), parla.cython.device.Stream.__str__(), and parla.cython.device.CupyStream.__str__().
get_variant()
def parla.cython.variants._VariantFunction.get_variant (self, spec_key)
Get the variant for a given specialization key.
Definition at line 54 of file variants.pyx.
    def get_variant(self, spec_key):
        """!
        @brief Get the variant for a given specialization key.
        """
        return self._variants.get(spec_key, self._default)
    
References parla.cython.variants._VariantFunction._default, and parla.cython.variants._VariantFunction._variants.
Referenced by parla.cython.variants._VariantFunction.__call__().
variant()
def parla.cython.variants._VariantFunction.variant (self, spec_list, override = False)
Decorator to declare a variant of this function for a specific architecture.
Parameters
spec_list A list of architectures to specialize this function for. Can be a single architecture, or a list of architectures. Each architecture can be a tuple of architectures to specialize for a multidevice configuration.
override If true, allow overriding an existing variant for one of the given architectures.
Definition at line 31 of file variants.pyx.
    def variant(self, spec_list, override=False):
        """!
        @brief Decorator to declare a variant of this function for a specific architecture.
        @param spec_list A list of architectures to specialize this function for. Can be a single architecture, or a list of architectures. Each architecture can be a tuple of architectures to specialize for a multidevice configuration.
        @param override If true, allow overriding an existing variant for one of the given architectures.
        """
        if not isinstance(spec_list, list):
            spec_list = [spec_list]
        
        if any(t in self._variants for t in spec_list) and not override:
            raise VariantDefinitionError("Variant already exists for one of the given specialization targets.")
        def variant(f):
            for t in spec_list:
                assert isinstance(t, PyArchitecture)
                self._variants[t.id] = f
            return f
        
        variant.__name__ = "{}.variant".format(self._default.__name__)
        return variant
References parla.cython.variants._VariantFunction._default, and parla.cython.variants._VariantFunction._variants.
Member Data Documentation
_default
parla.cython.variants._VariantFunction._default [private]
Definition at line 27 of file variants.pyx.
Referenced by parla.cython.variants._VariantFunction.__call__(), parla.cython.variants._VariantFunction.__repr__(), parla.cython.variants._VariantFunction.get_variant(), and parla.cython.variants._VariantFunction.variant().
_variants
parla.cython.variants._VariantFunction._variants [private]
Definition at line 28 of file variants.pyx.
Referenced by parla.cython.variants._VariantFunction.__repr__(), parla.cython.variants._VariantFunction.get_variant(), and parla.cython.variants._VariantFunction.variant().
The documentation for this class was generated from the following file:
src/python/parla/cython/variants.pyx