Mapper Class Reference
Mapper phase of the scheduler.
#include <phases.hpp>
Public Member Functions
Mapper ()=delete
Mapper (InnerScheduler *scheduler, DeviceManager *devices, std::shared_ptr< MappingPolicy > policy)
void enqueue (InnerTask *task)
Enqueue a task to the phase.
void enqueue (std::vector< InnerTask * > &tasks)
Enqueue a vector of tasks to the phase.
void run (SchedulerPhase *next_phase)
Run the phase. Check tasks in the enqueued buffer, check phase condition, and move tasks to the next phase.
size_t get_count ()
Get the number of tasks enqueued (and waiting) in the phase.
size_t atomic_incr_num_mapped_tasks ()
Increase the number of the total mapped tasks to the whole devices.
size_t atomic_incr_num_mapped_tasks_device (DevID_t dev_id)
Increase the number of the tasks mapped to a device.
size_t atomic_decr_num_mapped_tasks ()
Decrease the number of the total mapped tasks to the whole devices.
size_t atomic_decr_num_mapped_tasks_device (DevID_t dev_id)
Decrease the number of the tasks mapped to a device.
const size_t atomic_load_total_num_mapped_tasks () const
Return the number of total mapped tasks to the whole devices.
const size_t atomic_load_dev_num_mapped_tasks_device (DevID_t dev_id) const
Return the number of mapped tasks to a single device.
Protected Attributes
MapperStatus status {name}
TaskQueue mappable_tasks
std::vector< InnerTask * > mapped_tasks_buffer
uint64_t dummy_dev_idx_
std::shared_ptr< MappingPolicy > policy_
std::atomic< size_t > total_num_mapped_tasks_ {0}
The total number of tasks mapped to and running on the whole devices.
std::vector< CopyableAtomic< size_t > > dev_num_mapped_tasks_
The total number of tasks mapped to and running on a single device.
Static Protected Attributes
static const std::string name {`Mapper`}
Detailed Description
Mapper phase of the scheduler.
Uses constraints to assign tasks to device sets.
Definition at line 141 of file phases.hpp.
Constructor & Destructor Documentation
Mapper() [1/2]
Mapper::Mapper () [delete]
Mapper() [2/2]
Mapper::Mapper (InnerScheduler * scheduler, DeviceManager * devices, std::shared_ptr< MappingPolicy > policy) [inline]
Definition at line 144 of file phases.hpp.
      : SchedulerPhase(scheduler, devices), dummy_dev_idx_{0}, policy_{policy} {
    dev_num_mapped_tasks_.resize(devices->get_num_devices());
  }
References Mapper(), and SchedulerPhase::SchedulerPhase().
Referenced by Mapper().
Member Function Documentation
atomic_decr_num_mapped_tasks()
size_t Mapper::atomic_decr_num_mapped_tasks () [inline]
Decrease the number of the total mapped tasks to the whole devices.
Returns
The number of the total mapped tasks
Definition at line 174 of file phases.hpp.
                                        {
    return total_num_mapped_tasks_.fetch_sub(1, std::memory_order_relaxed);
  }
atomic_decr_num_mapped_tasks_device()
size_t Mapper::atomic_decr_num_mapped_tasks_device (DevID_t dev_id) [inline]
Decrease the number of the tasks mapped to a device.
Parameters
dev_id Device global ID where a task is mapped
Returns
The number of the tasks mapped to a device
Definition at line 182 of file phases.hpp.
                                                             {
    return dev_num_mapped_tasks_[dev_id].fetch_sub(1,
                                                   std::memory_order_relaxed);
  }
atomic_incr_num_mapped_tasks()
size_t Mapper::atomic_incr_num_mapped_tasks () [inline]
Increase the number of the total mapped tasks to the whole devices.
Returns
The number of the total mapped tasks
Definition at line 158 of file phases.hpp.
                                        {
    return total_num_mapped_tasks_.fetch_add(1, std::memory_order_relaxed);
  }
atomic_incr_num_mapped_tasks_device()
size_t Mapper::atomic_incr_num_mapped_tasks_device (DevID_t dev_id) [inline]
Increase the number of the tasks mapped to a device.
Parameters
dev_id Device global ID where a task is mapped
Returns
The number of the tasks mapped to a device
Definition at line 166 of file phases.hpp.
                                                             {
    return dev_num_mapped_tasks_[dev_id].fetch_add(1,
                                                   std::memory_order_relaxed);
  }
atomic_load_dev_num_mapped_tasks_device()
const size_t Mapper::atomic_load_dev_num_mapped_tasks_device (DevID_t dev_id) const [inline]
Return the number of mapped tasks to a single device.
Parameters
dev_id Device global ID where a task is mapped
Returns
The old number of the tasks mapped to a device
Definition at line 198 of file phases.hpp.
                                                                             {
    return dev_num_mapped_tasks_[dev_id].load(std::memory_order_relaxed);
  }
atomic_load_total_num_mapped_tasks()
const size_t Mapper::atomic_load_total_num_mapped_tasks () const [inline]
Return the number of total mapped tasks to the whole devices.
Returns
The old number of total mapped tasks
Definition at line 190 of file phases.hpp.
                                                          {
    return total_num_mapped_tasks_.load(std::memory_order_relaxed);
  }
Referenced by LocalityLoadBalancingMappingPolicy::calc_score_devplacement().
enqueue() [1/2]
void Mapper::enqueue (InnerTask * task) [virtual]
Enqueue a task to the phase.
Implements SchedulerPhase.
Definition at line 16 of file phases.cpp.
{ this->mappable_tasks.push_back(task); }
Referenced by InnerScheduler::enqueue_task().
enqueue() [2/2]
void Mapper::enqueue (std::vector< InnerTask * > & tasks) [virtual]
Enqueue a vector of tasks to the phase.
Implements SchedulerPhase.
Definition at line 18 of file phases.cpp.
                                                  {
  this->mappable_tasks.push_back(tasks);
}
get_count()
size_t Mapper::get_count () [virtual]
Get the number of tasks enqueued (and waiting) in the phase.
Implements SchedulerPhase.
Definition at line 22 of file phases.cpp.
                         {
  size_t count = this->mappable_tasks.atomic_size();
  return count;
}
run()
void Mapper::run (SchedulerPhase * next_phase) [virtual]
Run the phase. Check tasks in the enqueued buffer, check phase condition, and move tasks to the next phase.
Parameters
next_phase The next phase to move tasks to.
Implements SchedulerPhase.
Definition at line 27 of file phases.cpp.
                                           {
  NVTX_RANGE("Mapper::run", NVTX_COLOR_LIGHT_GREEN)
  //std::cout << "Mapper::run" << std::endl;
  MemoryReserver *memory_reserver = dynamic_cast<MemoryReserver *>(next_phase);
  // TODO: Refactor this so its readable without as many nested conditionals
  // This is a non-critical region
  // Comment(wlr): Why is this a noncritical region?
  // Comment(lhc): Only one thread performs this function.
  // Assumptions:
  // Scheduler maps a task to a device.
  // Scheduler does not reserve any resource at this phase.
  bool has_task = true;
  has_task = this->get_count() > 0;
  while (has_task) {
    //Comment(wlr): this assumes the task is always able to be mapped.
    InnerTask *task = this->mappable_tasks.front_and_pop();
    PlacementRequirementCollections &placement_req_options =
        task->get_placement_req_options();
    std::vector<std::shared_ptr<PlacementRequirementBase>>
        placement_req_options_vec =
            placement_req_options.get_placement_req_opts_ref();
    std::vector<std::vector<std::pair<parray::InnerPArray *, AccessMode>>>
        &parray_list = task->parray_list;
    // A set of chosen devices to a task.
    Score_t best_score{-1};
    std::vector<std::shared_ptr<DeviceRequirement>> chosen_devices;
    // Iterate all placement requirements passed by users and calculate
    // scores based on a policy.
    for (std::shared_ptr<PlacementRequirementBase> base_req :
         placement_req_options_vec) {
      if (base_req->is_multidev_req()) {
        // Multi-device placement requirements.
        // std::cout << "[Multi-device requirement]\n";
        MultiDeviceRequirements *mdev_reqs =
            dynamic_cast<MultiDeviceRequirements *>(base_req.get());
        std::vector<std::shared_ptr<DeviceRequirement>> mdev_reqs_vec;
        Score_t score{0};
        bool is_req_available = policy_->calc_score_mdevplacement(
            task, mdev_reqs, *this, &mdev_reqs_vec, &score, parray_list);
        if (!is_req_available) {
          continue;
        }
        if (best_score <= score) {
          best_score = score;
          chosen_devices.swap(mdev_reqs_vec);
        }
      } else if (base_req->is_dev_req()) {
        // A single device placement requirement.
        std::shared_ptr<DeviceRequirement> dev_req =
            std::dynamic_pointer_cast<DeviceRequirement>(base_req);
        Score_t score{0};
        bool is_req_available = policy_->calc_score_devplacement(
            task, dev_req, *this, &score, parray_list[0]);
        if (!is_req_available) {
          continue;
        }
        if (best_score <= score) {
          assert(dev_req != nullptr);
          best_score = score;
          chosen_devices.clear();
          chosen_devices.emplace_back(dev_req);
        }
      } else if (base_req->is_arch_req()) {
        // A single architecture placement requirement.
        ArchitectureRequirement *arch_req =
            dynamic_cast<ArchitectureRequirement *>(base_req.get());
        std::shared_ptr<DeviceRequirement> chosen_dev_req{nullptr};
        Score_t chosen_dev_score{0};
        // std::cout << "[Mapper] Task name:" << task->get_name() << ", " << "Checking arch requirement."
        // << "\n";
        bool is_req_available = policy_->calc_score_archplacement(
            task, arch_req, *this, chosen_dev_req, &chosen_dev_score,
            parray_list[0]);
        if (!is_req_available) {
          continue;
        }
        if (best_score <= chosen_dev_score) {
          assert(chosen_dev_req != nullptr);
          best_score = chosen_dev_score;
          chosen_devices.clear();
          chosen_devices.emplace_back(chosen_dev_req);
        }
      }
    }
    if (chosen_devices.empty()) {
      // It means that none of the devices is available for this task.
      // If it is, re-enqueue the task to the mappable task queue.
      this->enqueue(task);
      //std::cout << "Task has not been mapped" << std::endl;
    } else {
      std::vector<std::vector<std::pair<parray::InnerPArray *, AccessMode>>>
          *parray_list = &(task->parray_list);
      for (size_t i = 0; i < chosen_devices.size(); ++i) {
        assert(chosen_devices[i] != nullptr);
        Device *chosen_device = chosen_devices[i]->device();
        DevID_t global_dev_id = chosen_device->get_global_id();
        task->assigned_devices.push_back(chosen_device);
        task->device_constraints.insert(
            {chosen_device->get_global_id(), chosen_devices[i]->res_req()});
        this->atomic_incr_num_mapped_tasks_device(
            chosen_device->get_global_id());
        for (size_t j = 0; j < (*parray_list)[i].size(); ++j) {
          parray::InnerPArray *parray = (*parray_list)[i][j].first;
          this->scheduler->get_parray_tracker()->reserve_parray(*parray,
                                                                chosen_device);
          parray->incr_num_active_tasks(global_dev_id);
        }
      }
#if 0
      std::cout << "[Mapper] Task name:" << task->get_name() << ", " << task
                << "\n";
      for (size_t i = 0; i < task->assigned_devices.size(); ++i) {
        std::cout << "\t [" << i << "] "
                  << task->assigned_devices[i]->get_name() << "\n";
        /*
        auto res = task->device_constraints[task->assigned_devices[i]
                                                ->get_global_id()];
        std::cout << "\t memory:" << res.get(Resource::Memory)
                  << ", vcu:" << res.get(Resource::VCU) << "\n";
        */
      }
#endif
      this->mapped_tasks_buffer.push_back(task);
      this->atomic_incr_num_mapped_tasks();
    }
    has_task = this->get_count() > 0;
  } // while there are mappable tasks
  for (InnerTask *mapped_task : this->mapped_tasks_buffer) {
    mapped_task->notify_dependents(this->enqueue_buffer, Task::MAPPED);
    this->scheduler->enqueue_tasks(this->enqueue_buffer);
    this->enqueue_buffer.clear();
    bool enqueue_flag =
        (mapped_task->num_unreserved_dependencies.fetch_sub(1) == 1);
    if (enqueue_flag) {
      mapped_task->set_status(Task::RESERVABLE);
      memory_reserver->enqueue(mapped_task);
    }
  }
  this->mapped_tasks_buffer.clear();
}
Referenced by InnerScheduler::activate().
Member Data Documentation
dev_num_mapped_tasks_
std::vector<CopyableAtomic<size_t> > Mapper::dev_num_mapped_tasks_ [protected]
The total number of tasks mapped to and running on a single device.
Definition at line 213 of file phases.hpp.
dummy_dev_idx_
uint64_t Mapper::dummy_dev_idx_ [protected]
Definition at line 207 of file phases.hpp.
mappable_tasks
TaskQueue Mapper::mappable_tasks [protected]
Definition at line 205 of file phases.hpp.
mapped_tasks_buffer
std::vector<InnerTask *> Mapper::mapped_tasks_buffer [protected]
Definition at line 206 of file phases.hpp.
name
const std::string Mapper::name {`Mapper`} [inline], [static], [protected]
Definition at line 203 of file phases.hpp.
Referenced by parla.cython.tasks.Task::__hash__(), parla.cython.tasks.Task::get_name(), parla.cython.tasks.Task::unpack_name(), and parla.cython.tasks.Task::update_name().
policy_
std::shared_ptr<MappingPolicy> Mapper::policy_ [protected]
Definition at line 209 of file phases.hpp.
status
MapperStatus Mapper::status {name} [protected]
Definition at line 204 of file phases.hpp.
Referenced by parla.cython.scheduler.WorkerThread::run().
total_num_mapped_tasks_
std::atomic<size_t> Mapper::total_num_mapped_tasks_ {0} [protected]
The total number of tasks mapped to and running on the whole devices.
Definition at line 211 of file phases.hpp.
The documentation for this class was generated from the following files:
src/c/backend/include/phases.hpp
src/c/backend/phases.cpp