TaskBarrier Class Reference
The C++ `Mirror` of Parla's Python TaskSets & Spaces They are used as barriers for the calling thread for the completion of their members.
#include <runtime.hpp>
Public Member Functions
TaskBarrier ()=default
TaskBarrier (int num_tasks)
Task::State _add_task (InnerTask *task)
void add_task (InnerTask *task)
void add_tasks (std::vector< InnerTask * > &tasks)
void set_id (int64_t id)
void wait ()
void notify ()
Public Attributes
std::mutex mtx
std::condition_variable cv
int64_t id
std::atomic< int > num_incomplete_tasks {0}
Detailed Description
The C++ `Mirror` of Parla's Python TaskSets & Spaces They are used as barriers for the calling thread for the completion of their members.
Definition at line 640 of file runtime.hpp.
Constructor & Destructor Documentation
TaskBarrier() [1/2]
TaskBarrier::TaskBarrier () [default]
TaskBarrier() [2/2]
TaskBarrier::TaskBarrier (int num_tasks) [inline]
Definition at line 655 of file runtime.hpp.
: num_incomplete_tasks(num_tasks) {}
Member Function Documentation
_add_task()
Task::State TaskBarrier::_add_task (InnerTask * task)
Definition at line 471 of file task.cpp.
                                                {
  Task::State dependent_state = task->add_dependent_space(this);
  if (dependent_state == Task::COMPLETED) {
    this->num_incomplete_tasks.fetch_sub(1, std::memory_order_relaxed);
  }
  return dependent_state;
}
add_task()
void TaskBarrier::add_task (InnerTask * task)
Definition at line 481 of file task.cpp.
                                          {
  // don't use this
  this->num_incomplete_tasks.fetch_add(1, std::memory_order_relaxed);
  this->_add_task(task);
  this->notify();
}
Referenced by InnerTaskSpace::add_task().
add_tasks()
void TaskBarrier::add_tasks (std::vector< InnerTask * > & tasks)
Definition at line 488 of file task.cpp.
                                                         {
  this->num_incomplete_tasks.fetch_add(tasks.size() + 1,
                                       std::memory_order_relaxed);
  for (auto task : tasks) {
    this->_add_task(task);
  }
  // std::cout << "TaskBarrier::add_tasks: " <<
  // this->num_incomplete_tasks.load()
  // << std::endl;
  this->notify();
}
Referenced by parla.cython.core.PyTaskBarrier::__init__().
notify()
void TaskBarrier::notify () [inline]
Definition at line 668 of file runtime.hpp.
                {
    std::unique_lock<std::mutex> lck(mtx);
    int prev = this->num_incomplete_tasks.fetch_sub(1);
    if (prev == 1) {
      cv.notify_all();
    }
  }
Referenced by InnerTaskSpace::notify().
set_id()
void TaskBarrier::set_id (int64_t id) [inline]
Definition at line 660 of file runtime.hpp.
{ this->id = id; }
wait()
void TaskBarrier::wait () [inline]
Definition at line 662 of file runtime.hpp.
              {
    // std::cout << "Barrier Wait" << std::endl;
    std::unique_lock<std::mutex> lck(mtx);
    cv.wait(lck, [this] { return num_incomplete_tasks == 0; });
  }
Referenced by InnerTaskSpace::wait().
Member Data Documentation
cv
std::condition_variable TaskBarrier::cv
Definition at line 648 of file runtime.hpp.
id
int64_t TaskBarrier::id
Definition at line 649 of file runtime.hpp.
mtx
std::mutex TaskBarrier::mtx
Definition at line 647 of file runtime.hpp.
num_incomplete_tasks
std::atomic<int> TaskBarrier::num_incomplete_tasks {0}
Definition at line 651 of file runtime.hpp.
The documentation for this class was generated from the following files:
src/c/backend/include/runtime.hpp
src/c/backend/task.cpp