parla.cython.tasks.TaskCreated Class Reference
This state specifies that a task has been created but not yet spawned.
Public Member Functions
def value (self)
def is_terminal (self)
Detailed Description
This state specifies that a task has been created but not yet spawned.
Definition at line 68 of file tasks.pyx.
Member Function Documentation
is_terminal()
def parla.cython.tasks.TaskCreated.is_terminal (self)
Reimplemented from parla.cython.tasks.TaskState.
Definition at line 78 of file tasks.pyx.
    def is_terminal(self):
        return False
Referenced by parla.cython.tasks.TaskEnvironment.streams(), and parla.cython.tasks.TaskEnvironment.synchronize().
value()
def parla.cython.tasks.TaskCreated.value (self)
Reimplemented from parla.cython.tasks.TaskState.
Definition at line 74 of file tasks.pyx.
    def value(self):
        return 0
Referenced by parla.utility.threads.Propagate.run().
The documentation for this class was generated from the following file:
src/python/parla/cython/tasks.pyx