InnerTaskSpace Class Reference
The C++ backend for the Parla TaskSpace.
#include <runtime.hpp>
Public Member Functions
InnerTaskSpace ()=default
void add_task (int64_t key, InnerTask *task)
void add_tasks (std::vector< int64_t > &keys, std::vector< InnerTask * > &tasks)
void get_tasks (std::vector< int64_t > &keys, std::vector< InnerTask * > &tasks)
void wait ()
void notify ()
Public Attributes
std::unordered_map< int64_t, InnerTask * > task_map
Detailed Description
The C++ backend for the Parla TaskSpace.
The TaskSpace is a collection of tasks that can be queried (sliced) to get a subset of tasks and synchronized on.
Definition at line 734 of file runtime.hpp.
Constructor & Destructor Documentation
InnerTaskSpace()
InnerTaskSpace::InnerTaskSpace () [default]
Member Function Documentation
add_task()
void InnerTaskSpace::add_task (int64_t key, InnerTask * task) [inline]
Definition at line 741 of file runtime.hpp.
                                              {
    task_map.insert({key, task});
    TaskBarrier::add_task(task);
  }
References TaskBarrier::add_task().
add_tasks()
void InnerTaskSpace::add_tasks (std::vector< int64_t > & keys, std::vector< InnerTask * > & tasks) [inline]
Definition at line 746 of file runtime.hpp.
                                                                          {
    for (int i = 0; i < keys.size(); i++) {
      task_map.insert({keys[i], tasks[i]});
    }
    TaskBarrier::add_tasks(tasks);
  }
Referenced by parla.cython.core.PyTaskBarrier::__init__().
get_tasks()
void InnerTaskSpace::get_tasks (std::vector< int64_t > & keys, std::vector< InnerTask * > & tasks) [inline]
Definition at line 753 of file runtime.hpp.
                                                                          {
    for (int i = 0; i < keys.size(); i++) {
      tasks.push_back(task_map[keys[i]]);
    }
  }
notify()
void InnerTaskSpace::notify () [inline]
Definition at line 761 of file runtime.hpp.
{ TaskBarrier::notify(); }
References TaskBarrier::notify().
wait()
void InnerTaskSpace::wait () [inline]
Definition at line 759 of file runtime.hpp.
{ TaskBarrier::wait(); }
References TaskBarrier::wait().
Member Data Documentation
task_map
std::unordered_map<int64_t, InnerTask *> InnerTaskSpace::task_map
Definition at line 739 of file runtime.hpp.
The documentation for this class was generated from the following file:
src/c/backend/include/runtime.hpp