InnerTask Class Reference
The C++ runtime implementation of a task.
#include <runtime.hpp>
Public Member Functions
InnerTask ()
InnerTask (long long int id, void *py_task)
InnerTask (std::string name, long long int id, void *py_task)
void set_scheduler (InnerScheduler *scheduler)
void set_name (std::string name)
const std::string & get_name () const
void set_id (long long int name)
void set_py_task (void *py_task)
void set_priority (int priority)
void queue_dependency (InnerTask *task)
TaskStatusFlags process_dependencies ()
void clear_dependencies ()
TaskState add_dependency (InnerTask *task)
TaskStatusFlags add_dependencies (std::vector< InnerTask * > &tasks, bool data_tasks=false)
TaskState add_dependent_task (InnerTask *task)
TaskState add_dependent_space (TaskBarrier *barrier)
void add_parray (parray::InnerPArray *parray, int access_mode, int dev_id)
void notify_dependents (TaskStatusList &tasks, TaskState new_state)
void notify_dependents_completed ()
bool notify_dependents_wrapper ()
TaskStatusFlags notify (TaskState dependency_state, bool is_data=false)
void reset ()
bool blocked ()
std::string get_name ()
const bool is_data_task () const
int get_num_dependencies ()
int get_num_dependents ()
int get_num_blocking_dependencies () const
int get_num_unmapped_dependencies () const
template<ResourceCategory category>
void set_num_instances ()
Set the number of instances of the task (replicates for multi-device scheduling)
template<ResourceCategory category>
int decrement_num_instances ()
Decrement the number of instances of the task (replicates for multi-device scheduling)
template<ResourceCategory category>
int get_num_instances ()
template<ResourceCategory category>
bool get_removed ()
A task is removed when one of its instances (replicates across multi-device queues) has been moved to the next phase.
template<ResourceCategory category>
void set_removed (bool waiting)
Set the removed flag for the task.
std::vector< void * > get_dependencies ()
std::vector< void * > get_dependents ()
void add_event (uintptr_t event)
void add_stream (uintptr_t stream)
void reset_events_streams ()
void synchronize_events ()
void handle_runahead_dependencies (int sync_type_int)
Dispatches to the appropriate synchronization function for runahead scheduling.
void synchronize_dependency_events ()
void wait_dependency_events ()
void * get_py_task ()
std::vector< Device * > & get_assigned_devices ()
void add_assigned_device (Device *device)
void copy_assigned_devices (const std::vector< Device * > &others)
int set_state (int state)
TaskState set_state (TaskState state)
TaskState get_state () const
TaskStatus set_status (TaskStatus status)
TaskStatus determine_status (bool spawnable, bool mappable, bool reservable, bool ready)
TaskStatus get_status () const
void set_complete ()
bool get_complete ()
void add_device_req (Device *dev_ptr, MemorySz_t mem_sz, VCU_t num_vcus)
void begin_arch_req_addition ()
void end_arch_req_addition ()
void begin_multidev_req_addition ()
void end_multidev_req_addition ()
PlacementRequirementCollections & get_placement_req_options ()
Public Attributes
long long int id = 0
std::string name = ``
int instance = 0
std::atomic< TaskState > state {TaskState::CREATED}
std::atomic< TaskStatus > status {TaskStatus::INITIAL}
InnerScheduler * scheduler = nullptr
PointerList events
SynchronizationType sync_type = SynchronizationType::NON_BLOCKING
PointerList streams
std::mutex mtx
std::atomic< int > priority {0}
void * py_task = nullptr
TaskList dependencies
TaskList dependents
SpaceList spaces
std::vector< InnerTask * > dependency_buffer = std::vector<InnerTask *>()
std::atomic< int > num_blocking_compute_dependencies {1}
std::atomic< int > num_blocking_dependencies {1}
std::atomic< int > num_unspawned_dependencies {1}
std::atomic< int > num_unmapped_dependencies {1}
std::atomic< int > num_unreserved_dependencies {1}
std::atomic< int > num_persistant_instances {1}
bool removed_reserved {false}
std::atomic< int > num_runtime_instances {1}
bool removed_runtime {false}
std::vector< Device * > assigned_devices
std::unordered_map< int, ResourcePool_t > device_constraints
std::atomic< bool > is_data {false}
std::atomic< bool > processed_data {true}
std::vector< std::vector< std::pair< parray::InnerPArray *, AccessMode > > > parray_list
Protected Types
enum ReqAdditionState { SingleDevAdd = 1
, MultiDevAdd = 3
 }
Protected Attributes
uint32_t req_addition_mode_
std::shared_ptr< ArchitectureRequirement > tmp_arch_req_
std::shared_ptr< MultiDeviceRequirements > tmp_multdev_reqs_
PlacementRequirementCollections placement_req_options_
Detailed Description
The C++ runtime implementation of a task.
Inherits metadata from the Python layer.
Definition at line 202 of file runtime.hpp.
Member Enumeration Documentation
ReqAdditionState
enum InnerTask::ReqAdditionState [protected]
Enumerator
SingleDevAdd
MultiDevAdd
Definition at line 635 of file runtime.hpp.
                        {
    SingleDevAdd = 1,
    /* SingleArchAdd == 2, */
    MultiDevAdd = 3
  };
Constructor & Destructor Documentation
InnerTask() [1/3]
InnerTask::InnerTask ()
Definition at line 13 of file task.cpp.
    : req_addition_mode_(SingleDevAdd), tmp_arch_req_(nullptr),
      tmp_multdev_reqs_(nullptr) {
  this->dependency_buffer.reserve(DEPENDENCY_BUFFER_SIZE);
  this->id = 0;
  this->py_task = nullptr;
}
References id, InnerTask(), and py_task.
Referenced by InnerTask().
InnerTask() [2/3]
InnerTask::InnerTask (long long int id, void * py_task)
Definition at line 21 of file task.cpp.
    : req_addition_mode_(SingleDevAdd) {
  this->dependency_buffer.reserve(DEPENDENCY_BUFFER_SIZE);
  this->id = id;
  this->py_task = py_task;
}
References id, InnerTask(), and py_task.
Referenced by InnerTask().
InnerTask() [3/3]
InnerTask::InnerTask (std::string name, long long int id, void * py_task)
Definition at line 28 of file task.cpp.
    : req_addition_mode_(SingleDevAdd) {
  this->dependency_buffer.reserve(DEPENDENCY_BUFFER_SIZE);
  this->name = name;
  this->id = id;
  this->py_task = py_task;
}
References id, InnerTask(), and py_task.
Referenced by InnerTask().
Member Function Documentation
add_assigned_device()
void InnerTask::add_assigned_device (Device * device)
Definition at line 377 of file task.cpp.
                                                  {
  this->assigned_devices.push_back(device);
}
add_dependencies()
TaskStatusFlags InnerTask::add_dependencies (std::vector< InnerTask * > & tasks, bool data_tasks = false)
Definition at line 120 of file task.cpp.
                                                             {
  LOG_INFO(TASK, "Adding dependencies to {}. D={}", this, tasks);
  // TODO: Change all of this to lock free.
  // Handle phase events
  if (data_tasks == false) {
    this->num_unspawned_dependencies.fetch_add(tasks.size());
    this->num_unmapped_dependencies.fetch_add(tasks.size());
    this->num_unreserved_dependencies.fetch_add(tasks.size());
    this->num_blocking_compute_dependencies.fetch_add(tasks.size());
  }
  // CHECKME: Is this still correct on the subsequent call (should be
  // tasks.size()+1 to prevent finishing while adding)
  this->num_blocking_dependencies.fetch_add(tasks.size());
  for (size_t i = 0; i < tasks.size(); i++) {
    this->add_dependency(tasks[i]);
  }
  // Decrement overcount to free this region
  bool spawnable = this->num_unspawned_dependencies.fetch_sub(1) == 1;
  bool mappable = this->num_unmapped_dependencies.fetch_sub(1) == 1;
  // Other counters are 'freed' in each phase before entering the next phase
  TaskStatusFlags status = TaskStatusFlags();
  status.spawnable = spawnable;
  status.mappable = mappable;
  // TaskStatus status =
  // this->determine_status(spawnable, mappable, reservable, ready);
  LOG_INFO(TASK, "Added dependencies to {}. Status = {}", this, status);
  return status;
  // If true, this task is ready to launch. Launching must be handled
  // Otherwise launching will be handled by another task's notify_dependents
}
add_dependency()
TaskState InnerTask::add_dependency (InnerTask * task)
Definition at line 71 of file task.cpp.
                                                   {
  // Store all added dependencies for bookkeeping
  // I cannot think of a scenario when multiple writers would be adding
  // dependencies NOTE: Please make this thread safe if we have one
  this->dependencies.push_back_unsafe(task);
  // If the task is already complete, we don't need to add it to the dependency
  bool dependency_complete = false;
  TaskState dependent_state = task->add_dependent_task(this);
  if (dependent_state >= TaskState::RUNAHEAD) {
    this->num_blocking_dependencies.fetch_sub(1);
    this->num_unspawned_dependencies.fetch_sub(1);
    this->num_unmapped_dependencies.fetch_sub(1);
    this->num_unreserved_dependencies.fetch_sub(1);
  } else if (dependent_state >= TaskState::RESERVED) {
    this->num_unspawned_dependencies.fetch_sub(1);
    this->num_unmapped_dependencies.fetch_sub(1);
    this->num_unreserved_dependencies.fetch_sub(1);
  } else if (dependent_state >= TaskState::MAPPED) {
    this->num_unspawned_dependencies.fetch_sub(1);
    this->num_unmapped_dependencies.fetch_sub(1);
  } else if (dependent_state >= TaskState::SPAWNED) {
    this->num_unspawned_dependencies.fetch_sub(1);
  }
  return dependent_state;
}
add_dependent_space()
TaskState InnerTask::add_dependent_space (TaskBarrier * barrier)
Definition at line 215 of file task.cpp.
                                                             {
  this->spaces.lock();
  TaskState state = this->get_state();
  this->spaces.push_back_unsafe(barrier);
  this->spaces.unlock();
  return state;
}
add_dependent_task()
TaskState InnerTask::add_dependent_task (InnerTask * task)
Definition at line 192 of file task.cpp.
                                                       {
  // Store all dependents for bookkeeping
  // Dependents can be written to by multiple threads calling this function
  // Dependents is read when the task is in cleanup, which can overlap with this
  // function This write needs to be thread-safe
  // NOTE: This is not a lock free implementation. I don't know how to make it
  // lock free
  // This lock and its match in notify_dependents ensures correctness,
  // explained above. A tasks "completeness" cannot change while we are
  // adding a dependent to the list This means notify dependents has not
  // run yet.
  this->dependents.lock();
  TaskState state = this->get_state(); // s1
  this->dependents.push_back_unsafe(task); // s3
  this->dependents.unlock();
  return state;
}
add_device_req()
void InnerTask::add_device_req (Device * dev_ptr, MemorySz_t mem_sz, VCU_t num_vcus)
Definition at line 413 of file task.cpp.
                                               {
  ResourcePool_t res_req;
  res_req.set(Resource::Memory, mem_sz);
  res_req.set(Resource::VCU, num_vcus);
  std::shared_ptr<DeviceRequirement> dev_req =
      std::make_shared<DeviceRequirement>(dev_ptr, res_req);
  if (req_addition_mode_ == SingleDevAdd) {
    placement_req_options_.append_placement_req_opt(std::move(dev_req));
  } else if (req_addition_mode_ % 2 == 0) { /* Architecture requirement */
    tmp_arch_req_->append_placement_req_opt(std::move(dev_req));
  } else if (req_addition_mode_ == MultiDevAdd) {
    tmp_multdev_reqs_->append_placement_req(std::move(dev_req));
  }
}
add_event()
void InnerTask::add_event (uintptr_t event) [inline]
Definition at line 496 of file runtime.hpp.
{ this->events.push_back(event); }
add_parray()
void InnerTask::add_parray (parray::InnerPArray * parray, int access_mode, int dev_id)
Definition at line 224 of file task.cpp.
                                                                        {
  AccessMode access_mode = static_cast<AccessMode>(am);
  if (access_mode != AccessMode::IN) {
    parray->get_parent_parray()->add_task(this);
  }
  this->parray_list[dev_id].emplace_back(std::make_pair(parray, access_mode));
}
add_stream()
void InnerTask::add_stream (uintptr_t stream) [inline]
Definition at line 499 of file runtime.hpp.
{ this->streams.push_back(stream); };
begin_arch_req_addition()
void InnerTask::begin_arch_req_addition ()
Definition at line 430 of file task.cpp.
                                        {
  // Setting architecture resource requirement
  // could be called within multi-device requirement
  // setup.
  ++req_addition_mode_;
  assert(tmp_arch_req_ == nullptr);
  tmp_arch_req_ = std::make_shared<ArchitectureRequirement>();
}
begin_multidev_req_addition()
void InnerTask::begin_multidev_req_addition ()
Definition at line 449 of file task.cpp.
                                            {
  assert(req_addition_mode_ == SingleDevAdd);
  assert(tmp_multdev_reqs_ == nullptr);
  tmp_multdev_reqs_ = std::make_shared<MultiDeviceRequirements>();
  req_addition_mode_ = MultiDevAdd;
}
blocked()
bool InnerTask::blocked ()
Definition at line 330 of file task.cpp.
{ return this->num_blocking_dependencies.load() > 0; }
clear_dependencies()
void InnerTask::clear_dependencies ()
Definition at line 65 of file task.cpp.
                                   {
  this->dependency_buffer.clear();
  this->dependencies.clear();
  // this->dependency_buffer.reserve(DEPENDENCY_BUFFER_SIZE);
}
copy_assigned_devices()
void InnerTask::copy_assigned_devices (const std::vector< Device * > & others)
Definition at line 373 of file task.cpp.
                                                                       {
  this->assigned_devices = others;
}
decrement_num_instances()
template<ResourceCategory category>
int InnerTask::decrement_num_instances () [inline]
Decrement the number of instances of the task (replicates for multi-device scheduling)
Template Parameters
category ResourceCategory::Persistent or ResourceCategory::Runtime to denote which phase of scheduling we are in (memory or runtime)
Definition at line 441 of file runtime.hpp.
                                                                            {
    if constexpr (category == ResourceCategory::Persistent) {
      return this->num_persistant_instances.fetch_sub(1);
    } else {
      return this->num_runtime_instances.fetch_sub(1);
    }
  };
References Persistent.
determine_status()
TaskStatus InnerTask::determine_status (bool spawnable, bool mappable, bool reservable, bool ready)
Definition at line 103 of file task.cpp.
                                                                               {
  if (new_runnable and this->processed_data) {
    return TaskStatus::RUNNABLE;
  } else if (new_runnable and !this->processed_data) {
    return TaskStatus::COMPUTE_RUNNABLE;
  } else if (new_reservable) {
    return TaskStatus::RESERVABLE;
  } else if (new_mappable) {
    return TaskStatus::MAPPABLE;
  } else if (new_spawnable) {
    return TaskStatus::SPAWNABLE;
  } else {
    return TaskStatus::INITIAL;
  }
}
end_arch_req_addition()
void InnerTask::end_arch_req_addition ()
Definition at line 439 of file task.cpp.
                                      {
  assert(req_addition_mode_ % 2 == 0);
  if (req_addition_mode_ == 4) {
    tmp_multdev_reqs_->append_placement_req(std::move(tmp_arch_req_));
  } else {
    placement_req_options_.append_placement_req_opt(std::move(tmp_arch_req_));
  }
  --req_addition_mode_;
}
end_multidev_req_addition()
void InnerTask::end_multidev_req_addition ()
Definition at line 456 of file task.cpp.
                                          {
  assert(tmp_multdev_reqs_ != nullptr);
  placement_req_options_.append_placement_req_opt(std::move(tmp_multdev_reqs_));
  req_addition_mode_ = SingleDevAdd;
}
get_assigned_devices()
std::vector< Device * > & InnerTask::get_assigned_devices ()
Definition at line 369 of file task.cpp.
                                                     {
  return this->assigned_devices;
}
get_complete()
bool InnerTask::get_complete ()
Definition at line 406 of file task.cpp.
                             {
  return this->get_state() == TaskState::COMPLETED;
}
get_dependencies()
std::vector< void * > InnerTask::get_dependencies ()
Definition at line 340 of file task.cpp.
                                              {
  std::vector<void *> dependency_list;
  this->dependencies.lock();
  for (size_t i = 0; i < this->dependencies.size_unsafe(); i++) {
    dependency_list.push_back(this->dependencies.get_unsafe(i));
  }
  this->dependencies.unlock();
  return dependency_list;
}
Referenced by parla.cython.tasks.Task::py_handle_runahead_dependencies().
get_dependents()
std::vector< void * > InnerTask::get_dependents ()
Definition at line 350 of file task.cpp.
                                            {
  std::vector<void *> dependent_list;
  this->dependents.lock();
  for (size_t i = 0; i < this->dependents.size_unsafe(); i++) {
    dependent_list.push_back(this->dependents.get_unsafe(i));
  }
  this->dependents.unlock();
  return dependent_list;
}
get_name() [1/2]
std::string InnerTask::get_name ()
Definition at line 332 of file task.cpp.
{ return this->name; }
Referenced by parla.cython.device_manager.PrintableFrozenSet::__repr__().
get_name() [2/2]
const std::string& InnerTask::get_name () const [inline]
Definition at line 307 of file runtime.hpp.
{ return this->name; };
Referenced by parla.cython.device_manager.PrintableFrozenSet::__repr__().
get_num_blocking_dependencies()
int InnerTask::get_num_blocking_dependencies () const [inline]
Definition at line 408 of file runtime.hpp.
                                                   {
    return this->num_blocking_dependencies.load();
  };
get_num_dependencies()
int InnerTask::get_num_dependencies ()
Definition at line 334 of file task.cpp.
                                    {
  return this->dependencies.atomic_size();
}
get_num_dependents()
int InnerTask::get_num_dependents ()
Definition at line 338 of file task.cpp.
{ return this->dependents.atomic_size(); }
get_num_instances()
template<ResourceCategory category>
int InnerTask::get_num_instances () [inline]
Definition at line 449 of file runtime.hpp.
                                                                      {
    if constexpr (category == ResourceCategory::Persistent) {
      return this->num_persistant_instances.load();
    } else {
      return this->num_runtime_instances.load();
    }
  };
References Persistent.
get_num_unmapped_dependencies()
int InnerTask::get_num_unmapped_dependencies () const [inline]
Definition at line 412 of file runtime.hpp.
                                                   {
    return this->num_unmapped_dependencies.load();
  };
get_placement_req_options()
PlacementRequirementCollections& InnerTask::get_placement_req_options () [inline]
Definition at line 626 of file runtime.hpp.
                                                               {
    return placement_req_options_;
  }
References placement_req_options_.
get_py_task()
void * InnerTask::get_py_task ()
Definition at line 360 of file task.cpp.
{ return this->py_task; }
get_removed()
template<ResourceCategory category>
bool InnerTask::get_removed () [inline]
A task is removed when one of its instances (replicates across multi-device queues) has been moved to the next phase.
Template Parameters
category ResourceCategory::Persistent or ResourceCategory::Runtime to denote which phase of scheduling we are in (memory or runtime)
Returns
True if the task has already been removed from the queue
Definition at line 464 of file runtime.hpp.
                                                                 {
    if constexpr (category == ResourceCategory::Persistent) {
      return this->removed_reserved;
    } else {
      return this->removed_runtime;
    }
  }
References Persistent, removed_reserved, and removed_runtime.
get_state()
TaskState InnerTask::get_state () const [inline]
Definition at line 595 of file runtime.hpp.
                              {
    const TaskState state = this->state.load();
    return state;
  }
Referenced by InnerScheduler::enqueue_task().
get_status()
TaskStatus InnerTask::get_status () const [inline]
Definition at line 609 of file runtime.hpp.
                                {
    const TaskStatus status = this->status.load();
    return status;
  }
handle_runahead_dependencies()
void InnerTask::handle_runahead_dependencies (int sync_type_int) [inline]
Dispatches to the appropriate synchronization function for runahead scheduling.
Parameters
sync_type SynchronizationType::BLOCKING or SynchronizationType::NON_BLOCKING
Definition at line 522 of file runtime.hpp.
                                                       {
    SynchronizationType sync_type =
        static_cast<SynchronizationType>(sync_type_int);
    if (sync_type == SynchronizationType::BLOCKING) {
      this->synchronize_dependency_events();
    } else if (sync_type == SynchronizationType::NON_BLOCKING) {
      this->wait_dependency_events();
    }
  }
References BLOCKING, NON_BLOCKING, synchronize_dependency_events(), and wait_dependency_events().
is_data_task()
const bool InnerTask::is_data_task () const [inline]
Definition at line 397 of file runtime.hpp.
                                  {
    return this->is_data.load(std::memory_order_relaxed);
  }
Referenced by InnerWorker::get_task(), and InnerScheduler::task_cleanup_postsync().
notify()
TaskStatusFlags InnerTask::notify (TaskState dependency_state, bool is_data = false)
Definition at line 293 of file task.cpp.
                                                                          {
  bool spawnable = false;
  bool mappable = false;
  bool reservable = false;
  bool compute_runnable = false;
  bool runnable = false;
  if (is_data) {
    if (dependency_state == TaskState::RUNAHEAD) {
      // A data task never notifies for the other stages
      runnable = (this->num_blocking_dependencies.fetch_sub(1) == 1);
    }
  } else {
    if (dependency_state == TaskState::RUNAHEAD) {
      compute_runnable =
          (this->num_blocking_compute_dependencies.fetch_sub(1) == 1);
      runnable = (this->num_blocking_dependencies.fetch_sub(1) == 1);
    } else if (dependency_state >= TaskState::RESERVED) {
      reservable = (this->num_unreserved_dependencies.fetch_sub(1) == 1);
    } else if (dependency_state >= TaskState::MAPPED) {
      mappable = (this->num_unmapped_dependencies.fetch_sub(1) == 1);
    } else if (dependency_state >= TaskState::SPAWNED) {
      spawnable = (this->num_unspawned_dependencies.fetch_sub(1) == 1);
    }
  }
  TaskStatusFlags status;
  status.spawnable = spawnable;
  status.mappable = mappable;
  status.reservable = reservable;
  status.compute_runnable = compute_runnable;
  status.runnable = runnable;
  return status;
}
notify_dependents()
void InnerTask::notify_dependents (TaskStatusList & tasks, TaskState new_state)
Definition at line 252 of file task.cpp.
                                                                             {
  LOG_INFO(TASK, "Notifying dependents of {}: {}", this, buffer);
  NVTX_RANGE("InnerTask::notify_dependents", NVTX_COLOR_MAGENTA)
  // NOTE: I changed this to queue up ready tasks instead of enqueing them one
  // at a time
  // This is possibly worse, but splits out scheduler dependency.
  // May need to change back to call scheduler.enqueue(task) here instead
  this->dependents.lock();
  // std::cout << "Notifying dependents of " << this->name << ": " <<
  // this->dependents.size_unsafe() << std::endl;
  for (size_t i = 0; i < this->dependents.size_unsafe(); i++) {
    auto task = this->dependents.get_unsafe(i);
    TaskStatusFlags status = task->notify(new_state, this->is_data.load());
    // std::cout << "Dependent Task is notified: " << task->name << std::endl;
    if (status.any()) {
      // std::cout << "Dependent Task Ready: " << task->name << std::endl;
      buffer.push_back(std::make_pair(task, status));
    }
  }
  this->set_state(new_state);
  this->dependents.unlock();
  // std::cout << "Notified dependents of " << this->name << ". Ready tasks: "
  // << buffer.size() << std::endl;
  LOG_INFO(TASK, "Notified dependents of {}. Ready tasks: {}", this, buffer);
}
notify_dependents_completed()
void InnerTask::notify_dependents_completed ()
Definition at line 232 of file task.cpp.
                                            {
  LOG_INFO(TASK, "Notifying dependents of {}.", this);
  NVTX_RANGE("InnerTask::notify_dependents", NVTX_COLOR_MAGENTA)
  this->dependents.lock();
  this->spaces.lock();
  for (size_t i = 0; i < this->spaces.size_unsafe(); i++) {
    auto space = this->spaces.get_unsafe(i);
    space->notify();
  }
  this->set_state(TaskState::COMPLETED);
  this->spaces.unlock();
  this->dependents.unlock();
  LOG_INFO(TASK, "Notified dependents of {}.", this);
}
Referenced by InnerScheduler::task_cleanup_postsync().
notify_dependents_wrapper()
bool InnerTask::notify_dependents_wrapper ()
Definition at line 287 of file task.cpp.
                                          {
  TaskStatusList buffer = TaskStatusList();
  this->notify_dependents(buffer, TaskState::MAPPED);
  return buffer.size() > 0;
}
process_dependencies()
TaskStatusFlags InnerTask::process_dependencies ()
Definition at line 57 of file task.cpp.
                                                {
  NVTX_RANGE("InnerTask::process_dependencies", NVTX_COLOR_MAGENTA)
  TaskStatusFlags status = this->add_dependencies(this->dependency_buffer);
  this->dependency_buffer.clear();
  this->dependency_buffer.reserve(DEPENDENCY_BUFFER_SIZE);
  return status;
}
Referenced by InnerScheduler::spawn_task(), and InnerScheduler::task_cleanup_postsync().
queue_dependency()
void InnerTask::queue_dependency (InnerTask * task)
Definition at line 53 of file task.cpp.
                                                {
  this->dependency_buffer.push_back(task);
}
reset()
void InnerTask::reset () [inline]
Definition at line 376 of file runtime.hpp.
               {
    // TODO(wlr): Should this be done with set_state and assert old==RUNNING?
    this->state.store(TaskState::SPAWNED);
    this->status.store(TaskStatus::INITIAL);
    this->instance++;
    this->num_blocking_compute_dependencies.store(1);
    this->num_blocking_dependencies.store(1);
    this->num_unspawned_dependencies.store(1);
    this->num_unmapped_dependencies.store(1);
    this->num_unreserved_dependencies.store(1);
    this->assigned_devices.clear();
    // this->reset_events_streams();
  }
References INITIAL, instance, and SPAWNED.
Referenced by InnerScheduler::task_cleanup_postsync().
reset_events_streams()
void InnerTask::reset_events_streams () [inline]
Definition at line 502 of file runtime.hpp.
                              {
    this->events.clear();
    this->streams.clear();
  }
set_complete()
void InnerTask::set_complete ()
Definition at line 404 of file task.cpp.
{ this->set_state(TaskState::COMPLETED); }
set_id()
void InnerTask::set_id (long long int name)
Definition at line 47 of file task.cpp.
{ this->id = id; }
set_name()
void InnerTask::set_name (std::string name)
Definition at line 42 of file task.cpp.
                                       {
  // std::cout << "Setting name to " << name << std::endl;
  this->name = name;
}
set_num_instances()
template<ResourceCategory category>
void InnerTask::set_num_instances () [inline]
Set the number of instances of the task (replicates for multi-device scheduling)
Template Parameters
category ResourceCategory::Persistent or ResourceCategory::Runtime to denote which phase of scheduling we are in.
Parameters
num_instances Number of instances of the task
This is called to set the multi-device counters for the task when enqueued into the RuntimeReserver and MemoryResever Phases. These counters track how many devices the task is waiting on to be scheduled (i.e. it has not yet reached the head of their queues)
Definition at line 427 of file runtime.hpp.
                                                                       {
    if constexpr (category == ResourceCategory::Persistent) {
      this->num_persistant_instances.store(this->assigned_devices.size());
    } else {
      this->num_runtime_instances.store(this->assigned_devices.size());
    }
  };
References Persistent.
set_priority()
void InnerTask::set_priority (int priority)
Definition at line 51 of file task.cpp.
{ this->priority = priority; }
set_py_task()
void InnerTask::set_py_task (void * py_task)
Definition at line 49 of file task.cpp.
{ this->py_task = py_task; }
set_removed()
template<ResourceCategory category>
void InnerTask::set_removed (bool waiting) [inline]
Set the removed flag for the task.
Template Parameters
category ResourceCategory::Persistent or ResourceCategory::Runtime to denote which phase of scheduling we are in (memory or runtime)
Parameters
waiting True if the task is waiting to be removed from the queue
This is called when a task is moved to the next phase of scheduling (i.e. from MemoryReserver to RuntimeReserver) to indicate that the task is no longer in the queue
Definition at line 481 of file runtime.hpp.
                                                                             {
    if constexpr (category == ResourceCategory::Persistent) {
      this->removed_reserved = waiting;
    } else {
      this->removed_runtime = waiting;
    }
  }
References Persistent, removed_reserved, and removed_runtime.
set_scheduler()
void InnerTask::set_scheduler (InnerScheduler * scheduler)
Definition at line 36 of file task.cpp.
                                                       {
  this->scheduler = scheduler;
  size_t num_devices = this->scheduler->get_device_manager()->get_num_devices();
  this->parray_list.resize(num_devices);
}
References InnerScheduler::get_device_manager(), and scheduler.
set_state() [1/2]
int InnerTask::set_state (int state)
Definition at line 362 of file task.cpp.
                                  {
  TaskState new_state = static_cast<TaskState>(state);
  TaskState old_state = this->set_state(new_state);
  int old_state_id = static_cast<int>(new_state);
  return old_state_id;
}
set_state() [2/2]
TaskState InnerTask::set_state (TaskState state)
Definition at line 381 of file task.cpp.
                                              {
  TaskState new_state = state;
  TaskState old_state;
  do {
    old_state = this->state.load();
  } while (!this->state.compare_exchange_weak(old_state, new_state));
  return old_state;
}
Referenced by InnerScheduler::spawn_task().
set_status()
TaskStatus InnerTask::set_status (TaskStatus status)
Definition at line 392 of file task.cpp.
                                                  {
  TaskStatus new_status = status;
  TaskStatus old_status;
  do {
    old_status = this->status.load();
  } while (!this->status.compare_exchange_weak(old_status, new_status));
  return old_status;
}
Referenced by InnerScheduler::enqueue_task().
synchronize_dependency_events()
void InnerTask::synchronize_dependency_events () [inline]
Definition at line 533 of file runtime.hpp.
                                       {
    size_t num_dependencies = this->dependencies.size_unsafe();
    for (size_t i = 0; i < num_dependencies; i++) {
      InnerTask *dependency = this->dependencies.at_unsafe(i);
      dependency->synchronize_events();
    }
  }
References synchronize_events().
Referenced by handle_runahead_dependencies().
synchronize_events()
void InnerTask::synchronize_events () [inline]
Definition at line 508 of file runtime.hpp.
                            {
    size_t num_events = this->events.size_unsafe();
    for (size_t i = 0; i < num_events; i++) {
      uintptr_t event_ptr = this->events.at_unsafe(i);
      event_synchronize(event_ptr);
    }
  }
Referenced by synchronize_dependency_events(), and InnerScheduler::task_cleanup().
wait_dependency_events()
void InnerTask::wait_dependency_events () [inline]
Definition at line 546 of file runtime.hpp.
                                {
    std::cout << "Setting wait triggers for dependencies of "
              << this->get_name() << std::endl;
    // For each dependency, wait on all of its events on all of our streams
    size_t num_dependencies = this->dependencies.size_unsafe();
    for (size_t i = 0; i < num_dependencies; i++) {
      InnerTask *dependency = this->dependencies.at_unsafe(i);
      auto &dependency_events = dependency->events;
      std::cout << "Waiting for event from dependency: "
                << dependency->get_name() << std::endl;
      size_t num_events = dependency_events.size_unsafe();
      for (size_t j = 0; j < num_events; j++) {
        uintptr_t event_ptr = dependency_events.at_unsafe(j);
        // Wait on the event on all of our streams
        size_t num_streams = this->streams.size_unsafe();
        for (size_t k = 0; k < num_streams; k++) {
          uintptr_t stream_ptr = this->streams.at_unsafe(k);
          event_wait(event_ptr, stream_ptr);
        }
      }
    }
  }
Referenced by handle_runahead_dependencies().
Member Data Documentation
assigned_devices
std::vector<Device *> InnerTask::assigned_devices
Definition at line 278 of file runtime.hpp.
Referenced by parla.cython.tasks.DataMovementTask::_execute_task().
dependencies
TaskList InnerTask::dependencies
Definition at line 243 of file runtime.hpp.
Referenced by parla.cython.tasks.TaskRunning::clear_dependencies().
dependency_buffer
std::vector<InnerTask *> InnerTask::dependency_buffer = std::vector<InnerTask *>()
Definition at line 252 of file runtime.hpp.
dependents
TaskList InnerTask::dependents
Definition at line 246 of file runtime.hpp.
device_constraints
std::unordered_map<int, ResourcePool_t> InnerTask::device_constraints
Definition at line 281 of file runtime.hpp.
events
PointerList InnerTask::events
Definition at line 225 of file runtime.hpp.
id
long long int InnerTask::id = 0
Definition at line 207 of file runtime.hpp.
Referenced by InnerTask().
instance
int InnerTask::instance = 0
Definition at line 213 of file runtime.hpp.
Referenced by reset().
is_data
std::atomic<bool> InnerTask::is_data {false}
Definition at line 284 of file runtime.hpp.
mtx
std::mutex InnerTask::mtx
Definition at line 234 of file runtime.hpp.
name
std::string InnerTask::name = ``
Definition at line 210 of file runtime.hpp.
Referenced by parla.cython.tasks.Task::__hash__(), parla.cython.tasks.Task::get_name(), parla.cython.tasks.Task::unpack_name(), and parla.cython.tasks.Task::update_name().
num_blocking_compute_dependencies
std::atomic<int> InnerTask::num_blocking_compute_dependencies {1}
Definition at line 255 of file runtime.hpp.
num_blocking_dependencies
std::atomic<int> InnerTask::num_blocking_dependencies {1}
Definition at line 258 of file runtime.hpp.
num_persistant_instances
std::atomic<int> InnerTask::num_persistant_instances {1}
Definition at line 270 of file runtime.hpp.
num_runtime_instances
std::atomic<int> InnerTask::num_runtime_instances {1}
Definition at line 274 of file runtime.hpp.
num_unmapped_dependencies
std::atomic<int> InnerTask::num_unmapped_dependencies {1}
Definition at line 264 of file runtime.hpp.
num_unreserved_dependencies
std::atomic<int> InnerTask::num_unreserved_dependencies {1}
Definition at line 267 of file runtime.hpp.
num_unspawned_dependencies
std::atomic<int> InnerTask::num_unspawned_dependencies {1}
Definition at line 261 of file runtime.hpp.
parray_list
std::vector<std::vector<std::pair<parray::InnerPArray *, AccessMode> > > InnerTask::parray_list
Definition at line 294 of file runtime.hpp.
placement_req_options_
PlacementRequirementCollections InnerTask::placement_req_options_ [protected]
Definition at line 644 of file runtime.hpp.
Referenced by get_placement_req_options().
priority
std::atomic<int> InnerTask::priority {0}
Definition at line 237 of file runtime.hpp.
processed_data
std::atomic<bool> InnerTask::processed_data {true}
Definition at line 288 of file runtime.hpp.
py_task
void* InnerTask::py_task = nullptr
Definition at line 240 of file runtime.hpp.
Referenced by InnerTask().
removed_reserved
bool InnerTask::removed_reserved {false}
Definition at line 271 of file runtime.hpp.
Referenced by get_removed(), and set_removed().
removed_runtime
bool InnerTask::removed_runtime {false}
Definition at line 275 of file runtime.hpp.
Referenced by get_removed(), and set_removed().
req_addition_mode_
uint32_t InnerTask::req_addition_mode_ [protected]
Definition at line 640 of file runtime.hpp.
scheduler
InnerScheduler* InnerTask::scheduler = nullptr
Definition at line 222 of file runtime.hpp.
Referenced by parla.cython.scheduler.SchedulerContext::__enter__(), parla.cython.tasks.DataMovementTask::_execute_task(), parla.cython.scheduler.WorkerThread::_initialize(), parla.cython.scheduler.WorkerThread::run(), set_scheduler(), and parla.cython.tasks.Task::set_scheduler().
spaces
SpaceList InnerTask::spaces
Definition at line 249 of file runtime.hpp.
state
std::atomic<TaskState> InnerTask::state {TaskState::CREATED}
Definition at line 216 of file runtime.hpp.
Referenced by parla.cython.tasks.Task::result(), and parla.cython.tasks.Task::run().
status
std::atomic<TaskStatus> InnerTask::status {TaskStatus::INITIAL}
Definition at line 219 of file runtime.hpp.
Referenced by parla.cython.scheduler.WorkerThread::run().
streams
PointerList InnerTask::streams
Definition at line 231 of file runtime.hpp.
Referenced by parla.cython.tasks.TaskEnvironment::stream(), parla.cython.tasks.TerminalEnvironment::write_streams_to_task(), and parla.cython.tasks.TerminalEnvironment::write_to_task().
sync_type
SynchronizationType InnerTask::sync_type = SynchronizationType::NON_BLOCKING
Definition at line 228 of file runtime.hpp.
tmp_arch_req_
std::shared_ptr<ArchitectureRequirement> InnerTask::tmp_arch_req_ [protected]
Definition at line 641 of file runtime.hpp.
tmp_multdev_reqs_
std::shared_ptr<MultiDeviceRequirements> InnerTask::tmp_multdev_reqs_ [protected]
Definition at line 642 of file runtime.hpp.
The documentation for this class was generated from the following files:
src/c/backend/include/runtime.hpp
src/c/backend/task.cpp