parla.cython.tasks.TaskException Class Reference
This state specifies that a task has completed execution with an exception.
Public Member Functions
def value (self)
def is_terminal (self)
def __init__ (self, exc=None, tb=None)
def __repr__ (self)
Public Attributes
exception
traceback
Static Private Attributes
list __slots__ = [`exception`, `traceback`]
Detailed Description
This state specifies that a task has completed execution with an exception.
Definition at line 227 of file tasks.pyx.
Constructor & Destructor Documentation
__init__()
def parla.cython.tasks.TaskException.__init__ (self, exc = None, tb = None)
Definition at line 242 of file tasks.pyx.
    def __init__(self, exc=None, tb=None):
        self.exception = exc
        self.traceback = tb
Member Function Documentation
__repr__()
def parla.cython.tasks.TaskException.__repr__ (self)
Reimplemented from parla.cython.tasks.TaskState.
Definition at line 246 of file tasks.pyx.
    def __repr__(self):
        return "TaskException({})".format(self.exception)
References parla.cython.tasks.TaskException.exception.
Referenced by parla.common.globals.Storage.__str__(), parla.common.globals.LocalStack.__str__(), parla.cython.device.Stream.__str__(), parla.cython.device.CupyStream.__str__(), and parla.cython.tasks.TaskState.__str__().
is_terminal()
def parla.cython.tasks.TaskException.is_terminal (self)
Reimplemented from parla.cython.tasks.TaskState.
Definition at line 239 of file tasks.pyx.
    def is_terminal(self):
        return True
Referenced by parla.cython.tasks.TaskEnvironment.synchronize().
value()
def parla.cython.tasks.TaskException.value (self)
Reimplemented from parla.cython.tasks.TaskState.
Definition at line 235 of file tasks.pyx.
    def value(self):
        return 8
Referenced by parla.utility.threads.Propagate.run().
Member Data Documentation
__slots__
list parla.cython.tasks.TaskException.__slots__ = [`exception`, `traceback`] [static], [private]
Definition at line 232 of file tasks.pyx.
exception
parla.cython.tasks.TaskException.exception
Definition at line 243 of file tasks.pyx.
Referenced by parla.cython.tasks.TaskException.__repr__().
traceback
parla.cython.tasks.TaskException.traceback
Definition at line 244 of file tasks.pyx.
The documentation for this class was generated from the following file:
src/python/parla/cython/tasks.pyx