InnerScheduler Class Reference
The C++ `Mirror` of Parla's Python Scheduler This class is used to create a C++ representation of a Parla Scheduler All scheduling logic should be handled by these after creation until launched by the Python callback.
#include <runtime.hpp>
Public Member Functions
InnerScheduler (DeviceManager *device_manager)
~InnerScheduler ()
void set_num_workers (int nworkers)
void set_py_scheduler (void *py_scheduler)
void set_stop_callback (stopfunc_t stop_callback)
void run ()
void stop ()
Scheduler::Status activate ()
void activate_wrapper ()
void spawn_task (InnerTask *task)
void enqueue_task (InnerTask *task, TaskStatusFlags flags)
void enqueue_tasks (TaskStatusList &tasks)
void add_worker (InnerWorker *worker)
void enqueue_worker (InnerWorker *worker)
void task_cleanup (InnerWorker *worker, InnerTask *task, int state)
void task_cleanup_presync (InnerWorker *worker, InnerTask *task, int state)
void task_cleanup_postsync (InnerWorker *worker, InnerTask *task, int state)
int get_num_active_tasks ()
void increase_num_active_tasks ()
void decrease_num_active_tasks ()
int increase_num_notified_workers ()
int decrease_num_notified_workers ()
int get_num_running_tasks ()
int get_num_ready_tasks ()
int get_num_notified_workers ()
PArrayTracker * get_parray_tracker ()
void reserve_parray (parray::InnerPArray *parray, DevID_t global_dev_id)
void release_parray (parray::InnerPArray *parray, DevID_t global_dev_id)
bool get_parray_state (DevID_t global_dev_idx, uint64_t parray_parent_id)
void spawn_wait ()
DeviceManager * get_device_manager ()
Public Attributes
bool sleep_flag = false
int sleep_time = 20
std::vector< InnerTask * > task_buffer = std::vector<InnerTask *>(10)
WorkerPool_t workers
std::atomic< int > num_active_tasks {1}
std::atomic< bool > should_run = true
Mapper * mapper
MemoryReserver * memory_reserver
RuntimeReserver * runtime_reserver
Launcher * launcher
stopfunc_t stop_callback
void * py_scheduler
Scheduler::Status status
Protected Attributes
DeviceManager * device_manager_
It manages all device instances in C++.
PArrayTracker parray_tracker_
It manages the current/planned distribution of PArrays across devices.
Detailed Description
The C++ `Mirror` of Parla's Python Scheduler This class is used to create a C++ representation of a Parla Scheduler All scheduling logic should be handled by these after creation until launched by the Python callback.
Definition at line 968 of file runtime.hpp.
Constructor & Destructor Documentation
InnerScheduler()
InnerScheduler::InnerScheduler (DeviceManager * device_manager)
Definition at line 126 of file scheduler.cpp.
    : device_manager_(device_manager), parray_tracker_(device_manager) {
  // A dummy task count is used to keep the scheduler alive.
  // NOTE: At least one task must be added to the scheduler by the main thread,
  // otherwise the runtime will finish immediately
  // this->increase_num_active_tasks();
  this->workers.set_num_workers(1);
  // Mapping policy
  std::shared_ptr<LocalityLoadBalancingMappingPolicy> mapping_policy =
      std::make_shared<LocalityLoadBalancingMappingPolicy>(
          device_manager, &this->parray_tracker_);
  // Initialize the phases
  this->mapper = new Mapper(this, device_manager, std::move(mapping_policy));
  this->memory_reserver = new MemoryReserver(this, device_manager);
  this->runtime_reserver = new RuntimeReserver(this, device_manager);
  this->launcher = new Launcher(this, device_manager);
  // this->resources = std::make_shared < ResourcePool<std::atomic<int64_t>>();
}
References device_manager_, InnerScheduler(), Launcher::Launcher(), launcher, memory_reserver, MemoryReserver::MemoryReserver(), runtime_reserver, and RuntimeReserver::RuntimeReserver().
Referenced by InnerScheduler().
 InnerScheduler()
InnerScheduler::~InnerScheduler ()
Definition at line 149 of file scheduler.cpp.
                                {
  delete this->mapper;
  delete this->memory_reserver;
  delete this->runtime_reserver;
  delete this->launcher;
}
References launcher, mapper, memory_reserver, and runtime_reserver.
Member Function Documentation
activate()
Scheduler::Status InnerScheduler::activate ()
Definition at line 186 of file scheduler.cpp.
                                         {
  // std::cout<< "Scheduler Activated" << std::endl;
  this->mapper->run(this->memory_reserver);
  this->memory_reserver->run(this->runtime_reserver);
  this->runtime_reserver->run(this->launcher);
  // LOG_TRACE(SCHEDULER, "ReadyPhase Status: {}", this->runtime_reserver);
  return this->status;
}
References launcher, mapper, memory_reserver, Mapper::run(), MemoryReserver::run(), RuntimeReserver::run(), runtime_reserver, and status.
Referenced by activate_wrapper(), and run().
activate_wrapper()
void InnerScheduler::activate_wrapper ()
Definition at line 197 of file scheduler.cpp.
{ this->activate(); }
References activate().
add_worker()
void InnerScheduler::add_worker (InnerWorker * worker)
Definition at line 235 of file scheduler.cpp.
                                                   {
  LOG_INFO(SCHEDULER, "Adding worker {} to pool", worker);
  this->workers.add_worker(worker);
}
decrease_num_active_tasks()
void InnerScheduler::decrease_num_active_tasks ()
Definition at line 338 of file scheduler.cpp.
                                               {
  int count = this->num_active_tasks.fetch_sub(1) - 1;
  // std::cout << "Decreasing num active tasks: " << count << std::endl;
  if (count == 0) {
    this->stop();
  }
}
References stop().
Referenced by task_cleanup_postsync().
decrease_num_notified_workers()
int InnerScheduler::decrease_num_notified_workers ()
Definition at line 353 of file scheduler.cpp.
                                                  {
  return this->workers.decrease_num_notified_workers();
}
Referenced by InnerWorker::get_task().
enqueue_task()
void InnerScheduler::enqueue_task (InnerTask * task, TaskStatusFlags flags)
Definition at line 209 of file scheduler.cpp.
                                                                         {
  // TODO: Change this to appropriate phase as it becomes implemented
  LOG_INFO(SCHEDULER, "Enqueing task: {}, Status: {}", task, status);
  if (status.mappable && (task->get_state() < TaskState::MAPPED)) {
    LOG_INFO(SCHEDULER, "Enqueing task: {} to mapper", task);
    task->set_status(TaskStatus::MAPPABLE);
    this->mapper->enqueue(task);
  } else if (status.reservable && (task->get_state() == TaskState::MAPPED)) {
    task->set_status(TaskStatus::RESERVABLE);
    LOG_INFO(SCHEDULER, "Enqueing task: {} to memory reserver", task);
    this->memory_reserver->enqueue(task);
  } else if (status.runnable && (task->get_state() == TaskState::RESERVED)) {
    task->set_status(TaskStatus::RUNNABLE);
    // std::cout << "ENQUEUE FROM CALLBACK" << std::endl;
    LOG_INFO(SCHEDULER, "Enqueing task: {} to runtime reserver", task);
    this->runtime_reserver->enqueue(task);
  }
}
References Mapper::enqueue(), MemoryReserver::enqueue(), RuntimeReserver::enqueue(), InnerTask::get_state(), TaskStatusFlags::mappable, MAPPABLE, MAPPED, mapper, memory_reserver, TaskStatusFlags::reservable, RESERVABLE, RESERVED, TaskStatusFlags::runnable, RUNNABLE, runtime_reserver, and InnerTask::set_status().
Referenced by spawn_task(), and task_cleanup_postsync().
enqueue_tasks()
void InnerScheduler::enqueue_tasks (TaskStatusList & tasks)
Definition at line 228 of file scheduler.cpp.
                                                        {
  // LOG_INFO(SCHEDULER, "Enqueing tasks: {}", tasks);
  for (TaskStatusPair task_status : tasks) {
    this->enqueue_task(task_status.first, task_status.second);
  }
}
enqueue_worker()
void InnerScheduler::enqueue_worker (InnerWorker * worker)
Definition at line 240 of file scheduler.cpp.
                                                       {
  LOG_INFO(SCHEDULER, "Enqueuing worker: {} is ready.", worker);
  this->workers.enqueue_worker(worker);
}
Referenced by task_cleanup_postsync().
get_device_manager()
DeviceManager* InnerScheduler::get_device_manager () [inline]
Definition at line 1111 of file runtime.hpp.
{ return this->device_manager_; }
References device_manager_.
Referenced by InnerTask::set_scheduler().
get_num_active_tasks()
int InnerScheduler::get_num_active_tasks ()
Definition at line 331 of file scheduler.cpp.
{ return this->num_active_tasks; }
get_num_notified_workers()
int InnerScheduler::get_num_notified_workers () [inline]
Definition at line 1081 of file runtime.hpp.
                                 {
    return this->workers.get_num_notified_workers();
  }
get_num_ready_tasks()
int InnerScheduler::get_num_ready_tasks ()
Definition at line 361 of file scheduler.cpp.
                                        {
  return this->runtime_reserver->get_count();
}
References RuntimeReserver::get_count(), and runtime_reserver.
get_num_running_tasks()
int InnerScheduler::get_num_running_tasks ()
Definition at line 357 of file scheduler.cpp.
                                          {
  return this->launcher->get_count();
}
References Launcher::get_count(), and launcher.
get_parray_state()
bool InnerScheduler::get_parray_state (DevID_t global_dev_idx, uint64_t parray_parent_id) [inline]
Definition at line 1102 of file runtime.hpp.
                                                                           {
    return this->parray_tracker_.get_parray_state(global_dev_idx,
                                                  parray_parent_id);
  }
get_parray_tracker()
PArrayTracker* InnerScheduler::get_parray_tracker () [inline]
Definition at line 1086 of file runtime.hpp.
{ return &(this->parray_tracker_); }
increase_num_active_tasks()
void InnerScheduler::increase_num_active_tasks ()
Definition at line 333 of file scheduler.cpp.
                                               {
  int count = this->num_active_tasks.fetch_add(1);
  // std::cout << "Increasing num active tasks: " << count + 1 << std::endl;
}
Referenced by spawn_task().
increase_num_notified_workers()
int InnerScheduler::increase_num_notified_workers ()
Definition at line 349 of file scheduler.cpp.
                                                  {
  return this->workers.increase_num_notified_workers();
}
Referenced by InnerWorker::wait().
release_parray()
void InnerScheduler::release_parray (parray::InnerPArray * parray, DevID_t global_dev_id) [inline]
Definition at line 1096 of file runtime.hpp.
                                                                        {
    Device *device =
        this->device_manager_->get_device_by_global_id(global_dev_id);
    this->parray_tracker_.release_parray(*parray, device);
  }
reserve_parray()
void InnerScheduler::reserve_parray (parray::InnerPArray * parray, DevID_t global_dev_id) [inline]
Definition at line 1089 of file runtime.hpp.
                                                                        {
    Device *device =
        this->device_manager_->get_device_by_global_id(global_dev_id);
    this->parray_tracker_.reserve_parray(*parray, device);
  }
run()
void InnerScheduler::run ()
Definition at line 168 of file scheduler.cpp.
                         {
  NVTX_RANGE("Scheduler::run", NVTX_COLOR_RED)
  unsigned long long iteration_count = 0;
  while (this->should_run.load()) {
    auto status = this->activate();
    if (this->sleep_flag) {
      std::this_thread::sleep_for(std::chrono::milliseconds(this->sleep_time));
    }
  }
}
References activate(), and sleep_flag.
set_num_workers()
void InnerScheduler::set_num_workers (int nworkers)
Definition at line 156 of file scheduler.cpp.
                                                 {
  this->workers.set_num_workers(nworkers);
}
set_py_scheduler()
void InnerScheduler::set_py_scheduler (void * py_scheduler)
Definition at line 160 of file scheduler.cpp.
                                                        {
  this->py_scheduler = py_scheduler;
}
References py_scheduler.
set_stop_callback()
void InnerScheduler::set_stop_callback (stopfunc_t stop_callback)
Definition at line 164 of file scheduler.cpp.
                                                               {
  this->stop_callback = stop_callback;
}
References stop_callback.
spawn_task()
void InnerScheduler::spawn_task (InnerTask * task)
Definition at line 199 of file scheduler.cpp.
                                               {
  LOG_INFO(SCHEDULER, "Spawning task: {}", task);
  NVTX_RANGE("Scheduler::spawn_task", NVTX_COLOR_RED)
  auto status = task->process_dependencies();
  this->increase_num_active_tasks();
  task->set_state(TaskState::SPAWNED);
  this->enqueue_task(task, status);
}
References enqueue_task(), increase_num_active_tasks(), InnerTask::process_dependencies(), InnerTask::set_state(), and SPAWNED.
spawn_wait()
void InnerScheduler::spawn_wait ()
Definition at line 365 of file scheduler.cpp.
{ this->workers.spawn_wait(); }
stop()
void InnerScheduler::stop ()
Definition at line 179 of file scheduler.cpp.
                          {
  LOG_INFO(SCHEDULER, "Stopping scheduler");
  this->should_run = false;
  launch_stop_callback(this->stop_callback, this->py_scheduler);
  LOG_INFO(SCHEDULER, "Stopped scheduler");
}
References launch_stop_callback(), py_scheduler, and stop_callback.
Referenced by decrease_num_active_tasks().
task_cleanup()
void InnerScheduler::task_cleanup (InnerWorker * worker, InnerTask * task, int state)
Definition at line 321 of file scheduler.cpp.
                                             {
  NVTX_RANGE("Scheduler::task_cleanup", NVTX_COLOR_MAGENTA)
  task_cleanup_presync(worker, task, state);
  // synchronize task enviornment
  task->synchronize_events();
  task_cleanup_postsync(worker, task, state);
}
References InnerTask::synchronize_events(), task_cleanup_postsync(), and task_cleanup_presync().
task_cleanup_postsync()
void InnerScheduler::task_cleanup_postsync (InnerWorker * worker, InnerTask * task, int state)
Definition at line 268 of file scheduler.cpp.
                                                          {
  NVTX_RANGE("Scheduler::task_cleanup_postsync", NVTX_COLOR_MAGENTA)
  TaskState state = static_cast<TaskState>(state_int);
  // std::cout << "Task Cleanup Post Sync" << std::endl;
  if (state == TaskState::RUNAHEAD) {
    this->decrease_num_active_tasks();
    task->notify_dependents_completed();
  }
  // Release all resources for this task on all devices
  for (size_t i = 0; i < task->assigned_devices.size(); ++i) {
    Device *device = task->assigned_devices[i];
    DevID_t dev_id = device->get_global_id();
    ResourcePool_t &device_pool = device->get_reserved_pool();
    ResourcePool_t &task_pool =
        task->device_constraints[device->get_global_id()];
    // TODO(wlr): This needs to be changed to not release PARRAY resources
    device_pool.increase<ResourceCategory::All>(task_pool);
    // PArrays could be evicted even during task barrier continuation.
    // However, these PArrays will be allocated and tracked
    // again after the task restarts.
    if (!task->is_data_task()) {
      for (size_t j = 0; j < task->parray_list[i].size(); ++j) {
        parray::InnerPArray *parray = task->parray_list[i][j].first;
        parray->decr_num_active_tasks(dev_id);
        // This PArray is not released from the PArray tracker here,
        // but when it is EVICTED, it will check the number of referneces
        // and will be released if that is 0.
      }
    }
    this->mapper->atomic_decr_num_mapped_tasks_device(dev_id);
  }
  // Clear all assigned streams from the task
  task->streams.clear();
  this->launcher->num_running_tasks--;
  worker->remove_task();
  if (state == TaskState::RUNNING) {
    task->reset();
    auto status = task->process_dependencies();
    this->enqueue_task(task, status);
  }
  this->enqueue_worker(worker);
}
References All, decrease_num_active_tasks(), enqueue_task(), enqueue_worker(), Device::get_reserved_pool(), InnerTask::is_data_task(), launcher, InnerTask::notify_dependents_completed(), InnerTask::process_dependencies(), InnerWorker::remove_task(), InnerTask::reset(), RUNAHEAD, and RUNNING.
Referenced by task_cleanup().
task_cleanup_presync()
void InnerScheduler::task_cleanup_presync (InnerWorker * worker, InnerTask * task, int state)
Definition at line 245 of file scheduler.cpp.
                                                         {
  NVTX_RANGE("Scheduler::task_cleanup_presync", NVTX_COLOR_MAGENTA)
  LOG_INFO(WORKER, "Cleaning up: {} on {}", task, worker);
  TaskState state = static_cast<TaskState>(state_int);
  // std::cout << "CLEANUP PRE SYNC: " << state << " " << Task::RUNAHEAD
  // << std::endl;
  // std::cout << "Task state: " << state << std::endl;
  if (state == TaskState::RUNAHEAD) {
    // Notify dependents that they can be scheduled
    auto &enqueue_buffer = worker->enqueue_buffer;
    task->notify_dependents(enqueue_buffer, TaskState::RUNAHEAD);
    if (enqueue_buffer.size() > 0) {
      this->enqueue_tasks(enqueue_buffer);
      enqueue_buffer.clear();
    }
  }
}
References RUNAHEAD.
Referenced by task_cleanup().
Member Data Documentation
device_manager_
DeviceManager* InnerScheduler::device_manager_ [protected]
It manages all device instances in C++.
This is destructed by the Cython scheduler.
Definition at line 1116 of file runtime.hpp.
Referenced by get_device_manager(), and InnerScheduler().
launcher
Launcher* InnerScheduler::launcher
Definition at line 997 of file runtime.hpp.
Referenced by activate(), get_num_running_tasks(), InnerScheduler(), task_cleanup_postsync(), and ~InnerScheduler().
mapper
Mapper* InnerScheduler::mapper
Definition at line 990 of file runtime.hpp.
Referenced by activate(), enqueue_task(), and ~InnerScheduler().
memory_reserver
MemoryReserver* InnerScheduler::memory_reserver
Definition at line 993 of file runtime.hpp.
Referenced by activate(), enqueue_task(), InnerScheduler(), and ~InnerScheduler().
num_active_tasks
std::atomic<int> InnerScheduler::num_active_tasks {1}
Definition at line 984 of file runtime.hpp.
parray_tracker_
PArrayTracker InnerScheduler::parray_tracker_ [protected]
It manages the current/planned distribution of PArrays across devices.
Parla task mapping policy considers locality of PArrays through this.
Definition at line 1120 of file runtime.hpp.
py_scheduler
void* InnerScheduler::py_scheduler
Definition at line 1007 of file runtime.hpp.
Referenced by set_py_scheduler(), and stop().
runtime_reserver
RuntimeReserver* InnerScheduler::runtime_reserver
Definition at line 994 of file runtime.hpp.
Referenced by activate(), enqueue_task(), get_num_ready_tasks(), InnerScheduler(), and ~InnerScheduler().
should_run
std::atomic<bool> InnerScheduler::should_run = true
Definition at line 987 of file runtime.hpp.
sleep_flag
bool InnerScheduler::sleep_flag = false
Definition at line 972 of file runtime.hpp.
Referenced by run().
sleep_time
int InnerScheduler::sleep_time = 20
Definition at line 975 of file runtime.hpp.
status
Scheduler::Status InnerScheduler::status
Definition at line 1010 of file runtime.hpp.
Referenced by activate(), and parla.cython.scheduler.WorkerThread::run().
stop_callback
stopfunc_t InnerScheduler::stop_callback
Definition at line 1004 of file runtime.hpp.
Referenced by set_stop_callback(), and stop().
task_buffer
std::vector<InnerTask *> InnerScheduler::task_buffer = std::vector<InnerTask *>(10)
Definition at line 978 of file runtime.hpp.
workers
WorkerPool_t InnerScheduler::workers
Definition at line 981 of file runtime.hpp.
The documentation for this class was generated from the following files:
src/c/backend/include/runtime.hpp
src/c/backend/scheduler.cpp