parla.cython.tasks.GPUEnvironment Class Reference
Public Member Functions
def __init__ (self, device, blocking=False)
def __repr__ (self)
def __enter__ (self)
def enter_without_context (self)
def __exit__ (self, exc_type, exc_val, exc_tb)
def exit_without_context (self, exc_type, exc_val, exc_tb)
def finalize (self)
def return_streams (self)
Public Attributes
active_stream
Detailed Description
Definition at line 1307 of file tasks.pyx.
Constructor & Destructor Documentation
__init__()
def parla.cython.tasks.GPUEnvironment.__init__ (self, device, blocking = False)
Reimplemented from parla.cython.tasks.TerminalEnvironment.
Definition at line 1309 of file tasks.pyx.
    def __init__(self, device, blocking=False):
        super(GPUEnvironment, self).__init__(device, blocking=blocking)
        stream_pool = get_stream_pool()
        stream = stream_pool.get_stream(device=device)
        self.stream_list.append(stream)
        self.event_dict['default'] = stream.create_event()
References parla.cython.tasks.TaskEnvironment.event_dict, parla.common.globals.get_stream_pool(), and parla.cython.tasks.TaskEnvironment.stream_list.
Member Function Documentation
__enter__()
def parla.cython.tasks.GPUEnvironment.__enter__ (self)
Reimplemented from parla.cython.tasks.TaskEnvironment.
Definition at line 1323 of file tasks.pyx.
    def __enter__(self):
        #print("Entering GPU Environment: ", self, flush=True)
        Locals.push_context(self)
        self.active_stream = self.stream_list[0]
        ret_stream = self.active_stream.__enter__()
        return self
Referenced by parla.cython.tasks.GPUEnvironment.enter_without_context().
__exit__()
def parla.cython.tasks.GPUEnvironment.__exit__ (self, exc_type, exc_val, exc_tb)
Reimplemented from parla.cython.tasks.TaskEnvironment.
Definition at line 1336 of file tasks.pyx.
    def __exit__(self, exc_type, exc_val, exc_tb):
        #print("Exiting GPU Environment: ", self, flush=True)
        ret = False
        self.active_stream.__exit__(exc_type, exc_val, exc_tb)
        Locals.pop_context()
        return ret
References parla.cython.tasks.GPUEnvironment.active_stream.
Referenced by parla.cython.tasks.GPUEnvironment.exit_without_context().
__repr__()
def parla.cython.tasks.GPUEnvironment.__repr__ (self)
Reimplemented from parla.cython.tasks.TerminalEnvironment.
Definition at line 1319 of file tasks.pyx.
    def __repr__(self):
        return f"GPUEnvironment({self._device})"
Referenced by parla.common.globals.Storage.__str__(), parla.common.globals.LocalStack.__str__(), parla.cython.device.Stream.__str__(), parla.cython.device.CupyStream.__str__(), and parla.cython.tasks.TaskState.__str__().
enter_without_context()
def parla.cython.tasks.GPUEnvironment.enter_without_context (self)
Reimplemented from parla.cython.tasks.TaskEnvironment.
Definition at line 1330 of file tasks.pyx.
    def enter_without_context(self):
        self.active_stream = self.stream_list[0]
        ret_stream = self.active_stream.__enter__()
        return self
References parla.cython.tasks.GPUEnvironment.__enter__(), parla.cython.tasks.GPUEnvironment.active_stream, and parla.cython.tasks.TaskEnvironment.stream_list.
exit_without_context()
def parla.cython.tasks.GPUEnvironment.exit_without_context (self, exc_type, exc_val, exc_tb)
Reimplemented from parla.cython.tasks.TaskEnvironment.
Definition at line 1343 of file tasks.pyx.
    def exit_without_context(self, exc_type, exc_val, exc_tb):
        ret = False
        self.active_stream.__exit__(exc_type, exc_val, exc_tb)
        return ret
References parla.cython.tasks.GPUEnvironment.__exit__(), and parla.cython.tasks.GPUEnvironment.active_stream.
finalize()
def parla.cython.tasks.GPUEnvironment.finalize (self)
Reimplemented from parla.cython.tasks.TaskEnvironment.
Definition at line 1348 of file tasks.pyx.
    def finalize(self):
        stream_pool = get_stream_pool()
        for stream in self.stream_list:
            stream.synchronize()
            stream_pool.return_stream(stream)
References parla.common.globals.get_stream_pool(), and parla.cython.tasks.TaskEnvironment.stream_list.
return_streams()
def parla.cython.tasks.GPUEnvironment.return_streams (self)
Reimplemented from parla.cython.tasks.TaskEnvironment.
Definition at line 1354 of file tasks.pyx.
    def return_streams(self):
        stream_pool = get_stream_pool()
        for stream in self.stream_list:
            stream_pool.return_stream(stream)
References parla.common.globals.get_stream_pool(), and parla.cython.tasks.TaskEnvironment.stream_list.
Member Data Documentation
active_stream
parla.cython.tasks.GPUEnvironment.active_stream
Definition at line 1326 of file tasks.pyx.
Referenced by parla.cython.tasks.GPUEnvironment.__exit__(), parla.cython.tasks.GPUEnvironment.enter_without_context(), and parla.cython.tasks.GPUEnvironment.exit_without_context().
The documentation for this class was generated from the following file:
src/python/parla/cython/tasks.pyx