parla.common.array.ArrayType Class Reference
Public Member Functions
def can_assign_from (self, src, dst)
def get_array_module (self, src)
def copy_from (self, src, int target_device_id)
def copy_into (self, src, dst)
Detailed Description
Definition at line 23 of file array.py.
Member Function Documentation
can_assign_from()
def parla.common.array.ArrayType.can_assign_from (self, src, dst)
:param a: An array of self's type.
:param b: An array of any type.
:return: True iff `a` supports assignments from `b`.
Reimplemented in parla.common.array.CupyArray, and parla.common.array.NumpyArray.
Definition at line 26 of file array.py.
    def can_assign_from(self, src, dst):
        """
        :param a: An array of self's type.
        :param b: An array of any type.
        :return: True iff `a` supports assignments from `b`.
        """
        raise NotImplementedError(
            "can_assign_from not implemented for type {}".format(type(self).__name__))
Referenced by parla.common.array.NumpyArray.copy_into(), and parla.common.array.CupyArray.copy_into().
copy_from()
def parla.common.array.ArrayType.copy_from (self, src, int target_device_id)
:param a: An array of some type.
:return: A copy of `a` of this type
Reimplemented in parla.common.array.CupyArray, and parla.common.array.NumpyArray.
Definition at line 45 of file array.py.
    def copy_from(self, src, target_device_id: int):
        """
        :param a: An array of some type.
        :return: A copy of `a` of this type
        """
        raise NotImplementedError(
            "copy_from not implemented for type {}".format(type(self).__name__))
Referenced by parla.common.array.NumpyArray.copy_into(), and parla.common.array.CupyArray.copy_into().
copy_into()
def parla.common.array.ArrayType.copy_into (self, src, dst)
:param src: An array of some type.
:param dst: An array of this type.
:return: A copy of `src` into `dst`.
Reimplemented in parla.common.array.CupyArray, and parla.common.array.NumpyArray.
Definition at line 54 of file array.py.
    def copy_into(self, src, dst):
        """
        :param src: An array of some type.
        :param dst: An array of this type.
        :return: A copy of `src` into `dst`.
        """
        raise NotImplementedError(
            "copy_into not implemented for type {}".format(type(self).__name__))
get_array_module()
def parla.common.array.ArrayType.get_array_module (self, src)
:param a: An array of self's type.
:return: The `numpy` compatible module for the array `a`.
Reimplemented in parla.common.array.CupyArray, and parla.common.array.NumpyArray.
Definition at line 36 of file array.py.
    def get_array_module(self, src):
        """
        :param a: An array of self's type.
        :return: The `numpy` compatible module for the array `a`.
        """
        raise NotImplementedError(
            "get_array_module not implemented for type {}".format(type(self).__name__))
The documentation for this class was generated from the following file:
src/python/parla/common/array.py