parla.utility.execute Namespace Reference
Classes
class GPUInfo
class GraphContext
Functions
def make_parrays (data_list)
def estimate_frequency (n_samples=10, ticks=1900000000)
def get_placement_set_from (ps_str_set, num_gpus)
List[np.ndarray] generate_data (Dict[int, DataInfo] data_config, float data_scale, data_movement_type)
def synthetic_kernel (int total_time, Union[Fraction, float] gil_fraction, int gil_accesses, RunConfig config)
def synthetic_kernel_gpu (int total_time, Union[Fraction, float] gil_fraction, int gil_accesses, RunConfig config)
def create_task_no_data (task, taskspaces, config, data_list=None)
def create_task_eager_data (task, taskspaces, config=None, data_list=None)
def create_task_lazy_data (task, taskspaces, config=None, data_list=None)
def execute_tasks (taskspaces, Dict[TaskID, TaskInfo] tasks, RunConfig run_config, data_list=None)
def execute_graph (Dict[int, DataInfo] data_config, Dict[TaskID, TaskInfo] tasks, RunConfig run_config, List[TimeSample] timing)
TimeSample run (Dict[TaskID, TaskInfo] tasks, Dict[int, DataInfo] data_config=None, RunConfig run_config=None)
bool verify_order (Dict[TaskID, TaskTime] log_times, Dict[TaskID, List[TaskID]] truth_graph)
def verify_dependencies (Dict[TaskID, List[TaskID]] log_graph, Dict[TaskID, List[TaskID]] truth_graph)
bool verify_complete (Dict[TaskID, List[TaskID]] log_graph, Dict[TaskID, List[TaskID]] truth_graph)
bool verify_time (Dict[TaskID, TaskTime] log_times, Dict[TaskID, List[TaskID]] truth_graph, float factor=2.0)
def verify_ntasks (Dict[TaskID, TaskTime] log_times, Dict[TaskID, List[TaskID]] truth_graph)
bool verify_states (log_states)
def timeout (seconds_before_timeout)
Variables
PArray = parray.core.PArray
_GPUInfo = GPUInfo()
list __all__
Function Documentation
create_task_eager_data()
def parla.utility.execute.create_task_eager_data (task, taskspaces, config = None, data_list = None)
Definition at line 329 of file execute.py.
def create_task_eager_data(task, taskspaces, config=None, data_list=None):
    try:
        # Task ID
        task_idx = task.task_id.task_idx
        taskspace = taskspaces[task.task_id.taskspace]
        # Dependency Info
        dependencies = [taskspaces[dep.taskspace][dep.task_idx]
                        for dep in task.task_dependencies]
        # Valid Placement Set
        num_gpus = config.num_gpus
        placement_key = task.task_runtime.keys()
        placement_set_str = list(placement_key)
        placement_set = get_placement_set_from(placement_set_str, num_gpus)
        # In/out/inout data information
        # read: list, write: list, read_write: list
        data_information = task.data_dependencies
        read_data_list = data_information.read
        write_data_list = data_information.write
        rw_data_list = data_information.read_write
        # Remove duplicated data blocks between in/out and inout
        if len(read_data_list) > 0 and len(rw_data_list) > 0:
            read_data_list = list(
                set(read_data_list).difference(set(rw_data_list)))
        if len(write_data_list) > 0 and len(rw_data_list) > 0:
            write_data_list = list(
                set(write_data_list).difference(set(rw_data_list)))
        """
        print("RW data list:", rw_data_list)
        print("R data list:", read_data_list)
        print("W data list:", write_data_list)
        print("Data list:", data_list)
        """
        # Construct data blocks.
        INOUT = [] if len(rw_data_list) == 0 else [
            (data_list[d], 0) for d in rw_data_list]
        IN = [] if len(read_data_list) == 0 else [(data_list[d], 0)
                                                  for d in read_data_list]
        OUT = [] if len(write_data_list) == 0 else [(data_list[d], 0)
                                                    for d in write_data_list]
        # TODO: This needs rework with Device support
        # TODO(hc): This assumes that this task is a single task
        # and does not have multiple placement options.
        runtime_info = task.task_runtime[placement_set_str[0]]
        # Task Constraints
        device_fraction = runtime_info.device_fraction
        if config.device_fraction is not None:
            device_fraction = config.device_fraction
        # Task Work
        total_time = runtime_info.task_time
        gil_accesses = runtime_info.gil_accesses
        gil_fraction = runtime_info.gil_fraction
        if config.task_time is not None:
            total_time = config.task_time
        if config.gil_accesses is not None:
            gil_accesses = config.gil_accesses
        if config.gil_fraction is not None:
            gil_fraction = config.gil_fraction
        # print("Eager data in:", IN, " out:", OUT, " inout:", INOUT, flush=True)
        """
        print("task idx:", task_idx, " dependencies:", dependencies, " vcu:", device_fraction,
            " placement:", placement_set)
        """
        # TODO(hc): Add data checking.
        @spawn(taskspace[task_idx], dependencies=dependencies, vcus=device_fraction, placement=[placement_set], input=IN, output=OUT, inout=INOUT)
        async def task_func():
            if config.verbose:
                print(f"+{task.task_id} Running", flush=True)
            elapsed = synthetic_kernel(total_time, gil_fraction,
                                       gil_accesses, config=config)
            if config.verbose:
                print(f"-{task.task_id} Finished: {elapsed} seconds", flush=True)
    except Exception as e:
        print(f"Failed creating Task {task.task_id}: {e}", flush=True)
    finally:
        return
References parla.utility.execute.get_placement_set_from(), and parla.utility.execute.synthetic_kernel().
Referenced by parla.utility.execute.execute_tasks().
create_task_lazy_data()
def parla.utility.execute.create_task_lazy_data (task, taskspaces, config = None, data_list = None)
Definition at line 424 of file execute.py.
def create_task_lazy_data(task, taskspaces, config=None, data_list=None):
    try:
        # Task ID
        task_idx = task.task_id.task_idx
        taskspace = taskspaces[task.task_id.taskspace]
        # Dependency Info
        dependencies = [taskspaces[dep.taskspace][dep.task_idx]
                        for dep in task.task_dependencies]
        # Valid Placement Set
        num_gpus = config.num_gpus
        placement_key = task.task_runtime.keys()
        placement_set_str = list(placement_key)
        placement_set = get_placement_set_from(placement_set_str, num_gpus)
        # In/out/inout data information
        # read: list, write: list, read_write: list
        data_information = task.data_dependencies
        read_data_list = data_information.read
        write_data_list = data_information.write
        rw_data_list = data_information.read_write
        # Remove duplicated data blocks between in/out and inout
        if len(read_data_list) > 0 and len(rw_data_list) > 0:
            read_data_list = list(
                set(read_data_list).difference(set(rw_data_list)))
        if len(write_data_list) > 0 and len(rw_data_list) > 0:
            write_data_list = list(
                set(write_data_list).difference(set(rw_data_list)))
        """
        print("RW data list:", rw_data_list)
        print("R data list:", read_data_list)
        print("W data list:", write_data_list)
        print("Data list:", data_list)
        """
        # TODO: This needs rework with Device support
        # TODO(hc): This assumes that this task is a single task
        # and does not have multiple placement options.
        runtime_info = task.task_runtime[placement_set_str[0]]
        # Task Constraints
        device_fraction = runtime_info.device_fraction
        if config.device_fraction is not None:
            device_fraction = config.device_fraction
        # Task Work
        total_time = runtime_info.task_time
        gil_accesses = runtime_info.gil_accesses
        gil_fraction = runtime_info.gil_fraction
        if config.task_time is not None:
            total_time = config.task_time
        if config.gil_accesses is not None:
            gil_accesses = config.gil_accesses
        if config.gil_fraction is not None:
            gil_fraction = config.gil_fraction
        print("task idx:", task_idx, " dependencies:", dependencies, " vcu:", device_fraction,
              " placement:", placement_set)
        @spawn(taskspace[task_idx], dependencies=dependencies, vcus=device_fraction, placement=[placement_set])
        async def task_func():
            if config.verbose:
                print(f"+{task.task_id} Running", flush=True)
            local_data = dict()
            for d in itertools.chain(read_data_list, rw_data_list):
                data = data_list[d]
                where = -1 if isinstance(data, np.ndarray) else data.device.id
                local_data[d] = clone_here(data)
                old = None
                if config.do_check:
                    old = np.copy(data[0, 1])
                    local_data[d][0, 1] = -old
                if config.verbose:
                    print(
                        f"=Task {task_idx} moved Data[{d}] from Device[{where}]. Block=[{local_data[d][0, 0]}] | Value=[{local_data[d][0, 1]}], <{old}>", flush=True)
            elapsed = synthetic_kernel(total_time, gil_fraction,
                                       gil_accesses, config=config)
            for d in itertools.chain(write_data_list, rw_data_list):
                data_list[d] = local_data[d]
            if config.verbose:
                print(f"-{task.task_id} Finished: {elapsed} seconds", flush=True)
    except Exception as e:
        print(f"Failed creating Task {task.task_id}: {e}", flush=True)
    finally:
        return
References parla.common.array.clone_here(), parla.utility.execute.get_placement_set_from(), and parla.utility.execute.synthetic_kernel().
Referenced by parla.utility.execute.execute_tasks().
create_task_no_data()
def parla.utility.execute.create_task_no_data (task, taskspaces, config, data_list = None)
Definition at line 264 of file execute.py.
def create_task_no_data(task, taskspaces, config, data_list=None):
    try:
        # Task ID
        task_idx = task.task_id.task_idx
        taskspace = taskspaces[task.task_id.taskspace]
        # Dependency Info
        dependencies = [taskspaces[dep.taskspace][dep.task_idx]
                        for dep in task.task_dependencies]
        # Valid Placement Set
        num_gpus = config.num_gpus
        placement_key = task.task_runtime.keys()
        placement_set_str = list(placement_key)
        placement_set = get_placement_set_from(placement_set_str, num_gpus)
        print("placement key: ", placement_key)
        print("placement set str: ", placement_set_str)
        print("placement set: ", placement_set)
        # TODO: This needs rework with Device support
        # TODO(hc): This assumes that this task is a single task
        # and does not have multiple placement options.
        runtime_info = task.task_runtime[placement_set_str[0]]
        # Task Constraints
        device_fraction = runtime_info.device_fraction
        if config.device_fraction is not None:
            device_fraction = config.device_fraction
        # Task Work
        total_time = runtime_info.task_time
        gil_accesses = runtime_info.gil_accesses
        gil_fraction = runtime_info.gil_fraction
        if config.task_time is not None:
            total_time = config.task_time
        if config.gil_accesses is not None:
            gil_accesses = config.gil_accesses
        if config.gil_fraction is not None:
            gil_fraction = config.gil_fraction
        # print("task idx:", task_idx, " dependencies:", dependencies, " vcu:", device_fraction,
        # " placement:", placement_set, " placement key:", placement_set_str)
        @spawn(taskspace[task_idx], dependencies=dependencies, vcus=device_fraction, placement=[placement_set])
        async def task_func():
            if config.verbose:
                print(f"+{task.task_id} Running", flush=True)
            elapsed = synthetic_kernel(total_time, gil_fraction,
                                       gil_accesses, config=config)
            if config.verbose:
                print(f"-{task.task_id} Finished: {elapsed} seconds", flush=True)
    except Exception as e:
        print(f"Failed creating Task {task.task_id}: {e}", flush=True)
    finally:
        return
References parla.utility.execute.get_placement_set_from(), and parla.utility.execute.synthetic_kernel().
Referenced by parla.utility.execute.execute_tasks().
estimate_frequency()
def parla.utility.execute.estimate_frequency (n_samples = 10, ticks = 1900000000)
Definition at line 49 of file execute.py.
def estimate_frequency(n_samples=10, ticks=1900000000):
    import cupy as cp
    stream = cp.cuda.get_current_stream()
    cycles = ticks
    device_id = 0
    print(f"Starting GPU Frequency benchmark.")
    times = np.zeros(n_samples)
    for i in range(n_samples):
        start = time.perf_counter()
        gpu_bsleep_nogil(device_id, int(ticks), stream)
        stream.synchronize()
        end = time.perf_counter()
        print(f"...collected frequency sample {i} ", end-start)
        times[i] = (end-start)
    times = times[2:]
    elapsed = np.mean(times)
    estimated_speed = cycles/np.mean(times)
    median_speed = cycles/np.median(times)
    print("Finished Benchmark.")
    print("Estimated GPU Frequency: Mean: ", estimated_speed,
          ", Median: ", median_speed, flush=True)
    
    return estimated_speed
Referenced by parla.utility.execute.GPUInfo.update_cycles().
execute_graph()
def parla.utility.execute.execute_graph (Dict[int, DataInfo] data_config, Dict[TaskID, TaskInfo] tasks, RunConfig run_config, List[TimeSample] timing)
Definition at line 548 of file execute.py.
def execute_graph(data_config: Dict[int, DataInfo], tasks: Dict[TaskID, TaskInfo], run_config: RunConfig, timing: List[TimeSample]):
    @spawn(vcus=0)
    async def main_task():
        graph_times = []
        for i in range(run_config.inner_iterations):
            data_list = generate_data(
                data_config, run_config.data_scale, run_config.movement_type)
            # Initialize task spaces
            taskspaces = {}
            for task, details in tasks.items():
                space_name = details.task_id.taskspace
                if space_name not in taskspaces:
                    taskspaces[space_name] = TaskSpace(space_name)
            graph_start_t = time.perf_counter()
            execute_tasks(taskspaces, tasks, run_config, data_list=data_list)
            for taskspace in taskspaces.values():
                await taskspace
            graph_end_t = time.perf_counter()
            graph_elapsed = graph_end_t - graph_start_t
            graph_times.append(graph_elapsed)
        graph_times = np.asarray(graph_times)
        graph_t = TimeSample(np.mean(graph_times), np.median(graph_times), np.std(
            graph_times), np.min(graph_times), np.max(graph_times), len(graph_times))
        timing.append(graph_t)
References parla.utility.execute.execute_tasks(), parla.utility.execute.generate_data(), and parla.TaskSpace.
Referenced by parla.utility.execute.run().
execute_tasks()
def parla.utility.execute.execute_tasks (taskspaces, Dict[TaskID, TaskInfo] tasks, RunConfig run_config, data_list = None)
Definition at line 523 of file execute.py.
def execute_tasks(taskspaces, tasks: Dict[TaskID, TaskInfo], run_config: RunConfig, data_list=None):
    spawn_start_t = time.perf_counter()
    # Spawn tasks
    for task, details in tasks.items():
        # print("task:", task, ", details:", details)
        if run_config.movement_type == MovementType.NO_MOVEMENT:
            # print("No data movement")
            create_task_no_data(details, taskspaces,
                                config=run_config, data_list=data_list)
        elif run_config.movement_type == MovementType.EAGER_MOVEMENT:
            # print("Eager data movement")
            create_task_eager_data(details, taskspaces,
                                   config=run_config, data_list=data_list)
        elif run_config.movement_type == MovementType.LAZY_MOVEMENT:
            # print("Lazy data movement")
            create_task_lazy_data(details, taskspaces,
                                  config=run_config, data_list=data_list)
    spawn_end_t = time.perf_counter()
    return taskspaces
References parla.utility.execute.create_task_eager_data(), parla.utility.execute.create_task_lazy_data(), and parla.utility.execute.create_task_no_data().
Referenced by parla.utility.execute.execute_graph().
generate_data()
List[np.ndarray] parla.utility.execute.generate_data (Dict[int, DataInfo] data_config, float data_scale, data_movement_type)
Definition at line 126 of file execute.py.
def generate_data(data_config: Dict[int, DataInfo], data_scale: float, data_movement_type) -> List[np.ndarray]:
    value = 0
    data_list = []
    # If data does not exist, this loop will not be iterated.
    for data_idx in data_config:
        data_info = data_config[data_idx]
        data_location = data_info.location
        data_size = data_info.size
        if data_location == DeviceType.CPU_DEVICE:
            data = np.zeros([data_size, data_scale],
                            dtype=np.float32) + value + 1
            data_list.append(data)
        elif data_location > DeviceType.ANY_GPU_DEVICE:
            import cupy as cp
            with cp.cuda.Device(data_location - 1) as device:
                data = cp.zeros([data_size, data_scale],
                                dtyp=np.float32) + value + 1
                device.synchronize()
                data_list.append(data)
        else:
            raise NotImplementedError("This device is not supported for data")
        value += 1
        
    return data_list
#TODO(wlr): Rewrite this supporting multiple device placement.
References parla.utility.execute.make_parrays().
Referenced by parla.utility.execute.execute_graph().
get_placement_set_from()
def parla.utility.execute.get_placement_set_from (ps_str_set, num_gpus)
Definition at line 100 of file execute.py.
def get_placement_set_from(ps_str_set, num_gpus):
    ps_set = []
    # TODO(hc): This assumes a single device task.
    for ps_str in ps_str_set[0]:
        dev_type = int(ps_str)
        if dev_type == DeviceType.ANY_GPU_DEVICE:
            ps_set.append(gpu)
        elif dev_type == DeviceType.CPU_DEVICE:
            ps_set.append(cpu)
        # TODO(hc): just assume that system has 4 gpus.
        elif dev_type == DeviceType.GPU_0:
            ps_set.append(gpu(0))
        elif dev_type == DeviceType.GPU_1:
            ps_set.append(gpu(1))
        elif dev_type == DeviceType.GPU_2:
            ps_set.append(gpu(2))
        elif dev_type == DeviceType.GPU_3:
            ps_set.append(gpu(3))
        elif dev_type >= DeviceType.USER_CHOSEN_DEVICE:
            gpu_idx = (dev_type - DeviceType.USER_CHOSEN_DEVICE) % num_gpus
            ps_set.append(gpu(gpu_idx))
        else:
            raise ValueError("Does not support this placement:", dev_type)
    return tuple(ps_set)
References parla.cython.device_manager.gpu.
Referenced by parla.utility.execute.create_task_eager_data(), parla.utility.execute.create_task_lazy_data(), and parla.utility.execute.create_task_no_data().
make_parrays()
def parla.utility.execute.make_parrays (data_list)
Definition at line 42 of file execute.py.
def make_parrays(data_list):
    parray_list = list()
    for i, data in enumerate(data_list):
        parray_list.append(asarray(data, name="data"+str(i)))
    return parray_list
References parla.common.parray.from_data.asarray().
Referenced by parla.utility.execute.generate_data().
run()
TimeSample parla.utility.execute.run (Dict[TaskID, TaskInfo] tasks, Dict[int, DataInfo] data_config = None, RunConfig run_config = None)
Definition at line 586 of file execute.py.
def run(tasks: Dict[TaskID, TaskInfo], data_config: Dict[int, DataInfo] = None, run_config: RunConfig = None) -> TimeSample:
    if run_config is None:
        run_config = RunConfig(outer_iterations=1, inner_iterations=1,
                               verbose=False, threads=1, data_scale=1)
    timing = []
    for outer in range(run_config.outer_iterations):
        outer_start_t = time.perf_counter()
        with Parla(logfile=run_config.logfile):
            internal_start_t = time.perf_counter()
            execute_graph(data_config, tasks, run_config, timing)
            internal_end_t = time.perf_counter()
        outer_end_t = time.perf_counter()
        parla_total_elapsed = outer_end_t - outer_start_t
        parla_internal_elapsed = internal_end_t - internal_start_t
    return timing[0]
References parla.utility.execute.execute_graph().
Referenced by parla.cython.core.PyInnerScheduler.__dealloc__().
synthetic_kernel()
def parla.utility.execute.synthetic_kernel (int total_time, Union[Fraction, float] gil_fraction, int gil_accesses, RunConfig config)
A simple synthetic kernel that simulates a task that takes a given amount of time
and accesses the GIL a given number of times. The GIL is accessed in a fraction of
the total time given.
Definition at line 179 of file execute.py.
def synthetic_kernel(total_time: int, gil_fraction: Union[Fraction, float], gil_accesses: int, config: RunConfig):
    """
    A simple synthetic kernel that simulates a task that takes a given amount of time
    and accesses the GIL a given number of times. The GIL is accessed in a fraction of
    the total time given.
    """
    if config.verbose:
        task_internal_start_t = time.perf_counter()
    # Simulate task work
    kernel_time = total_time / gil_accesses
    free_time = kernel_time * (1 - gil_fraction)
    gil_time = kernel_time * gil_fraction
    #print(f"gil accesses: {gil_accesses}, free time: {free_time}, gil time: {gil_time}", flush=True)
    for i in range(gil_accesses):
        free_sleep(free_time)
        lock_sleep(gil_time)
    if config.verbose:
        task_internal_end_t = time.perf_counter()
        task_internal_duration = task_internal_end_t - task_internal_start_t
        return task_internal_duration
    return None
@synthetic_kernel.variant(architecture=gpu)
Referenced by parla.utility.execute.create_task_eager_data(), parla.utility.execute.create_task_lazy_data(), and parla.utility.execute.create_task_no_data().
synthetic_kernel_gpu()
def parla.utility.execute.synthetic_kernel_gpu (int total_time, Union[Fraction, float] gil_fraction, int gil_accesses, RunConfig config)
A simple synthetic kernel that simulates a task that takes a given amount of time
and accesses the GIL a given number of times. The GIL is accessed in a fraction of
the total time given.
Definition at line 208 of file execute.py.
def synthetic_kernel_gpu(total_time: int, gil_fraction: Union[Fraction, float], gil_accesses: int, config: RunConfig):
    """
    A simple synthetic kernel that simulates a task that takes a given amount of time
    and accesses the GIL a given number of times. The GIL is accessed in a fraction of
    the total time given.
    """
    if config.verbose:
        task_internal_start_t = time.perf_counter()
    # Simulate task work
    cycles_per_second = _GPUInfo.get_cycles_per_second()
    kernel_time = total_time / gil_accesses
    free_time = kernel_time * (1 - gil_fraction)
    gil_time = kernel_time * gil_fraction
    free_ticks = int((free_time/(10**6))*cycles_per_second)
    gil_ticks = int((gil_time/(10**6))*cycles_per_second)
    # print(f"gil accesses: {gil_accesses}, free time: {free_time}, gil time: {gil_time}")
    for i in range(gil_accesses):
        print(dev_id[0]().device_id, parla_cuda_stream.stream, flush=True)
        gpu_bsleep_nogil(dev_id[0]().device_id, int(
            ticks), parla_cuda_stream.stream)
        parla_cuda_stream.stream.synchronize()
        lock_sleep(gil_time)
    context = get_current_context()
    for device in context.loop():
        device_idx = device.gpu_id
        stream = device.cupy_stream
        for i in range(gil_accesses):
            gpu_bsleep_nogil(device_idx, free_ticks, stream)
            gpu_bsleep_gil(device_idx, gil_ticks, stream)
            if config.inner_sync:
                stream.synchronize()
    
    if config.outer_sync:
        context.synchronize()
    if config.verbose:
        task_internal_end_t = time.perf_counter()
        task_internal_duration = task_internal_end_t - task_internal_start_t
        return task_internal_duration
    task_internal_end_t = time.perf_counter()
    task_internal_duration = task_internal_end_t - task_internal_start_t
    # print("Wall clock duration:", task_internal_duration, ", user passed total time:", total_time, ", ticks:", ticks , flush=True)
    return None
References parla.common.globals.get_current_context().
timeout()
def parla.utility.execute.timeout (seconds_before_timeout)
Decorator that raises an exception if the function takes longer than seconds_before_timeout to execute.
https://stackoverflow.com/questions/21827874/timeout-a-function-windows
Definition at line 721 of file execute.py.
def timeout(seconds_before_timeout):
    """
    Decorator that raises an exception if the function takes longer than seconds_before_timeout to execute.
    https://stackoverflow.com/questions/21827874/timeout-a-function-windows
    """
    def deco(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            res = [Exception('function [%s] timeout [%s seconds] exceeded!' % (
                func.__name__, seconds_before_timeout))]
            def newFunc():
                try:
                    res[0] = func(*args, **kwargs)
                except Exception as e:
                    res[0] = e
            t = Propagate(target=newFunc)
            t.daemon = True
            try:
                t.start()
                t.join(seconds_before_timeout)
                r = t.value
            except Exception as e:
                print('Unhandled exception in Propagate wrapper', flush=True)
                raise e
            ret = res[0]
            if isinstance(ret, BaseException):
                raise ret
            return ret
        return wrapper
    return deco
verify_complete()
bool parla.utility.execute.verify_complete (Dict[TaskID, List[TaskID]] log_graph, Dict[TaskID, List[TaskID]] truth_graph)
Verify that all tasks in the truth graph have completed exceution in the log graph.
Definition at line 646 of file execute.py.
def verify_complete(log_graph: Dict[TaskID, List[TaskID]], truth_graph: Dict[TaskID, List[TaskID]]) -> bool:
    """
    Verify that all tasks in the truth graph have completed exceution in the log graph.
    """
    for task in truth_graph:
        if task not in log_graph:
            print(f"Task {task} not in log graph")
            return False
    return True
verify_dependencies()
def parla.utility.execute.verify_dependencies (Dict[TaskID, List[TaskID]] log_graph, Dict[TaskID, List[TaskID]] truth_graph)
Verify that all dependencies in the truth graph have completed execution in the log graph.
Definition at line 628 of file execute.py.
def verify_dependencies(log_graph: Dict[TaskID, List[TaskID]], truth_graph: Dict[TaskID, List[TaskID]]):
    """
    Verify that all dependencies in the truth graph have completed execution in the log graph.
    """
    for task in truth_graph:
        details = truth_graph[task]
        for dependency in details.task_dependencies:
            if dependency not in log_graph:
                print(
                    f"Dependency {dependency} of task {task} not in log graph")
                return False
    return True
verify_ntasks()
def parla.utility.execute.verify_ntasks (Dict[TaskID, TaskTime] log_times, Dict[TaskID, List[TaskID]] truth_graph)
Verify that the number of tasks in the log graph is the same as the number of tasks in the truth graph.
Definition at line 680 of file execute.py.
def verify_ntasks(log_times: Dict[TaskID, TaskTime], truth_graph: Dict[TaskID, List[TaskID]]):
    """
    Verify that the number of tasks in the log graph is the same as the number of tasks in the truth graph.
    """
    if len(log_times) != len(truth_graph)+1:
        print(
            f"Number of tasks in log graph ({len(log_times)}) does not match number of tasks in truth graph ({len(truth_graph)})")
        return False
    return True
verify_order()
bool parla.utility.execute.verify_order (Dict[TaskID, TaskTime] log_times, Dict[TaskID, List[TaskID]] truth_graph)
Verify that all tasks have run in the correct order in the log graph.
Definition at line 611 of file execute.py.
def verify_order(log_times: Dict[TaskID, TaskTime], truth_graph: Dict[TaskID, List[TaskID]]) -> bool:
    """
    Verify that all tasks have run in the correct order in the log graph.
    """
    for task in truth_graph:
        details = truth_graph[task]
        for dependency in details.task_dependencies:
            if log_times[task].start_t < log_times[dependency].end_t:
                print("Task {task} started before dependency {dependency}")
                return False
    return True
verify_states()
bool parla.utility.execute.verify_states (log_states)
Verify that all tasks have visited all states in a valid order.
Definition at line 693 of file execute.py.
def verify_states(log_states) -> bool:
    """
    Verify that all tasks have visited all states in a valid order.
    """
    for task in log_states:
        states = log_states[task]
        instance = task.instance
        # if ('SPAWNED' not in states):
        # print(f"Task {task} did not spawn", flush=True)
        # return False
        if ('MAPPED' not in states):
            print(f"Task {task} was not mapped.", states, flush=True)
            return False
        if ('RESERVED' not in states):
            print(f"Task {task} was not reserved.", states, flush=True)
            return False
        # if ('RUNNING' not in states):
        # print(f"Task {task} did not run.", states, flush=True)
        # return False
        if ('RUNAHEAD' not in states):
            print(f"Task {task} was not runahead", states, flush=True)
            return False
    return True
verify_time()
bool parla.utility.execute.verify_time (Dict[TaskID, TaskTime] log_times, Dict[TaskID, List[TaskID]] truth_graph, float factor = 2.0)
Verify that all tasks execute near their expected time.
Definition at line 659 of file execute.py.
def verify_time(log_times: Dict[TaskID, TaskTime], truth_graph: Dict[TaskID, List[TaskID]], factor: float = 2.0) -> bool:
    """
    Verify that all tasks execute near their expected time.
    """
    for task in truth_graph:
        details = truth_graph[task]
        # TODO: This needs to be fixed for device support
        device_idx = (-1,) # CPU
        expected_time = details.task_runtime[device_idx].task_time
        observed_time = log_times[task].duration / 1000
        if observed_time > expected_time * factor:
            print(
                f"Task {task} took too long to execute. Expected {expected_time} us, took {observed_time} us")
            return False
    return True
Variable Documentation
__all__
list parla.utility.execute.__all__ [private]
Initial value:
= [run, verify_order, verify_dependencies,
           verify_complete, verify_time, timeout, GraphContext]
Definition at line 811 of file execute.py.
_GPUInfo
parla.utility.execute._GPUInfo = GPUInfo() [private]
Definition at line 97 of file execute.py.
PArray
parla.utility.execute.PArray = parray.core.PArray
Definition at line 39 of file execute.py.